### ISSUE TITLE
Custom icons and file colours based on file name

### ISSUE THREAD

**Issue by tomitrescak** [robertohuertasm/vscode-icons#100]
Hi, In my Meteor.js project I have files that have different suffixes "_collection", "_view", "_container". It would be great if I could change the icon based on the file name. Also, do you have any idea if the colour of the filename can be changed as well ?

Something similar to this:

![screen shot 2016-07-22 at 3 53 23 pm](https://cloud.githubusercontent.com/assets/2682705/17047817/7a0dd686-5024-11e6-9e3c-5da9e2d3b67c.png)

**Comment by jens1o** [comment]
Great suggestion!
:+1:
It would be really great, so I can make Interfaces have another color, to have a bit of contrast!

**Comment by robertohuertasm** [comment]
@tomitrescak custom file associations has been already shipped. Custom colors will be also considered.

**Comment by tomitrescak** [comment]
@robertohuertasm thanks for this wonderful update! ;) I already put it to the good use ;)

Just an idea here. What if you wouldn't use images to display icons but actual icons from fontawesome or others. This way, users would be free to modify the behaviour to their liking and use myriads of possible icons. Something in this ballpark: https://atom.io/packages/file-icons

Yet, since you have to modify actual vscode files to make this work, I guess it would not be easy :/

Thanks again!

**Comment by robertohuertasm** [comment]
@tomitrescak I've also explored this idea too but it's not the easiest path to follow at the moment. Microsoft is exploring similar ideas and willing to integrate the extension to their new coming API [#10294](https://github.com/Microsoft/vscode/issues/10294)

**Comment by robertohuertasm** [comment]
I'm closing this issue as it's partially completed. I've created [#203](https://github.com/robertohuertasm/vscode-icons/issues/203) to explore file coloring.

**Comment by ciel** [comment]
I'm really confused. Does this functionality exist? I followed the [link to #203](https://github.com/robertohuertasm/vscode-icons/issues/203) and was left even more confused.

**Comment by robertohuertasm** [comment]
@ciel check my comment in #946

**Comment by ciel** [comment]
Thank you so much. You're absolutely phenomenal. I am loving this extension SO much! It's made my work space so much cleaner and prettier. 
![2017-05-25-04-58-001](https://cloud.githubusercontent.com/assets/438196/26445748/d01fad0a-4106-11e7-8d08-06863b3cb269.png)
![2017-05-25-04-58-002](https://cloud.githubusercontent.com/assets/438196/26445757/d9e0bc08-4106-11e7-8e73-58857dee4eb0.png)
![2017-05-25-04-59-001](https://cloud.githubusercontent.com/assets/438196/26445771/e502b686-4106-11e7-9148-57d89bebe9f6.png)

**Comment by jens1o** [comment]
Just to clarify, this issue was where the extension didn't used the official way, but we hacked inside to provide these icons, even then when `vscode` didn't supported them. This way we had the possibility to make anything we can imagine.(e.g. file coloring) And now we hope that `vscode` supports the things we had(considered to) implement(ed).
