### ISSUE TITLE
Icons in tabs

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#101]

**Comment by jens1o** [comment]
:-1:
I don't like this idea, and even tabs in VSCode is something I don't like. Is there an option also in planning?

**Comment by robertohuertasm** [comment]
I've been asked by several colleagues to implement this and I like it. I will try to make it optional if feasible to make you happy 😉

**Comment by Empereol** [comment]
@jens1o Add `"workbench.editor.showTabs": false` to your User Settings to disable tabs.

**Comment by jens1o** [comment]
No, I actually like tabs. But I won't like it, when there is an icon next to the filename in tab view. I want an option for this.

**Comment by mysticman** [comment]
I like this idea, and I think it would be also very usefull like the icons what was not implemented by the VSCode  developers.

I am waiting for this update :)

**Comment by robertohuertasm** [comment]
@mysticman could you elaborate your second statement. I'm not sure to understand what you mean... Thanks! :wink:

**Comment by mysticman** [comment]
Doesn't matter, I just mentioned that this vs-code-icons plugin is a must have plugin for vscode. I cannot live without it, and as I see 44K downloads is also prove this. :+1:

**Comment by robertohuertasm** [comment]
I completely agree. For what I know they're already working on it. The idea behind this extension was precisely to proof the importance of this cosmetic extension to be viscose native.

**Comment by mysticman** [comment]
Here is a quick sample how is it look like the tab with the icons. Please review it. For me is OK, I like it.

![tab-icon-sample](https://cloud.githubusercontent.com/assets/2445639/17165503/2a512cd2-53d1-11e6-8593-62b2da299ddc.jpg)

**Comment by robertohuertasm** [comment]
@mysticman don't worry. This issue is next in release cycle. :wink:

**Comment by jens1o** [comment]
@mysticman Could you post your editor settings? I like the Atom Style, could you provide it for me too?

**Comment by robertohuertasm** [comment]
@jens1o I also use it. It's a theme exentension called one https://marketplace.visualstudio.com/items?itemName=andischerer.theme-atom-one-dark

**Comment by jens1o** [comment]
Thank you. I'll take a look.

**Comment by robertohuertasm** [comment]
Already released in 1.6.0

**Comment by flyinactor91** [comment]
After installing 1.6.0, enabling or updating icons causes tabs to not show at the top of the editor. The blank space for tabs is still allotted, however. Disabling icons causes tabs to appear again.
![1](https://cloud.githubusercontent.com/assets/2596237/17464167/d93cb7a2-5ca5-11e6-823c-fda4d0cc9b64.png)

**Comment by robertohuertasm** [comment]
Any message in your console?

**Comment by flyinactor91** [comment]
Nothing in the debug console

**Comment by robertohuertasm** [comment]
That's weird. Can you inspect the tab with the element inspector and let me know what you see with a screenwriter?

**Comment by flyinactor91** [comment]
Oh. Was running on the only computer which hadn't updated to 1.4.0. Must be a new feature.

**Comment by robertohuertasm** [comment]
Screenshot...  Sorry, I'm in mobile phone

**Comment by robertohuertasm** [comment]
Oh yes, you need 1.4.0 for this to work. I will update the readme.
