### ISSUE TITLE
.scss icon looks very narrow and dark in the editor 

### ISSUE THREAD

**Issue by mysticman** [robertohuertasm/vscode-icons#108]
Hi,

I am using kind of a dark theme, and the .scss icon is very hard to see. I am always search with my eyes the icon (.scss files) what is almost not visible. 

As on the original logo he color is much brighter pink maybe it worth a try to see how is it look it.

Here is a quick sample how is it look like the old one and the brighter one.

![scss-sample-color](https://cloud.githubusercontent.com/assets/2445639/17165657/3dcad79e-53d2-11e6-9f85-0e3470bc093c.png)

**Comment by robertohuertasm** [comment]
You're absolutely right. Feel free to make a PR with the new icon and I'll publish it asap

**Comment by robertohuertasm** [comment]
Solved in #109
