### ISSUE TITLE
package.json this is JSON

### ISSUE THREAD

**Issue by mrmlnc** [robertohuertasm/vscode-icons#11]
File `package.json` does not belong to the npm. This is a typical json file.

Maybe it's better this way:

```
{ icon: "npm", extensions: ["npmignore"] },
```

**Comment by rozzzly** [comment]
Or custom code that checks for existance of `node_modules`, `.npmignore`. Possibly even reading the file to see if it looks like the `package.json` schema, but I think that probably overkill/prone to hiccups.

**Comment by robertohuertasm** [comment]
@mrmlnc I just used the npm icon because I mostly use package.json on npm context. What other contexts does this file has? I've look into atom's icons and they just mark it as json. In fact, I just added this change today so... I can change it again if we have quorum ;D

**Comment by mrmlnc** [comment]
For example, themes for VS Code:
https://github.com/marvinhagemeister/vscode-theme-afterglow-remastered/blob/master/package.json

Or, languages for VS Code:
https://github.com/mrmlnc/vscode-apache/blob/master/package.json

Or, GitBook use `package.json` to configure the plugins.

In truth, this is not so important :)

**Comment by robertohuertasm** [comment]
Ok! You've made your point. I'll change it to json icon! :+1:
