### ISSUE TITLE
An advice to slow update speed~

### ISSUE THREAD

**Issue by WilsonLiu95** [robertohuertasm/vscode-icons#110]
Firstly,thank for you works.
I'am enjoy your vscode-icons.
But every few days I open the vscode to code,I can see a remind on the extensions,this is  terrible.
I don't want to update so frequently.
Maybe you can update slower.
And I will enjoy it without trouble

**Comment by mysticman** [comment]
I've never seen an extension issue when it is a problem when the updates comes frequently. This is benefit not an issue. If you don't want to update it just do not update :S I don't get you, there are no breaking changes etc. so why it is an issue.

**Comment by robertohuertasm** [comment]
Hi @WilsonLiu95, thank you very much for your advice but I have an opinion similar to @mysticman's 

The good thing about VS Code is that you decide when to update. You'll get the notification but it's really up to you to update whenever it's best suitable for you. If you like to make your updates on Fridays so be it. No one will stop you.

On the other hand, people like me like to have new features as soon as possible so, as this project is also something I built for myself, being myself a user, I like quick deployment. And I get your point, as some days I maybe can update twice, that's true. But then the project stays quiet for a week. So I don't think this is really an issue. And as I pointed out before, you decide when to apply the updates so...

Anyway, thanks for sharing your point of view which is always something valuable. :wink:

**Comment by WilsonLiu95** [comment]
@mysticman @robertohuertasm thanks for answer my question. Maybe I should not make the issue to express my advice. I am sorry because I am not familiar with the rule of github.

But sometime I update it for more than 3times will make me confused when the network isn't well. I will click the buttons many times.
Finally，thanks for you good extension.
