### ISSUE TITLE
Blue gopher icon for .go files

### ISSUE THREAD

**Issue by xmattstrongx** [robertohuertasm/vscode-icons#111]
Just a nitpick here but the gopher for golang is typically always blue. While there are some pictures of the brown gopher that exist, the little guy is colored in his blue standard most of the time.

I am going to update it myself and use the custom icons format shown in the README. However on my team (all go devs) we all think this color is a bit confusing and agree it should probably be the standard blue gopher. Any thoughts?

**Comment by jens1o** [comment]
You're right. Could you provide an original icon for me? I would create a PR, if you don't want to. But you're allowed to submit a PR at your own.

**Comment by xmattstrongx** [comment]
Ok, Ill get a PR in for this soon.

**Comment by robertohuertasm** [comment]
@xmattstrongx glad to receive your PR anytime :wink:

**Comment by xmattstrongx** [comment]
@robertohuertasm Thanks for allowing contributions 💯 

PR is in 
https://github.com/robertohuertasm/vscode-icons/pull/112

**Comment by robertohuertasm** [comment]
Ready to be published in 1.5.2
