### ISSUE TITLE
Icon Request: .postcss | .pcss extension (PostCSS)

### ISSUE THREAD

**Issue by sean-clayton** [robertohuertasm/vscode-icons#117]
PostCSS is pretty popular, and a lot of people differ PostCSS files from regular CSS files by changing the extension to .postcss or .pcss

Reference for extension names:
- https://github.com/rcsole/postcss-syntax/blob/master/syntaxes/postcss.tmLanguage#L7-L8
- https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS
- https://atom.io/packages/language-postcss

Here is the PostCSS logo files:
https://github.com/postcss/brand

**Comment by sean-clayton** [comment]
@robertohuertasm Would you be willing to take PRs on this? I wouldn't mind making one :smiley_cat:

**Comment by robertohuertasm** [comment]
@sean-clayton for sure! Go ahead! :+1:

**Comment by sean-clayton** [comment]
@robertohuertasm Is #121 a good PR to look at as a reference for adding an icon to an extension? Never made a PR here so I just wanna make sure I submit a good one!
