### ISSUE TITLE
Nunjucks file icon

### ISSUE THREAD

**Issue by iRoachie** [robertohuertasm/vscode-icons#118]
There's no current icon for the Nunjucks templating engine.

Here's a [link](http://mozilla.github.io/nunjucks/) to the main page.

For the icon we can take inspiration from Atom's icon for Nunjucks.
<img width="133" alt="screen shot 2016-07-29 at 9 22 22 pm" src="https://cloud.githubusercontent.com/assets/5962998/17267265/ba8abfe0-55d2-11e6-9968-f97e4c8ae429.png">

**Comment by mrmlnc** [comment]
Filetypes: 

  * `.njk` (official extension)
  * `.nunjucks`
  * `.nunjs`
  * `.nunj`
  * `.njs`
  * `.nj`

**Comment by iRoachie** [comment]
Are they any particular guidelines for icons? I can do up something

**Comment by robertohuertasm** [comment]
Transparent background, 32x32. Take some of the icons.zip file as example and it will suffice.

**Comment by iRoachie** [comment]
@robertohuertasm Good enough? Took same inspiration from atom.
![nunjucks](https://cloud.githubusercontent.com/assets/5962998/17313273/23a235ba-5828-11e6-8972-032a743439c7.png)

**Comment by robertohuertasm** [comment]
Ready to be released in 1.6.0

**Comment by robertohuertasm** [comment]
Already released in 1.6.0
