### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by rbatukaev** [robertohuertasm/vscode-icons#12]
Dockerfile icon is missing after recent update

**Comment by robertohuertasm** [comment]
Solved!

**Comment by FrenchBen** [comment]
Bringing this back up as it doesn't seem to have been solved. This was the latest update in VSCode:
![dockerfile-broken](https://cloud.githubusercontent.com/assets/3965324/18493300/ab7c7ea6-79c4-11e6-9969-f7e463f06bd2.png)


As you can see the `Dockerfile` doesn't have the nice whale on it, like a `.dockerfile` would :(

**Comment by robertohuertasm** [comment]
solved

**Comment by ritabradley** [comment]
I'm having his issue currently  and I'm using the latest versions of both VSC and vscode-icons
![Screen Shot 2019-06-22 at 8 55 47 AM](https://user-images.githubusercontent.com/41173740/59967981-5a9b6380-94e7-11e9-9108-5d6e8561babe.png)

**Comment by JimiC** [comment]
https://github.com/vscode-icons/docker

**Comment by JimiC** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker

**Comment by ritabradley** [comment]
@JimiC I have that extension installed already am still experiencing this issue.

**Comment by JimiC** [comment]
1. Make sure `vscode-icons` is activated.
2. Check your file associations in `settings`.
3. If all fails reinstall the extension.

**Comment by ritabradley** [comment]
What should the file extensions look like because I've done step 1 & 3 to no avail.

**Comment by JimiC** [comment]
Post printscreens of a wider file explorer tree and your settings.

**Comment by ritabradley** [comment]
well right now my file tree is just the Dockerfile but 
![Screen Shot 2019-06-22 at 1 01 32 PM](https://user-images.githubusercontent.com/41173740/59968386-e4e6c600-94ed-11e9-8e87-c7a3fb92c852.png)

**Comment by JimiC** [comment]
The correct setting is:

```
"vsicons.associations.files": [{
  "icon": "docker",
  "extensions": ["Dockerfile.dev", "Dockerfile.prod"]
  "format": ''svg",
  "extends": "docker"
}]
```
as per https://github.com/vscode-icons/vscode-icons/wiki/FineTuning example.

**Comment by ritabradley** [comment]
Still nothing :(

**Comment by ritabradley** [comment]
I uninstalled the icons, reinstalled them, activated them, tried restarting my computer and it's still not showing up. For what it's worth I'm only experiencing it with that particular file.

**Comment by JimiC** [comment]
Give a moment to figure it out.

**Comment by ritabradley** [comment]
Okay. And I need to correct myself, none of the icons are working for me.

**Comment by JimiC** [comment]
```json
"files.associations": {
    "Dockerfile.dev": "dockerfile",
    "Dockerfile.prod": "dockerfile"
  }
```

**Comment by ritabradley** [comment]
I'm not sure it's specific to the Dockerfile anymore. None of the icons work.
![Screen Shot 2019-06-22 at 1 38 42 PM](https://user-images.githubusercontent.com/41173740/59968715-13b36b00-94f3-11e9-9ebb-a0fbaa761c26.png)

**Comment by JimiC** [comment]
That's beyond what I can troubleshoot. You need to figure out what is wrong with your installation.

**Comment by ritabradley** [comment]
It's interesting because I'm not experiencing it with other file icon themes... I'll figure it out

**Comment by JimiC** [comment]
Last advice. 
1. Uninstall `vsicons`
2. Restart `vscode`
3. Reinstall `vsicons`
4. Activate `vscicons`

**Comment by ritabradley** [comment]
I had to completely uninstall vscode and reinstall it in order to get it working. Thanks though!
