### ISSUE TITLE
Vash (Express template engine) icon

### ISSUE THREAD

**Issue by dehghani-mehdi** [robertohuertasm/vscode-icons#120]
Hi,
Thanks for your awesome extension, if is possible, please add `Vash` icon too.

Good luck.

**Comment by jens1o** [comment]
Do you have an official icon for Vash?

**Comment by MehdiDehghani** [comment]
No, but I just sent a request to @kirbysayshi for making an icon. let's hope he add some.

**Comment by robertohuertasm** [comment]
@mehdiDehghani @jens1o Let's wait to have an icon or propose one that may be suitable before implementing this.

**Comment by jens1o** [comment]
Something new @MehdiDehghani?

**Comment by MehdiDehghani** [comment]
@jens1o nope, sadly the `Vash` author didn't response to the request yet.

**Comment by jens1o** [comment]
Hmm, the repo maintainer is inactive in the Vash Repo, I'll close this. Feel free to reopen, if the owner of the Vash Repo respond.

**Comment by robertohuertasm** [comment]
I have an idea for this extension. I see it uses razor syntax, which in Visual Studio uses to be a '@' icon. I think we can use the same motive.

**Comment by dehghani-mehdi** [comment]
I think this idea will work, seems like the Vash author is not active. so looking fwd to the icon. thanks !

**Comment by jens1o** [comment]
Do you have the @ icon? Google doesn't help really.

**Comment by dehghani-mehdi** [comment]
@jens1o I'm afraid, no. my source is Google too.

**Comment by robertohuertasm** [comment]
I'll build it. No problem. But I can't right now. :grin:

**Comment by jens1o** [comment]
Don't hurry. Take your time :wink:
