### ISSUE TITLE
Icon Request: .buildignore extension 

### ISSUE THREAD

**Issue by ajsb85** [robertohuertasm/vscode-icons#122]

**Comment by robertohuertasm** [comment]
@ajsb85 could you suggest an icon for this? In general I accept all icon requests but usually people provide some ideas about icons if the extension has not an official logo. :smile:

**Comment by robertohuertasm** [comment]
@ajsb85 is this extension related to Yeoman or can be used to a more generic purpose? What's the file format? .yml? .xml? .json? A little more help would be really appreciated. :wink:

**Comment by jens1o** [comment]
According to [this file](https://gitlab.com/ulthes/github-repos-catalogue/blob/master/.buildignore), it's looking like the same syntax to .gitignore, but I didn't find any icon...

**Comment by jens1o** [comment]
Closed according to inactivity.
