### ISSUE TITLE
Icon Request: special folder icons

### ISSUE THREAD

**Issue by stefan-kern** [robertohuertasm/vscode-icons#124]
similar to the file-icons package from atom, have an icon for the node_modules folder:

![nm](https://cloud.githubusercontent.com/assets/11061334/17329919/0530a722-58c5-11e6-94c6-593d369be7f4.png)

**Comment by robertohuertasm** [comment]
I like the idea!! Cool!

**Comment by jens1o** [comment]
really nice. :+1: :+1: :+1: Really cool!

**Comment by robertohuertasm** [comment]
I've changed the title to make this clear. The idea is to map some folders to certain icons. We'll provide a few. It would be able to be enabled/disabled. Custom folder associations will work, too.

**Comment by jens1o** [comment]
What "special folder" icons are in planning?

**Comment by robertohuertasm** [comment]
node_modules, .vscode, .meteor, bower, src, dist, typings...

**Comment by stefan-kern** [comment]
i'd propose .git & .hg

**Comment by zozzz** [comment]
Another idea. I would like to define the folder icon based on its contents like this:
```
src
  |_ package_name <- display package icon, because folder contains __init__.py
       |_ __init__.py
```

**Comment by robertohuertasm** [comment]
@zozzz unfortunately, we don't have access to the contents right now :disappointed:

**Comment by jens1o** [comment]
Do we have access to even null? :disappointed:

**Comment by petrmm** [comment]
It will be usefull to distinguish symbolic links like in atom.io
![image](https://cloud.githubusercontent.com/assets/7623513/17932535/c57da528-6a10-11e6-89b9-22f33b6d2ba3.png)

**Comment by robertohuertasm** [comment]
Sorry, but this is not really possible with the current api so nothing can be done here.

**Comment by robertohuertasm** [comment]
1.8.0 is out!

**Comment by jens1o** [comment]
GREAAAAAAAT :heart:  I love it

**Comment by ksmithut** [comment]
Any documentation on how to turn off certain folder associations? Or is it the same as file associations? @robertohuertasm

**Comment by robertohuertasm** [comment]
@ksmithut if you want to disable, let's say "src" icon, just use -as you already suggested- the file associations feature and put something like this:
```json
"vsicons": {
        "useFileAssociations": true,
        "associations":[
            ["src$", ""]
        ]
    }
```
This will make src folder look normal again.

**Comment by Dominik-K** [comment]
>> [icon for symbolic links]

> Sorry, but this is not really possible with the current api so nothing can be done here.

@robertohuertasm Is it the same status now that symbolic links can't be distinguished via API?

**Comment by robertohuertasm** [comment]
As far as I know, nothing has changed regarding this matter. I'd suggest you to raise an issue in `vscode` repo asking for the feature.

**Comment by jens1o** [comment]
We are going to implement that feature as soon as this feature exists, please let us know of your issue. (Reference would be great!)
