### ISSUE TITLE
Icon Request: CHANGELOG 

### ISSUE THREAD

**Issue by ajsb85** [robertohuertasm/vscode-icons#125]

**Comment by robertohuertasm** [comment]
Hi @ajsb85, could you provide an icon for this or suggest one? :wink:

**Comment by ajsb85** [comment]
![image](https://cloud.githubusercontent.com/assets/663460/17331684/48ed9054-58cc-11e6-8e3d-b98cbd70bee1.png)

![image](https://cloud.githubusercontent.com/assets/663460/17331688/4c9038f6-58cc-11e6-96f1-c8e8fd5d19a4.png)

**Comment by iRoachie** [comment]
Isn't changelog just a markdown file?

**Comment by robertohuertasm** [comment]
@iRoachie you're right. I'm going to close this issue. @ajsb85 there's already a log icon in the extension so you can use vscode-icons file associations to change the associated icon to ChangeLog.md.
