### ISSUE TITLE
Obj-c icon for .m files is matlab icon

### ISSUE THREAD

**Issue by mark-holland-leotech** [robertohuertasm/vscode-icons#128]

**Comment by robertohuertasm** [comment]
We have a conflict here and I guess no proper way of resolving it... any ideas?

**Comment by jens1o** [comment]
Do you have the "right" icon for .m?

**Comment by jens1o** [comment]
We could try to change the filename internally and then we handle it just as another type of extension?

**Comment by robertohuertasm** [comment]
@jens1o what do you mean? The way it works is by parsing the file extension. We have no way to know if its matlab or objective-c as we don't have access to the content. The way I see it I only see some settings solution: the user will decide if m is objective or matlab. Maybe we can decide the default based on user usage. What do you think?

**Comment by jens1o** [comment]
That's tricky. But as long as my data won't be published online, I'm fine with it. My plan was reading the first lines and then we're looking for typical things for each language.

Are they any other languages that are using the same extension?

**Comment by mark-holland-leotech** [comment]
You guys currently detect gulp files but I'm guessing it's from the name 'gulpfile.js'?

**Comment by jens1o** [comment]
Yep, that's right. What do you mean?

**Comment by mark-holland-leotech** [comment]
@robertohuertasm I think that when there is a conflict a more generic icon with the .m in it would make sense.

**Comment by robertohuertasm** [comment]
@jens1o I'm not talking about publishing anything and even reading any file content as it cannot be done at the moment with the current state of VSCode regarding treeview customization (which by the way has no api). I'm just talking about looking online to see some stats about language usage, just that.

@mark-holland-leotech The M icon will be another approach I think it would be ok, but I feel that it maybe won't satisfy nor Objective-C nor Matlab users.

**Comment by robertohuertasm** [comment]
In next release, users will have the option to associate any extension to an existing icon. This will let users decide which of the icons to use for a specific extension no matter the default is.

That said, we need an icon for objective-c files. @mark-holland-leotech can you point me to the official one?

**Comment by mark-holland-leotech** [comment]
@robertohuertasm I don't think there is an 'official' icon. Mainly I wanted to avoid the confusion of seeing the Matlab logo so something generic with the extension will be more than sufficient.

**Comment by nimamarashi** [comment]
As a suggestion, I thought we can make it a bit smarter by looking at other extensions in same/sub/parent folders of worksapace.
That means if we have a setting like:
```
{
    icon: 'matlab',
    extensions: ['m', 'fig', 'mat', 'mex', 'mexn', 'mexrs6', 'mn', 'mum', 'mx', 'mx3', 'rwd', 'slx', 'slddc', 'smv', 'tikz', 'xvc', 'xvc'],

},
{
    icon: 'obj-c',
    extensions: ['m','cpp', 'hpp', 'cc', 'cxx'],
},

```
and the folders structure is like:

- index.cc
- method.m
-- hlper.hpp

there is a good chance the 'method.m' file belongs to an obj-c project

Even we can introduce an optional new property in settings named 'expects' to say what are the other extensions we expect to see a in the workspace.

**Comment by robertohuertasm** [comment]
@nimamarashi, unfortunately this is not an option as we only have access to the current file, not the parent nor the siblings. This will be solved by using vscode-icons file extension system once we have a proper icon. We're proposing a default and the user will be able to decide whether to use mathlab icon, the default icon or whatever icon she may like.

**Comment by robertohuertasm** [comment]
I will release 1.7.0 in a moment. .m files will have a simple M icon by default. Mathlab users will be able to change the icon via custom file association.

**Comment by Pedro-Mendes** [comment]
Hi @robertohuertasm 

I've just installed this and the default 'M' mentioned isn't showing up. I keep seeing the objective C icon.
I also tried to change the file association and it still didn´t work.
Any thoughts on this?

Thanks!

**Comment by JimiC** [comment]
@Pedro-Mendes You need to install a 3rd party extension that supports `matlab` syntax highlighting. Search the marketplace.
