### ISSUE TITLE
No icons on OSX

### ISSUE THREAD

**Issue by ksnyde** [robertohuertasm/vscode-icons#129]
I installed on OSX and yet the explorer still has no icons. Is there a step I'm missing?

![2016-08-03_08-47-08](https://cloud.githubusercontent.com/assets/980757/17357903/fc1ff970-5956-11e6-9d97-bfecac643136.png)

![2016-08-03_08-48-30](https://cloud.githubusercontent.com/assets/980757/17357947/27b17e06-5957-11e6-95de-84c44d813bf8.png)

**Comment by jens1o** [comment]
Yep, there's a step. Read the README.

**Comment by ksnyde** [comment]
Oh, silly me. I thought _enabling the addon_ and enabling the _icons_ was the same thing. it's working now. Is there no way to turn this on by default?

**Comment by jens1o** [comment]
No, it is not possible, because we need admin privilges and we need to replace the things while startup.
