### ISSUE TITLE
Translation Things....

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#131]
Would be cool, if we can provide translations. I could provide german translations, because it's my first language.

Could you say the format, in which I have to save the translations?

**Comment by robertohuertasm** [comment]
@jens1o Do you mean for the readme?

**Comment by jens1o** [comment]
Yep, readme and the few sentences shown up in the extension itself.

**Comment by robertohuertasm** [comment]
@jens1o I don't see the point in the Readme. Think of mantaining several languages... Besides that, the readme is used in the market. I don't want to offer people the information twice. If you don't know English then you can use Google Translator, for instance.

About sentences on the other hand, I think it would be ok as we can use the[ same system that VSCode uses](https://code.visualstudio.com/docs/customization/locales ).

**Comment by jens1o** [comment]
Okey, then I'll just provide the senctenes in german ;)

**Comment by robertohuertasm** [comment]
Closing this for the moment.
