### ISSUE TITLE
Add more eslint extensions

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#132]
ESLint supports configuration files in several formats:

    JavaScript - use .eslintrc.js and export an object containing your configuration.
    YAML - use .eslintrc.yaml or .eslintrc.yml to define the configuration structure.
    JSON - use .eslintrc.json to define the configuration structure. ESLint’s JSON files also allow JavaScript-style comments.
    Deprecated - use .eslintrc, which can be either JSON or YAML.
    package.json - create an eslintConfig property in your package.json file and define your configuration there.

If there are multiple configuration files in the same directory, ESLint will only use one. The priority order is:

    .eslintrc.js
    .eslintrc.yaml
    .eslintrc.yml
    .eslintrc.json
    .eslintrc
    package.json

**Comment by jens1o** [comment]
I'm for package.json, because it's one standard.
