### ISSUE TITLE
Groovy icon is missing

### ISSUE THREAD

**Issue by kdureidy** [robertohuertasm/vscode-icons#133]
Groovy icon is missing

**Comment by robertohuertasm** [comment]
@kdureidy if you could provide more info the better for us to implement the icon. e.g. offical logo url, supported extensions... you know...

**Comment by iRoachie** [comment]
@robertohuertasm Original icon taken from groovy [repo](https://github.com/apache/groovy)
![](https://raw.githubusercontent.com/groovy/artwork/master/medium.png)

**Comment by robertohuertasm** [comment]
@iRoachie we already have a groovy icon but was not associated to any extension yet. Now it's associated to .groovy extension. Ready to be released in 1.7.0.

**Comment by kdureidy** [comment]
It is fixed now, thank you
