### ISSUE TITLE
GitHub Templates

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#134]
Would be quite nice if there are some templates for issues and pull requests, for example anyone can see what type of information they have to give us. (Icon Request/Bug Report)

See this [blogpost](https://github.com/blog/2111-issue-and-pull-request-templates) for more informations.

**Comment by robertohuertasm** [comment]
Great idea jens1o!

**Comment by robertohuertasm** [comment]
@jens1o I think this is a must. We're receiving lots of Github issues with no proper information like #140 or #137. Can you take care of it? If you want, of course. :wink: If not, I will try to create this templates asap. Maybe we can review them together and decide if they're right or wrong. What do you think?

**Comment by jens1o** [comment]
Of course :)

I'll do that, you'll correcting my grammar mistakes, right?

**Comment by robertohuertasm** [comment]
Of course! :stuck_out_tongue_winking_eye: Many thanks Jens! :grinning:

**Comment by robertohuertasm** [comment]
@jens1o Super amazing work you've done here! :100:

**Comment by jens1o** [comment]
:smile: 
You've made me laughing loudly.

**Comment by robertohuertasm** [comment]
@jens1o we could also add into the issues template the steps needed to ask for an icon: extensions, official icon, alternative icon... what do you think?

**Comment by jens1o** [comment]
That sounds great. Also, how about explicity asking them for bugs?

**Comment by jens1o** [comment]
*notices in Dev Console

**Comment by robertohuertasm** [comment]
It's cool for me!

**Comment by jens1o** [comment]
Should/Could I take care of it?

**Comment by robertohuertasm** [comment]
Of course: wink:

**Comment by jens1o** [comment]
:smile:

**Comment by jens1o** [comment]
The only problem is, after all the Template is way too long. :sob:

**Comment by robertohuertasm** [comment]
Yes, you're right. I've already thought about this but I prefer to be explicit even at risk of overwhelm the other users and receive proper feedback from the beginning. If not, we'll end up writing always the same questions to the same type of request.

**Comment by jens1o** [comment]
GitHub should improve this, and make it more intiuitve.

**Comment by jens1o** [comment]
How about add a notice about the title?(Or adding a label.)

It oftens confused me, whether it is a icon request or a foldericon request. Could we add a notice here @robertohuertasm ?

**Comment by robertohuertasm** [comment]
It's OK for me. Great ideas: specific label and template check. :+1:

**Comment by jens1o** [comment]
Can you create the labels?

**Comment by robertohuertasm** [comment]
@jens1o you got it! :grin:

**Comment by jens1o** [comment]
thanks
