### ISSUE TITLE
Icon Request: xib, storyboard

### ISSUE THREAD

**Issue by ad1Dima** [robertohuertasm/vscode-icons#137]
xcode interface files has no icon

**Comment by jens1o** [comment]
Official Icon is missing.

**Comment by ad1Dima** [comment]
Icons from Xcode7 app package 
<img width="512" alt="xib" src="https://cloud.githubusercontent.com/assets/3244664/17468481/a3cb149e-5d52-11e6-90fa-f9f3f1ef92eb.png">
<img width="512" alt="storyboard" src="https://cloud.githubusercontent.com/assets/3244664/17468480/a3ca4456-5d52-11e6-9ebc-4a8f3cfa385f.png">

**Comment by jens1o** [comment]
Without the shadows? We need to cut it to 32x32. The shadow takes way too much space.

**Comment by ad1Dima** [comment]
it's official icons, but I think you can keep just inner symbol without shadow, curl and border

**Comment by jens1o** [comment]
Can somebody extract the last frames of these two images? I cannot to that, due I don't know how to do ;)

**Comment by robertohuertasm** [comment]
I'll take care. No worries.
