### ISSUE TITLE
Icon request: ASPX

### ISSUE THREAD

**Issue by mikiest** [robertohuertasm/vscode-icons#139]
Love your extension :+1: 

There is currently no icon for .aspx files. These files are often web forms or pages and could be represented by a simple web-related icon (e.g. a "world"). Alternatively something with a simple "ASPX" would do the job.

**Comment by jens1o** [comment]
The icons.zip does not contain an world-related icon, we'll have to create one.

**Comment by robertohuertasm** [comment]
We'll try to use Visual Studio Icons. The same goes for other Visual Studio related icons like #136

**Comment by robertohuertasm** [comment]
See #151

**Comment by jens1o** [comment]
I'd found a icon. PR coming soon.
