### ISSUE TITLE
How to enable the icons?

### ISSUE THREAD

**Issue by galvesribeiro** [robertohuertasm/vscode-icons#14]
Hi!

Thanks for bring icons back.

I don't know what is going on but, I installed the extension as admin but, where are the commands to enable the Icons?

Thanks!

**Comment by robertohuertasm** [comment]
In Windows and Linux just use the Ctrol+P key combination. Then enter Icons Enable. Is it not showing this for you?

**Comment by galvesribeiro** [comment]
Hey @robertohuertasm nop, it isn't :(

I'm with latest release version of Code and Windows 10:

```
Version 1.1.1
Commit def9e32467ad6e4f48787d38caf190acbfee5880
Date 2016-05-13T13:29:20.776Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

**Comment by mrmlnc** [comment]
You should open the editor with administrator privileges and invoke the command: enable icons. After that the admin mode is not needed.

**Comment by galvesribeiro** [comment]
@mrmlnc  I did... the command never appear:

![image](https://cloud.githubusercontent.com/assets/4714040/15801254/015e6946-2a66-11e6-964d-ef33da31938d.png)

![image](https://cloud.githubusercontent.com/assets/4714040/15801256/0d0bde54-2a66-11e6-9c90-9b6349a4b9b3.png)

**Comment by NomNes** [comment]
Press ctrl+shift+P

**Comment by galvesribeiro** [comment]
AHHHHHH was missing the SHIFT :)

Thank you guys! Keep this great work! :)
