### ISSUE TITLE
Icons enable doesn't work (Win 8.1)

### ISSUE THREAD

**Issue by MehdiDehghani** [robertohuertasm/vscode-icons#145]
Hi,
Thanks for your great extension.

First of all, please note, at my work, I'm using Windows 10, & I enabled your extension successfully.

But at home, I just installed `vscode-icons`, and run VS Code in `Administrator` mode, but `Icons Enable` doesn't work.

- I'm using latest version of Visual Studio Code & your extension.
- I'm using Windows 8.1
- I'm sure this issue is not a *duplicate*? I googled first and found nothing.

BTW, when I run `Icons Disable `, VS Code telling me, `you need to restart VS Code to see the effect`.

**Comment by robertohuertasm** [comment]
Please, take a look into the dev console and let us know what you see.

**Comment by MehdiDehghani** [comment]
I'm sorry, what you mean? I'm not familiar with dev console that you mentioned.

**Comment by robertohuertasm** [comment]
Go to VSCode menu > Help > Toggle Developer Tools > Console

**Comment by jens1o** [comment]
http://prntscr.com/c21m5m
If there's any error when you're clicking on console, let us know.

**Comment by MehdiDehghani** [comment]
![vsicons](https://cloud.githubusercontent.com/assets/9152330/17444566/ea5cc1fe-5b55-11e6-9753-55f63b1cf7a5.png)

**Comment by jens1o** [comment]
Looks like there is an proxy before you. Please check your windows enviroment variables for the Proxy connection.

**Comment by robertohuertasm** [comment]
This seems to me like a proxy issue. See #21

**Comment by MehdiDehghani** [comment]
I tired everything about `proxy`, but no success.
But with `offline icons support` I have your icon set. (thanks for that)
