### ISSUE TITLE
file extensions not working

### ISSUE THREAD

**Issue by rickmed** [robertohuertasm/vscode-icons#146]
vscode 1.4
win 10 x64

I have this 

```
    // Configure file associations to languages (e.g. "*.extension": "html"). These have precedence over the default associations of the languages installed.
    "files.associations": {
        "*.js?": "javascript",
        "*.es": "javascript"
    },

    "vsicons.useFileAssociations": true,
```
_Actual behaviour:_
only .js files are "iconized"

![image](https://cloud.githubusercontent.com/assets/7104786/17452153/9afd3028-5b3a-11e6-87d0-b3411c1868b2.png)

**Comment by jens1o** [comment]
Can confirm it.
This does not work. (I just don't recognized.)
http://prntscr.com/c26rpi

VSCode 1.4 Stable.
Windows 10 64x

**Comment by robertohuertasm** [comment]
My bad... First of all, no regular expression or glob patterns are supported. Second, I didn't really think about file associations already having its own convention (they use "javascript" instead of "js" for associations) so this won't work. I will fix it asap and let you know :disappointed: The only way for this to work at the moment would be this:
```json
"*.es": "js"
```

But as I said, wait for the fix. :wink:

**Comment by robertohuertasm** [comment]
I've just published 1.5.6 that will fix this. Still not supporting complex patterns but will cover the most common scenarios.

To use it, you won't be using *file.associations* anymore but a custom property inside vsicons:

```json
{
  "vsicons": {
     "useFileAssociations": true,
      "associations":{
        "*.cc": "css"
      }
    }
}
```
In your case, first case is not supported at the moment, but I will try to implement it if possible  :wink:

**Comment by rickmed** [comment]
@robertohuertasm does not seem to be working for me.

in user settings.json
```
// VS Icons

  "vsicons": {
     "useFileAssociations": true,
      "associations":{
        "*.es": "js"
      }
    }
```
the options does not appear on the workspace settings (not sure if relevant)

same environment as above

**Comment by robertohuertasm** [comment]
You're right, now only supported extensions will work... . es is not in the list of supported extensions so it won't be considered. 

I'll try to fix it tonight. Sorry for the inconveniences!

**Comment by robertohuertasm** [comment]
It's already fixed. #152 
Will be released soon in a major version with other enhancements.

**Comment by chai2010** [comment]
@robertohuertasm great work, thanks!

**Comment by robertohuertasm** [comment]
Already released in 1.6.0

**Comment by rickmed** [comment]
@robertohuertasm does not work for me. Same config as above (also tried several extensions values

**Comment by robertohuertasm** [comment]
Please, read the new readme as this has changed to support regular expressions.

**Comment by rickmed** [comment]
@robertohuertasm Tried a bunch of configs until I hit the update command :sweat_smile:

**Comment by robertohuertasm** [comment]
@rickmed thanks for your feedback. I'll update the readme to make it more explicit.
