### ISSUE TITLE
Official Visual Studio Image Library

### ISSUE THREAD

**Issue by julianpaulozzi** [robertohuertasm/vscode-icons#151]
Find many consistent icons and keeping them can be a pain. Have you considered using the official library of the Visual Studio images?

See: 

- [Visual Studio Image Library](https://www.microsoft.com/en-us/download/details.aspx?id=35825).
- [Microsoft Software License Terms](http://download.microsoft.com/download/0/6/0/0607D8EA-9BB7-440B-A36A-A24EB8C9C67E/Visual%20Studio%202015%20Image%20Library%20EULA.docx)

Thanks!

**Comment by jens1o** [comment]
Thank you!

I'll take a look and make a PR if there is any good icon to replace!

**Comment by jens1o** [comment]
I'm working on a Microsoft related Icon Pack.

**Comment by julianpaulozzi** [comment]
See if this helps: https://github.com/julianpaulozzi/vscode-icons-image-lib/

**Comment by robertohuertasm** [comment]
@julianpaulozzi Great work!! We'll update the readme with your new addition. Is there support for all the currently supported icons or there are some missing?

**Comment by julianpaulozzi** [comment]
At the moment it supports the icons with the extensions seen in "sample_files".

However there are some setpoints for the future, for example:

In supportedExtensions.js
node [json] to json [json]
reactjs [jsx] to jsx[jsx]
...

All visual studio project and solution types icons are available on Visual Studio Image Library, but they should be added to supportedExtensions.js.

Probably the "dark theme" will have to be a separated icon package due to outline color.

**Comment by jens1o** [comment]
Great!

I'll contribute to your one!

**Comment by julianpaulozzi** [comment]
At the weekend preparing a "supported Extensions.js" with additions.
The icons that I have not found just use the [default icons](http://github.com/robertohuertasm/vscode-icons/blob/master/icons.zip).

**Comment by jens1o** [comment]
But then you'll have to update your package every time this one becomes an update.

**Comment by julianpaulozzi** [comment]
At the time yes, but Primary and fallback Icon Pack #155 idea would be nice.

**Comment by robertohuertasm** [comment]
I'm closing this as this is already implemented as a separate set of items :+1:
