### ISSUE TITLE
Icons for .js.map

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#154]

**Comment by iRoachie** [comment]
Any ideas for this ?

**Comment by robertohuertasm** [comment]
Current js icon with a world globe in the lower right corner?

**Comment by iRoachie** [comment]
Good? 
![js map](https://cloud.githubusercontent.com/assets/5962998/18030771/4dd89c6e-6c93-11e6-8e81-cc88b3b57fac.png)

**Comment by robertohuertasm** [comment]
@iRoachie I've just implemented it 😞 . 
It's pretty similar though. The js color has a little alpha with white to make it different from js icon and the globe is actually closer to the js text.

**Comment by iRoachie** [comment]
@robertohuertasm Alright cool man no sweat 👍
