### ISSUE TITLE
Primary and fallback Icon Pack.

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#155]
**Checklist:**
- [X] I'm sure this issue is not a *duplicate*?

**Description:**

Would be really nice if it's possible to add an primary URL, and then a fallback URL. Why? Simply, if I want to create an icon pack, I have to feature all of the existing icons. So it's useful if I can set a primary Icon Pack URL and then a secondary, if one icon isn't found in the primary, it's searching in the secondary.

**Comment by robertohuertasm** [comment]
@jens1o I don't know if we're going to need this as once we integrate with the official API it will have no sense. In fact, every pack of icons will be an extension itself.

**Comment by jens1o** [comment]
You're right. Since the new api, this suggestion as now sense, I'm closing.
