### ISSUE TITLE
Auto Enable extension

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#156]
**Checklist:**
- [x] I'm sure this issue is not a *duplicate*?

**Description:**

Some users seem to be struggling always with the "Icons Update" command and they think that just updating the extension is enough to get the latest bits.

The idea is to save the state of the extension (enabled / disabled) and the previous version installed (if any). Then once, we activate the extension will check for this information and proceed to auto enable the extension.

**Comment by jens1o** [comment]
But I don't want to start VSCode generally as admin, because other extension could read out all my data. If they don't are open-source, I don't want to give them admin permission.

**Comment by robertohuertasm** [comment]
This doesn't affect anything regarding permissions. It's the same as before. Every time you wanted to update the extension you should execute it as admin. Now it's the same. This only automates the process of launching the update command. That's all.

**Comment by robertohuertasm** [comment]
Published in 1.6.3
