### ISSUE TITLE
Can't uninstall, extension is gone, but icons are still present

### ISSUE THREAD

**Issue by drulia** [robertohuertasm/vscode-icons#157]
I'm using Visual Studio Code Version 1.4.0
I'm using the extension version 1.6.3
My system is: Win 10 64bit

**Steps to reproduce:**
1. Install the extension (start VSCode as administrator)
2. restart for the changes to take effect
3. uninstall the extension (start VSCode as administrator)
4. restart for the changes to take effect

_Expected behaviour:_
VSCode to return to it's original shape

_Actual behaviour:_
All icons are still visible, even though extension folder is gone from extension folder

**Comment by robertohuertasm** [comment]
Before 3 you should execute the "Icons Disable" command to restore the bak files. You can reinstall the extension again and do as I said. It should do the trick. :wink:

**Comment by drulia** [comment]
indeed that worked, thanks!
