### ISSUE TITLE
New icon proposal: csv

### ISSUE THREAD

**Issue by agenestar** [robertohuertasm/vscode-icons#158]
**Checklist:**
- [x] I want to create an icon request(if not, remove these lines below):
      - Icon Name: **csv**
      - Sample original Icon(32x32/png/transparent whenever possible): [link](http://findicons.com/files/icons/977/rrze/32/csv_text.png)
      - Extensions: **.csv**
- [x] I'm sure this issue is not a *duplicate*?

**Description:**

New icon proporal for **.csv files**.

**Comment by iRoachie** [comment]
Looks okay? Took this screenshot from atom. Once it's good I can make it in 5 mins.
<img width="32" alt="screen shot 2016-08-20 at 8 28 00 am" src="https://cloud.githubusercontent.com/assets/5962998/17831185/097983d2-66b0-11e6-9c69-05ac7257a4ae.png">

**Comment by jens1o** [comment]
Sure, it's okey, but please transparent and 32x32.

**Comment by iRoachie** [comment]
Here you go
![csv](https://cloud.githubusercontent.com/assets/5962998/17834514/8888b682-6711-11e6-947b-10f0a76f9698.png)

**Comment by iRoachie** [comment]
@robertohuertasm Here you go.
![csv](https://cloud.githubusercontent.com/assets/5962998/17834544/298cfae2-6713-11e6-8386-9f8608d22109.png)

**Comment by robertohuertasm** [comment]
Can we make it green so we can use it for xls and xlsx files? We could use the official excel green.

**Comment by agenestar** [comment]
I normally use OpenOffice. Can we also add the .ods extension?

Do you like that green?
![298cfae2-6713-11e6-8386-9f8608d22109](https://cloud.githubusercontent.com/assets/10512395/17838858/b3e50bc0-67d7-11e6-97de-1618e7339373.png)

**Comment by robertohuertasm** [comment]
Ready to be released in 1.7.0 in a moment!

**Comment by Chris2011** [comment]
Can't find the icon, what is the name or was it replaced?

**Comment by JimiC** [comment]
Look in https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles

**Comment by Chris2011** [comment]
Great, thx.

**Comment by laukikk** [comment]
> Look in https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles

Can't find the updated icon for csv, tsv files. Has it been switched back?

**Comment by JimiC** [comment]
> > Look in https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles
> 
> Can't find the updated icon for csv, tsv, it still shows the same as txt. Has it been switched back?

There's no updated icon. CSV is basically a text file containing comma separated data and TSV has tab separated data, thus both have the txt icon.
