### ISSUE TITLE
Add icon for .cake extension

### ISSUE THREAD

**Issue by gep13** [robertohuertasm/vscode-icons#16]
How would I go about doing this?

This would be to support this build automation tool:

http://cakebuild.net/

Thanks!

**Comment by robertohuertasm** [comment]
Solved! Uploaded right now

**Comment by gep13** [comment]
@robertohuertasm thanks! Where does the actual cake icon reside though?

**Comment by robertohuertasm** [comment]
Icons are downloaded to resources/app/out/vs/workbench/parts/files/browser/media/icons/ folder. 
Depending on your OS you will have to look in Program Files (x86), inside your .app contents or in usr/share/code

**Comment by gep13** [comment]
@robertohuertasm sorry, that wasn't my question, but now I see what you have done...  I didn't notice the icons.zip in your commit: https://github.com/robertohuertasm/vscode-icons/commit/ce232284dc586cd2f656aa0f9d6cfb02e99720bc so I couldn't see where you were adding the cake icon.  But now I see what you are doing.

Thanks!

**Comment by robertohuertasm** [comment]
@gep13 :+1:
