### ISSUE TITLE
Icons have stopped appearing in Ubuntu 16.04 

### ISSUE THREAD

**Issue by jorawarsingh** [robertohuertasm/vscode-icons#161]
Hi first of all thanks for a useful extension.
Now i had this working extension before upgrading to 16.04. I have tried everything re-installed the vs-code more then 4 times removed all the files and folder manually as mentioned in another same issue which is closed now.

Help me to get them back.

**Comment by robertohuertasm** [comment]
Please take a look at #87 and #113 and honor the issue template if possible next time :wink:

**Comment by jorawarsingh** [comment]
@robertohuertasm sorry that i didn't honor the template but i have tried these all steps around 10 times yesterday without any success and that's why i opened this issue.

**Comment by robertohuertasm** [comment]
Let's continue this  in #113 and close this thread.
