### ISSUE TITLE
Linux container/object icon change request for 'hidden' types

### ISSUE THREAD

**Issue by razblack** [robertohuertasm/vscode-icons#162]
- [X] Visual Studio Code Version [1.4.0] [Stable/Insider]
- [X] Extension version [1.6.3]
- [X] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [X] My system is: Linux Mint 'Sarah'
- [X] I'm sure this issue is not a *duplicate*?
- [ X ] I want to create an icon request(if not, remove these lines below):
      - Icon Name: [hidden file & hidden folder]
      - Sample original Icon(32x32/png/transparent whenever possible): [none]
      - Extensions: any or none, hidden files/folders in linux 'start' with "."
      - [X] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**
[
Linux file system uses "." on directory or file names to represent "hidden" containers and objects.  I know that in Visual Studio, (as an example), the directory ".vscode" is shown with a slightly lighter and transparent color to represent it in the tree, perhaps this could also be done for similar files/directories in VSCode-Icons theme :)
]

**Comment by robertohuertasm** [comment]
This could be considered as an extension of #203

**Comment by robertohuertasm** [comment]
Closing this. See #328. Ask for the feature in vscode's repo.
