### ISSUE TITLE
Icons of the tabs disappear to reload window.

### ISSUE THREAD

**Issue by Tekbr** [robertohuertasm/vscode-icons#163]
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10
- Version vscode-icons: 1.6.4

-- Sorry for the English, I used Google Translator --

1- Open one or more files.
2- Press F1 and type "Reload Window" or close the VSCode and open it again.
3- See the icons disappear from the guides.
4- It is necessary to open a new file or tab for the icons to appear again or close it and open again.

**Comment by robertohuertasm** [comment]
Thanks @Tekbr for reporting this! I see that this is only happening in insider version. The stable version seems to be working fine. I'll take a look at it.

**Comment by robertohuertasm** [comment]
Something has changed in vscode refreshtabs function and they don't resolve the file name now in the same place so when the code flow gets into the custom icons function I don't have access to the name. I've solved it by calling to a context function though :wink: 

Solved in 1.6.5. Published right now.

**Comment by Tekbr** [comment]
@robertohuertasm It worked. Thank you again.
