### ISSUE TITLE
Icon Request: .apib extension

### ISSUE THREAD

**Issue by jsynowiec** [robertohuertasm/vscode-icons#167]
- Icon name / file name: [API Blueprint](https://apiblueprint.org/)
- Extensions: .apib
- 100x100 png with transparent background [file_type_apib@2x.png](https://cloud.githubusercontent.com/assets/1029142/17697540/b1f5553e-63b5-11e6-89d9-bb10f0dbc3aa.png)

![file_type_apib 2x](https://cloud.githubusercontent.com/assets/1029142/17697540/b1f5553e-63b5-11e6-89d9-bb10f0dbc3aa.png)

**Comment by jens1o** [comment]
What is this file-type called?

**Comment by jsynowiec** [comment]
API Blueprint: https://github.com/apiaryio/api-blueprint

**Comment by robertohuertasm** [comment]
Ready to be released in 1.7.0

**Comment by pedrosalpr** [comment]
This icon was released @robertohuertasm? Because in my vscode this icon does not appear.

**Comment by jens1o** [comment]
@pedrosalpr Please see https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles

You need to install an extension which provides that language id.

**Comment by pedrosalpr** [comment]
The `apib` extension does not handle the `apiblueprint` icon.

![captura de tela 2017-11-17 as 11 18 13](https://user-images.githubusercontent.com/5918761/32949219-2eef6b56-cb89-11e7-9759-d3d45409d2fe.png)

**Comment by jens1o** [comment]
@pedrosalpr Please create an new issue and we're going to fix it then. :)
