### ISSUE TITLE
Add icon for PowerShell (.ps1, .psm, .psd)

### ISSUE THREAD

**Issue by alex-hempel** [robertohuertasm/vscode-icons#17]
An icon for PowerShell files would be great.

Something like this would probably work:

https://chocolatey.org/content/packageimages/powershell-packagemanagement.10.0.10586.117.png

Cheers, keep up the great work!

**Comment by robertohuertasm** [comment]
@alex-hempel .psd can also be a photoshop file... I've uploaded the icon associated with ps1, psm1, psd1 according to this post: http://stackoverflow.com/questions/12107462/file-extension-for-powershell-3

Let me know if you feel this is wrong 😉

**Comment by alex-hempel** [comment]
@robertohuertasm, excellent work, thanks so much for the quick update! And you are of course correct, I got the PowerShell extensions wrong :)

**Comment by jonathanheaden** [comment]
![file_type_powershell 2x](https://cloud.githubusercontent.com/assets/6761609/18576135/00017116-7c22-11e6-9d50-6ac505c29ae3.png)
Thanks for this - love your work!
One thing of note for using dark themes is that the official Powershell logo has the Angle bracket and underscore white, not transparent.
