### ISSUE TITLE
Icon request: assembly

### ISSUE THREAD

**Issue by basdp** [robertohuertasm/vscode-icons#172]
I'm doing a lot of assembly in vscode lately, but there aren't any icons for that kind of files. Usual file extensions are `.s`/`.S`, and `.asm`.

I like the blue C/H icons for c and header files. Perhaps a blue 'S' icon? Maybe another color to distinguish them?

Thanks!

**Comment by iRoachie** [comment]
Whatcha think of this? I'll do the final version, if this concept is good
<img width="28" alt="screen shot 2016-08-20 at 8 19 55 pm" src="https://cloud.githubusercontent.com/assets/5962998/17834549/7ded105e-6713-11e6-8283-e24a0d18c295.png">

**Comment by basdp** [comment]
I like it!

**Comment by robertohuertasm** [comment]
@iRoachie :+1:

**Comment by iRoachie** [comment]
Here's it!
![assembly](https://cloud.githubusercontent.com/assets/5962998/17839355/2c86b756-67b3-11e6-978e-ee121d20d1d3.png)

**Comment by jens1o** [comment]
@iRoachie Your icons are *really* nice, great work!

**Comment by robertohuertasm** [comment]
Ready to be released in 1.7.0 in a moment!
