### ISSUE TITLE
No Icons in VSCode 1.5.0-insiders

### ISSUE THREAD

**Issue by brakmic** [robertohuertasm/vscode-icons#173]
I've followed the FAQ and tried to activate icons with "Update" but no luck. My VSCode is:

```
Version 1.5.0-insider
Commit 3d9622208b2167921b6664e04fd1fbd51507a4a0
Date 2016-08-19T06:08:05.883Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
```

I'm running a Win10 x64 (Anniversary Update)

**Comment by jens1o** [comment]
Any error in the debug console?

**Comment by brakmic** [comment]
No errors at all.

**Comment by Tekbr** [comment]
I have the same problem. For me, the icons of files as "html, css, js" does not appear in the 'Explorer', but the tabs appear. The icons of folders typically carry the 'Explorer'.

**Comment by MLefebvreICO** [comment]
Same here, only folder icons are present now :/

**Comment by robertohuertasm** [comment]
Have you all tried "Icons Update" command?

**Comment by MLefebvreICO** [comment]
@robertohuertasm 
First message from @brakmic states : 
> I've followed the FAQ and tried to activate icons with "Update" but no luck.

**Comment by robertohuertasm** [comment]
@MLefebvreICO I've read it but I didn't know if you all have tried or not :wink: that's why I asked to all of you. I guess you've tried. Could you be more specific on how this happens? I mean, is it your first install? Did you upgrade your vscode or the extension?

**Comment by MLefebvreICO** [comment]
It's not my first install.

I upgraded vscode, seeing there were no icons, I then upgraded the extension(which I  don't always update), but no luck.

**Comment by jens1o** [comment]
I can reproduce that with a fresh install of the Insider Version, extension version (fresh installed) 1.6.5.

The padding for the icon does appear, but the icon itself won't be shown.

**Comment by robertohuertasm** [comment]
The new insiders version made a change that has broken the extension. I've already fixed and will make a patch release in a few minutes.

**Comment by robertohuertasm** [comment]
I've just published v1.6.6 with the fix. Let me know if you find some issues.

**Comment by jens1o** [comment]
Works after executing(and restarting) "Icons Update"

**Comment by brakmic** [comment]
Same here: the new version works after Update/Restart/"Enable Icons"

Many thanks, @robertohuertasm :+1:

**Comment by safderali5** [comment]
every time update comes for the vs code, this extension breaks, updated the extension, and when i run 
icon update, the vs code hangs forever with blank screen, i have to uninstall and install it again, still extension do not work.
running vs code on debian 8.5

**Comment by robertohuertasm** [comment]
@safderali5 take a look at [this](https://github.com/robertohuertasm/vscode-icons/issues/140#issuecomment-245841274)
