### ISSUE TITLE
Migrate to the new Icon Extension Contribution Point

### ISSUE THREAD

**Issue by egamma** [robertohuertasm/vscode-icons#177]
The August release (avail in September) includes a new Contribution Point for icon extensions. We would much appreciate if this extension is migrated to this Contribtuion Point.

//CC @aeschli

**Comment by egamma** [comment]
@aeschli started the documentation in this issue  https://github.com/Microsoft/vscode/issues/10804

**Comment by robertohuertasm** [comment]
Recommended steps to migration according to @aeschli:
1. vscode-icons pushes an update early enough before we ship 1.5 currently planned for Sept 12th
2.  this update of vscode-icons bundles icons using the official way of the new icons theme contribution point
3. this update of vscode-icons includes a check for the ‘vscode.version’ being 1.5.0 or newer (using semver)
4.  if the extension run in vscode 1.5.0 or newer, disable the ‘runAutoInstall’ call and show a message to the user for any of the contributed commands (e.g. Enable Icons)
5. the message includes instructions for how to enable the icons (File > Preferences > File Icon Theme)

**Comment by robertohuertasm** [comment]
Done. Released as 2.0.1

**Comment by egamma** [comment]
@robertohuertasm this is great. Thanks for the great collaboration 🌹

**Comment by robertohuertasm** [comment]
@egamma thanks to you and you're team for bringing icons to VSCode. I'm looking forward to seeing this contribution point grow in terms of functionality and user customization. :smile:
