### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by laimonas** [robertohuertasm/vscode-icons#18]
After latest vscode 1.2.0 update icons not showing any more.
Windows 10

**Comment by robertohuertasm** [comment]
I've just tested in a Windows 10 virtual machine and it's working with 1.2.0 version. Did you upgrade from a very early version? Try reinstalling vscode. You won't loose your extensions as they're kept between installations but all the core files will be renewed.

**Comment by laimonas** [comment]
I just try to reinstall fresh vscode. Removed all extensions and install only this one. The i cons not showing. The same happens to my colleague.

**Comment by robertohuertasm** [comment]
Sorry to ask but just in case, did you execute the icons enable command, didn't you?

**Comment by robertohuertasm** [comment]
I don't know what's really happening. Here you can see my test with 1.20 version working.
![image](https://cloud.githubusercontent.com/assets/696981/15853309/c5411490-2ca4-11e6-8fa6-5125e754d30c.png)

**Comment by laimonas** [comment]
That's right i forgot about this. Now it's working. But after vscode upgrade i think icons should stay if they where enabled before.

**Comment by robertohuertasm** [comment]
That's not possible at the moment. As the extension modifies some vscode core files, if you upgrade vscode the reinstallation process will erase all the mods. It's all in the readme. ;D
