### ISSUE TITLE
Support for Dockerfile-<environment>

### ISSUE THREAD

**Issue by a-magdy** [robertohuertasm/vscode-icons#181]
- [x] I'm using Visual Studio Code Version [1.4.0] [6276dcb0ae497766056b4c09ea75be1d76a8b679]
- [x] I'm using the extension version [1.7.2]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] My system is: [mac] [64]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Icon Name: [docker]
      - Sample original Icon(32x32/png/transparent whenever possible): [url]
      - Extensions: Dockerfile-*
      - [ ] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**
I have other Dockerfile(s), for environments, for example, [Dockerfile, Dockerfile-development], I've used this convention from other projects running docker, and I want the Dockerfile-* to have the icon of Docker as well

**Comment by robertohuertasm** [comment]
Hi @a-magdy, this can be configured by setting this in your user.settings:
```json
 "vsicons": {
        "hideFolders": false,
        "useFileAssociations": true,
        "associations":[
            ["Dockerfile-", "dockerfile"]
        ]
    }
```
Cheers!
