### ISSUE TITLE
Icon Request: .travis.yml

### ISSUE THREAD

**Issue by AlexandreSNeto** [robertohuertasm/vscode-icons#185]
- [x] I want to create an icon request:
      - Icon Name: Travis CI
      - Sample original Icon(32x32/png/transparent whenever possible): https://docs.travis-ci.com/favicon.ico
      - Extensions: .travis.yml

**Comment by iRoachie** [comment]
Another possible icon.
 ![](http://cibuddy.com/img/travis-logo.png)

**Comment by robertohuertasm** [comment]
I prefer the original one if possible.

**Comment by iRoachie** [comment]
Will see if I can do it today
