### ISSUE TITLE
New icon proposal: dart

### ISSUE THREAD

**Issue by vatok** [robertohuertasm/vscode-icons#186]
**Checklist:**

- [x] I want to create an icon request(if not, remove these lines below):
      - Icon Name: dartlang
      - Sample original Icon(32x32/png/transparent whenever possible): [Link](https://www.dartlang.org/favicon.ico)
      - Extensions: .dart

New icon proporal for .dart files.

**Comment by robertohuertasm** [comment]
The same here with the margin. I think a little bit smaller will be great!

**Comment by jens1o** [comment]
For sure.
