### ISSUE TITLE
Icon request : Paket

### ISSUE THREAD

**Issue by JonCanning** [robertohuertasm/vscode-icons#188]
I want to create an icon request for [Paket](http://fsprojects.github.io/Paket/)

Icon Name: paket

Sample original Icon: https://dl.dropboxusercontent.com/u/11302680/logo.png

Extensions:

- paket.dependencies
- paket.lock
- paket.references
- paket.template
- paket.local

**Comment by robertohuertasm** [comment]
Are this extensions or file names?

**Comment by JonCanning** [comment]
They're the file names
