### ISSUE TITLE
Vuejs icon

### ISSUE THREAD

**Issue by MartinJBates** [robertohuertasm/vscode-icons#19]
Hi,

Can you add the icon .vue files please? http://vuejs.org/

**Comment by MartinJBates** [comment]
No longer needed

**Comment by aaroncolclough** [comment]
![file_type_vue](https://cloud.githubusercontent.com/assets/12542251/15860979/0eddb39c-2cc3-11e6-84fb-4d9e879461c4.png)
![file_type_vue 2x](https://cloud.githubusercontent.com/assets/12542251/15860980/0ee78b1a-2cc3-11e6-880a-cd8cb8fc2621.png)

**Comment by robertohuertasm** [comment]
Done! It's already published! 1.0.21
