### ISSUE TITLE
New Icons: go, zip, rar, php

### ISSUE THREAD

**Issue by llkiriell** [robertohuertasm/vscode-icons#197]
Proposed icons:

* go:  
![golang](https://k60.kn3.net/C/D/2/D/C/6/110.png)
* rar:  
![rar](https://k61.kn3.net/1/E/5/4/5/2/BAE.png)
* zip:  
![zip](https://k60.kn3.net/F/0/F/D/C/E/E30.png)
* php:  
![php](https://k61.kn3.net/D/0/7/C/A/6/2AD.png)

 #**Link:** [Icons](http://goo.gl/56yxL2)

**Comment by robertohuertasm** [comment]
Go, zip, and pop are already implemented.

**Comment by robertohuertasm** [comment]
The zip icon is generic at the moment and it's used for all kind of compressed files. Thanks anyway.

**Comment by jens1o** [comment]
php is also implemented, and I love the elefant how it looks.
