### ISSUE TITLE
some icons have not been displayed 

### ISSUE THREAD

**Issue by smallnest** [robertohuertasm/vscode-icons#2]
OS: Windows 10
vscode: 1.1.1
vscode-icons: latest(0.2.14)

I checked icons.zip and it has contained two icons for go.

[
![file-icons](https://cloud.githubusercontent.com/assets/865763/15734085/55a91022-28be-11e6-848a-f93c66db3a6f.png)
](url)

**Comment by robertohuertasm** [comment]
Done! As usual, download the new version, disable and enable icons and restart vscode.

**Comment by smallnest** [comment]
Thanks.
Deleted this plugin and installed it again. It works normally.
