### ISSUE TITLE
File colours based on file name

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#203]
This issue is coming from [#100](https://github.com/robertohuertasm/vscode-icons/issues/100) by @tomitrescak

> Hi, In my Meteor.js project I have files that have different suffixes "_collection", "_view", "_container". It would be great if I could change the icon based on the file name. Also, do you have any idea if the colour of the filename can be changed as well ?

It will be explored here.

**Comment by jens1o** [comment]
:+1: Next good idea, nice!

**Comment by jens1o** [comment]
How we will technical do that? Will spans be used or direct css to the item?

**Comment by whitecolor** [comment]
I wonder if it is possible to style in some way icons for git ignored files, for example make them faded or desaturated. Also something like this would be use for files that are in search.exclude option of .vscode/settings.json.

File name colors could be affected to reflect their nature.

**Comment by whitecolor** [comment]
@robertohuertasm how that goes is it possible to manage file colors of the files/folders?

**Comment by robertohuertasm** [comment]
@whitecolor this feature could be more or less implemented but I will refer back to [#235](https://github.com/robertohuertasm/vscode-icons/issues/235#issuecomment-243574260) .

**Comment by jens1o** [comment]
@robertohuertasm Is that feature in planning by the VS Code Team? Due we have limited time they allowing injecting code, it would be great when this will be solved by VS Code itself.

**Comment by robertohuertasm** [comment]
For what I know this is not in VSCode team's plans. In fact, there's no way for a user to customize any icon association except if the author of the extension has used language associations. I'm trying to convince them of the power of using custom regular expressions but I feel they're not interested in giving the user so much options. :disappointed:

**Comment by aeschli** [comment]
Adding to more sophisticated name matching is surely possible. Maybe not the full RegEx. The current implementation of associating icons to names is done through CSS and I'd like to stick to that (makes switching themes easy and avoids direct coupling of views to the themes). CSS has prefix/suffix or substring operators that we could use.

**Comment by robertohuertasm** [comment]
Closing this. See #328
