### ISSUE TITLE
How to assign myself?

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#204]
Hey,

it's just a github question, so I leaved out our template. Is there any option on GitHub to assign myself, without being the owner? Can you set something, that would be really useful, which person will resolve this issue.

Greets,
Jens

**Comment by Gama11** [comment]
No, only users with push permissions on a repo can be assigned.

**Comment by robertohuertasm** [comment]
That's right. At the moment you can leave a message in the issue by saying that you're taking care of it.
