### ISSUE TITLE
icons.zip corrupt - even after uninstalling/reinstalling

### ISSUE THREAD

**Issue by BakerNet** [robertohuertasm/vscode-icons#205]
**Checklist:**
- [X ] I'm using Visual Studio Code Version [1.4.0] [Stable]
- [X ] I'm using the extension version [1.8.1]
- [x ] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x ] My system is: Windows 10
- [x ] I'm sure this issue is not a *duplicate*?

**Description:**
After installing, updating, and enabling icons running as administrator, icons did not work.  **Uninstalled and tried again, same issue.**
icons.zip file corrupted

[**PLEASE INSERT THE ERROR(S) YOU CAN SEE IN DEV CONSOLE HERE**]

Using dev tools, saw errors: ERR FILE DOES NOT EXIST @ C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\browser\parts\editor\media\icons\_________.png
(or something similar)

Unfortunately, I did not think to take screenshots.

icons folder only had 2 files in it, Files.svg and file_type_acitonscript@2x.png, which was not a valid png.

icons.zip was present in media folder, but if I try to unzip it, I get "archive is corrupt" error from WinRAR with several errors for specific image files.

I manually added files to icons folder from download via GitHub (in case my icons.zip was the issue).  After manually adding files to icons, it worked fine.

**Steps to reproduce:**
Not sure.

_Expected behaviour:_
icons.zip should unzip to icons folder with each icon file

_Actual behaviour:_
icons.zip corrupted, not unzipping properly

**Comment by robertohuertasm** [comment]
@BakerNet maybe something went wrong while we were merging the zip files... Now it should be working ok. Can you confirm?

**Comment by robertohuertasm** [comment]
not working... I see... I will publish a patch right now and see what's happening.

**Comment by robertohuertasm** [comment]
I think it should be solved... can anyone confirm it?

**Comment by BakerNet** [comment]
I had to uninstall and reinstall Code in order for icons.zip to download/unzip.  It seems to have worked fine this time.

**Comment by BakerNet** [comment]
Thanks for the great extension, BTW!

**Comment by robertohuertasm** [comment]
There was an issue with the icons.zip generator during build time. It's now solved. Thanks @BakerNet for reporting it so soon :wink: :+1:
