### ISSUE TITLE
The extension is not removed

### ISSUE THREAD

**Issue by Riim** [robertohuertasm/vscode-icons#208]
After removing the extension icons still remain in the editor. Rebooting does not help.

https://yadi.sk/i/X_nnknF0uYG8N
https://yadi.sk/i/VQcwCqYXuYG9h

**Comment by robertohuertasm** [comment]
Yes, at the moment you have to exec icons disabled before uninstalling. This will restore your original vscode files.

**Comment by jens1o** [comment]
To do so, you need to reinstall the Extension and then execute Icon Disable.

**Comment by Riim** [comment]
> Icon Disable

It works. Thanks.
