### ISSUE TITLE
Icon request: VOLT

### ISSUE THREAD

**Issue by TiTnOuK** [robertohuertasm/vscode-icons#209]
**Phalcon template engine: Volt** has no icon.
Website URL : [Link](https://docs.phalconphp.com/en/latest/reference/volt.html)
Icon that can be used : [Link](https://commons.wikimedia.org/wiki/File:Phalcon_logo.png)
File extension : **.volt**

If you can add it, the Phalcon users would be delighted  :)

**Comment by jens1o** [comment]
I'll integrate it.

**Comment by jens1o** [comment]
see #210
