### ISSUE TITLE
Installed Extension no icons appear

### ISSUE THREAD

**Issue by jbeckton** [robertohuertasm/vscode-icons#21]
How do you enable these? A command was mentioned on the download page but where or how do you enter this command? I entered it into the command palette with no luck.  Please provide enough information so that I can enjoy these icons.

**Comment by mrmlnc** [comment]
1. Run VS Code with admin privileges
  2. Install this extension
  3. Press `Restart Now`
  4. Press `F1` and select `Icons Enable` or `Icons Update` (if extension was updated)
  5. Close VS Code
  6. Run VS Code

**Comment by robertohuertasm** [comment]
@jbeckton I already answered your question on the marketplace.
The truth is that I didn't think of explaining how to execute commands as this is a common feature of VS Code. I'll add this information in case someone else finds it difficult.

@mrmlnc has explained all the process to follow perfectly. :+1: 

@jbeckton could you be so kind of updating your stars assesment?

**Comment by jbeckton** [comment]
Thanks but the steps presented by mrmInc require a step that is not very common. Opening the command palette and entering a command and then hitting return is common, I do it all day long. Rarely do I have to restart the editor after entering a command. In fact I can't remember any instance where I had to restart the editor with the exception of installing extensions or updates.

I did however restart the editor just to see if it would have any effect and it did not. I have a Mac at home with the latest OS so I am not sure if there is a specific step I missed for that OS. I did read your docs about certain Linux distros but I was not sure if that included the latest OSX.

I will gladly update my rating as I am not trying to discredit your hard work, I was frustrated at Microsoft since they cannot provide such a simple UX element as icons, I have a large project and VS Code is making it more difficult to find things, they have taken "Simple" beyond it's usefulness.

**Comment by robertohuertasm** [comment]
@jbeckton as you may have already read in the docs this extension is some sort of a hack so restarting is needed in order to see the changes. That said, I'm not really sure why is not working for you. I also have a Mac and this is the easiest OS to make it work as you won't need to run vscode in administrator mode.

Could you tell me exactly what are you doing? I mean, this should be a very simple process. Lots of people with Macs, Windows and Linux are already using it without any problem so clearly, there must be something that we're missing and I'll be more than glad to modify the docs to make it clearer to all the users.

**Comment by jbeckton** [comment]
I just ran the install command again and it shows that the extension is already installed so I clicked the update button and this time I got a restart prompt. So I clicked it and still no icons. So I closed vs code by right clicking the icon and selecting quit. Still no icons..  

I guess it doesn't like me.. lol

![screen shot 2016-06-08 at 9 58 28 pm](https://cloud.githubusercontent.com/assets/2669585/15918536/f2150532-2dc4-11e6-9536-e353a4d7605d.png)

**Comment by robertohuertasm** [comment]
@jbeckton you're missing the most important step. I guess you're using a Mac, aren't you? If that's the case, once you have installed vscode-icons and restarted the IDE you have to enter the "Icons Enable" command. How would you do that? Easy. As @mrmlnc pointed out you just have to press F1 and then the command palette will pop up with a ">" icon in it. Then type in "icons enable" and hit Enter. Restart again, and you should enjoy our fancy icons! 😁 

Let me know if it works for you!

**Comment by jbeckton** [comment]
@robertohuertasm I'll try this again tonight when I get home. I ran that command already with no luck. But, I think I am in a better state now after running the update for the icons last night I did get the restart prompt after the update but I did not after the initial install.

**Comment by madrus** [comment]
I have two computers running VSCode v1.3 under Windows 10. I installed VSCode Icons on both of them. I started VSCode as Administrator on both. I ran `Ctrl-Shift-P` and `Icons Enable` on both of them. One of them echoed `Icons enabled. Restart to take effect`, the other one - nothing. I restarted VSCode on both of them. On the first one the icons appeared in Explorer. In the other one - nothing. No matter how many times I had them enabled, updated, disable or even reinstalled the extension. Is there any way to fix this or find the reason?

**Comment by robertohuertasm** [comment]
@madrus maybe something went wrong when injecting the code. Reinstall VSCode. The extensions will remain but all the original files will be restored again.

**Comment by madrus** [comment]
@robertohuertasm i did reinstall. no luck so far. i am beginning to suspect the corporate proxy. that is a tricky thing anyway. i have configured the `cntlm` local proxy and it is a classic solution for all stuff atom, vscode, nodejs, etc. when behind a corporate proxy. otherwise they don's install, upgrade, etc.

now, every time i run 'icons enable' or 'icons update', this error message appears in my event veiwer: 
>  cntlm: PID 18604: 127.0.0.1 CONNECT github.com:443

or
> cntlm: PID 18604: 127.0.0.1 CONNECT vscode-update.azurewebsites.net:443

It could also be a regular vscode check for updates, I am not 100% sure. The error message that I see also says something like this (translated from Dutch): 
> Cannot find the description of the event-id 0 of the source cntlm. The module that raised this event possibly is not installed on the local computer or the installations is corrupt. You can reinstall or restore this module on the local computer.

Possibly, you are right that something has to be reinstalled. But what? :)

**Comment by robertohuertasm** [comment]
@madrus Have you executed the "Icons Update" command? You can try to open the Developer Tools in your VSCode and look for some messages in the console while executing this command.

**Comment by pplawucki** [comment]
@robertohuertasm I've got the same problem as @madrus
Could be that request for icons.zip from github is not going through proxy configured at VS Code?

**Comment by pplawucki** [comment]
@robertohuertasm @madrus I've managed to solve the problem by properly setting environment variables HTTP_PROXY and HTTPS_PROXY. Once set, these are used by request library for making http(s) calls.

**Comment by madrus** [comment]
@robertohuertasm Here is the printscreen of the errors in Development Tools. The IP address 192.30.253.112 is that of GitHub it seems. I will do another check check dubble check on my HTTP(S)_PROXY variables.
![github_error](https://cloud.githubusercontent.com/assets/7058116/16865949/da7b4f6a-4a68-11e6-8658-bc538a7db073.png)

**Comment by madrus** [comment]
Here are my proxy settings in VSCode User Settings:
```json
// The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
"http.proxy": "http://localhost:53128",
"https.proxy": "http://localhost:53128",
// Whether the proxy server certificate should be verified against the list of supplied CAs.
"http.proxyStrictSSL": false,
```
As I mentioned earlier, my CNTLM proxy listens at port 53128. 
However, the more I look into it, the more I have a feeling this has nothing to do with the ICONS addon of @robertohuertasm.

**Comment by madrus** [comment]
Ok. SOLVED!!! Thanks to the tip of @pplawucki. While dubble checking, I have found out that I had no http_proxy nor https_proxy variables configured among the Windows environment variables. I have added them, restarted VSCode and bum! The icons work. Guys all of you 1000 thanks. You saved my day and weekend. :)

**Comment by robertohuertasm** [comment]
@madrus I'm glad you solved it! Thanks also to @pplawucki! I will refer this thread in the readme in case some else is having issues with their proxy.

**Comment by TonySpegel** [comment]
Issue remains in latest VSCode (1.6.0) and vscode-icons 3.0.4 - Ubuntu 16.04 LTS and I also get this when using icons enable "command is no longer supported for VSCode >= v1.6.0"

**Comment by robertohuertasm** [comment]
@TonySpegel see the readme, #368 and #369. Icons Enable is no longer supported with vscode >= 1.6.0

**Comment by JonasAmerico** [comment]
Go to FILE, PREFERENCES, CLICK ON "FILE ICON THEME", and then click VSCode Icons.

**Comment by nikitahl** [comment]
@JonasAmerico thanks, that worked for me!

**Comment by MRashed** [comment]
@JonasAmerico Thanks, that's working with current version I have (1.9.1)

**Comment by mustafa2080** [comment]
![Capture](https://user-images.githubusercontent.com/39808311/69534131-de1f1c00-0f81-11ea-86e2-857d1c45c4ea.JPG)
I want someone to help me to solve this problem.

**Comment by MalkeshDalia** [comment]
Try to install Dart Language support from the market. Flutter is dependent on Dart.
________________________________

**Comment by mustafa2080** [comment]
All extensions no appear icon

**Comment by KingDarBoja** [comment]
Locking conversation as this issue is pretty old. Please open a new issue if you have any issue regarding this extension.
