### ISSUE TITLE
Setting `hideCustomFolderIcons` to `true` has no effect.

### ISSUE THREAD

**Issue by jsynowiec** [robertohuertasm/vscode-icons#212]
**Checklist:**
- [x] I'm using Visual Studio Code Version [1.4.0] [Stable]
- [x] I'm using the extension version [1.8.2]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] My system is: OS X
- [x] I'm sure this issue is not a *duplicate*?
- [x] I've forced Icons Update.
- [x] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**
Setting `hideCustomFolderIcons` to `true` has no effect.

**Steps to reproduce:**
1. Update extension to 1.8.2
2. Add `"vscode. hideCustomFolderIcons": true` to vs code settings
3. Restart vscode

_Expected behaviour:_
All special folders have to basic folder icon.

_Actual behaviour:_
All special folders still have to custom icons.

As a workaround I'm using `useFileAssociations` and `associations` to hide custom icons for all special folders like src, test, node_modules, etc.

**Comment by robertohuertasm** [comment]
Sorry but this setting won't work for the moment until 1.8.2 will be released tomorrow. You have to use the associations workaround as stated in the readme as an alternative solution. I'm sorry for the inconveniences.
