### ISSUE TITLE
support for (git) ignored and search excluded fade style

### ISSUE THREAD

**Issue by whitecolor** [robertohuertasm/vscode-icons#213]
I wonder if it is possible to style in some way icons for git ignored files, for example make them faded or desaturated. Also something like this would be use for files that are in `search.exclude ` option of `.vscode/settings.json`.

Also can extension potentially effect file name colors? Maybe this could be useful too.

**Comment by robertohuertasm** [comment]
@whitecolor thanks for the idea but it's somehow duplicate. See #100, #162 and #203. I'm going to close this issue and I suggest you to add this information to #203. :wink:
