### ISSUE TITLE
Icon request: Poedit

### ISSUE THREAD

**Issue by TiTnOuK** [robertohuertasm/vscode-icons#214]
**Poedit: Gettext Translations Editor** has no icon.
Website URL : [Link](https://poedit.net/)
Icon that can be used : [Link](https://poedit.net/images/main_ico.png)
File extension : **.po** / **.mo**

If you can add it 😃

**Comment by jens1o** [comment]
I'll do it.

**Comment by jens1o** [comment]
see #217
