### ISSUE TITLE
Icons are not shown properly in tree, but in Open Editors are OK

### ISSUE THREAD

**Issue by rbukovansky** [robertohuertasm/vscode-icons#218]
- [x] I'm using Visual Studio Code Version [1.5.0] [Insider]
- [x] I'm using the extension version [1.8.1]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] My system is: Win7/64, Ubuntu/MATE 16.04.01 LTS
- [x] I'm sure this issue is not a *duplicate*?

**Description:**
After today's update to newest VS Code Insiders and latest vscode-icons, I'm getting icons shown correctly for Open editors, but for Tree view I'm getting placeholders instead of file icons. 
Folder icons are just fine.

This is happening on both listed machines.

![vscode-icons](https://cloud.githubusercontent.com/assets/1004491/18043219/c3e2af88-6dc6-11e6-80a9-92d6845fc2ad.PNG)

**Steps to reproduce:**
1. Update VS Code Insiders
2. Update vscode-icons
3. Re-enable vscode-icons

_Expected behaviour:_
Correct file icons are shown in tree view.

_Actual behaviour:_
Placeholder/generic file icon is shown in tree view.

**Comment by whitecolor** [comment]
Yes the same.

**Comment by robertohuertasm** [comment]
@rbukovansky @whitecolor thanks for the heads up! It seems something change with the latest version. As I was going to roll out 1.8.2 today I'll try to fix it. Hopefully, Insiders breaks will tend to diminish once the new VSCode official icons API gets stable and our extension integrates with it.

**Comment by rbukovansky** [comment]
Sounds good to me... Thanks.

BTW It would be much easier if MS decided to integrate/merge your code to VS Code. That would save a lot of time for everybody...

**Comment by robertohuertasm** [comment]
Fixed in 6e7b1ca40b7946c61f101d26a6c977cf66724d98
I will release 1.8.2 in a minute

**Comment by robertohuertasm** [comment]
Already published, you should be able to download the new version now. Let me know if this is not still happening! :wink:

**Comment by rbukovansky** [comment]
Looks good! Thanks.

**Comment by whitecolor** [comment]
Heh, after long iteration cycle with update/enable/uninstall/... it finally worked, thanks)

**Comment by robertohuertasm** [comment]
@whitecolor good to now the fix is working! :grinning:

**Comment by whitecolor** [comment]
Oh it happened again after today update, and I'm not able to restore it yet with unstall/install/enable/disable.. (

**Comment by robertohuertasm** [comment]
If they've changed again their code that won't be fixed by executing the commands. I will take a look asap and let you know.

**Comment by whitecolor** [comment]
Ok, just after your yesterday fix it too didn't work at once, so have to do some actions.

**Comment by robertohuertasm** [comment]
@whitecolor 1.8.4 is out! It should be fixed by upgrading the extension.

**Comment by whitecolor** [comment]
@robertohuertasm :+1: thanks it works

**Comment by whitecolor** [comment]
@robertohuertasm though icons on files seems ok icons on folder doesn't appear, what can be the problem?

**Comment by robertohuertasm** [comment]
@whitecolor you mean custom folders?

**Comment by whitecolor** [comment]
node_modules, test, src, etc

**Comment by whitecolor** [comment]
@robertohuertasm btw is it possible to support custom icons folders in a particular project? say if icon pictures will be place some where nearby.

**Comment by robertohuertasm** [comment]
1.8.5 is out with a patch.
@whitecolor I'm not really sure to follow you but if you want to add custom folders with your own icons is not so easy. The only thing you could do is use a current icon, substitute it with another and then using associations change the normal behaviour.

**Comment by whitecolor** [comment]
@robertohuertasm it works, thanks ok I will create an issue for this.

**Comment by rbukovansky** [comment]
@robertohuertasm Installed the last VSCode Insiders:

Version 1.6.0-insider
Commit d81ee41c51cae93a5cac967e42a28660a3a7e005
Date 2016-09-23T05:58:22.484Z
Shell 1.3.5
Renderer 52.0.2743.82
Node 6.3.0

and we are broken again in Explorer window... 
![vscode-icons-broken](https://cloud.githubusercontent.com/assets/1004491/18778693/e3b42d60-8175-11e6-92db-2c389c915010.PNG)

Please take a look.

**Comment by whitecolor** [comment]
@rbukovansky do you use build-in icon themes?
