### ISSUE TITLE
Icon request: Composer

### ISSUE THREAD

**Issue by TiTnOuK** [robertohuertasm/vscode-icons#219]
**Composer: Dependency Manager for PHP** has no icon.
Website URL : [Link](https://getcomposer.org/)
Icon that can be used : [Link](https://getcomposer.org/img/logo-composer-transparent.png)
File : **composer.json** / **composer.lock** / **composer.phar**

(For the .phar extension, it can be a PHP icon because it's not unique to Composer)
Thank you 😺

**Comment by jens1o** [comment]
I'll do that.

**Comment by robertohuertasm** [comment]
@jens1o you're on fire man!
