### ISSUE TITLE
PHP Icon Very Small

### ISSUE THREAD

**Issue by TheColorRed** [robertohuertasm/vscode-icons#22]
Maybe it is just me, but the PHP icon looks much smaller than the rest. Could we increase it's size?

![screenshot from 2016-06-08 11 32 20](https://cloud.githubusercontent.com/assets/1571806/15902266/bac290ac-2d6c-11e6-881b-7db83e673cfc.png)

**Comment by robertohuertasm** [comment]
Hi @TheColorRed, it's not jus you. I have to say that I took the icons from Sublime Text editor so I guess they somehow decided that this was the correct size for php files... and honestly, I don't know really why. 😁 

I'll try to fix this and I'll let you know once it's done! 👍

**Comment by robertohuertasm** [comment]
I've uploaded a new icons.zip file with a new php icon. You will have to update the extension. 😄
