### ISSUE TITLE
Makefiles with extensions

### ISSUE THREAD

**Issue by Gama11** [robertohuertasm/vscode-icons#229]
It seems to be fairly common practice to add file endings to make files, like `Makefile.win` for the windows version. See https://searchcode.com/?q=makefile.win&p=0&loc=0&loc2=10000

It's probably easy to `Makefile.win` specifically as a special case because it's common, but people also invent other extensions like [`.version_extra`] (https://github.com/HaxeFoundation/haxe/blob/development/Makefile.version_extra). I guess it's reasonable to not support those? I'm not sure what other ones besides `.win` are common, but I don't use makefiles too much.

What do you think?

**Comment by robertohuertasm** [comment]
Hi @Gama11, in my opinion this kind of scenarios are already covered with custom associations. If someone wants to associate Makefile.xxx to makefile icon he can do it by leveraging custom associations functionality, which uses regular expressions in order to match files.

For instance, see #181.

**Comment by Gama11** [comment]
Okay, good point - that's a great feature. :)

Do you still think it's a good idea to include common ones (such as `Makefile.win`)?

**Comment by robertohuertasm** [comment]
I don't really think is worth the effort. User custom config is more than enough. But if you feel that this is something that can add some value go on with it and I will accept the PR.

By the way, I'm going to publish a new version in a minute as there's been a change in VSCode insiders. Do you have something that you want to publish?

**Comment by Gama11** [comment]
Alright, fair enough.

Feel free to publish a new version, I'm gonna take a break from PRs for now. ;) Besides, you release frequently enough that it doesn't make a big difference if it's "only" available next version.

**Comment by robertohuertasm** [comment]
@Gama11 I'm publishing right now. I've to attend other businesses and I want to let this fix with Insiders version solved before I go. :wink:
