### ISSUE TITLE
Custom thumbnail icons for folder

### ISSUE THREAD

**Issue by whitecolor** [robertohuertasm/vscode-icons#235]
The case sometimes there is a monorepos with different kind of project inside (there are related technically ): for example: https://github.com/cyclejs/cyclejs/

There are folders that refer to different libs and tools and if it would be possible to "assign" each folder a picture in VSCode it would make a navigation though the project more efficient and pleasant. 
maybe each folder could contain its thumbnail icon file.

**Comment by robertohuertasm** [comment]
Next release of VSCode stable version is going to implement the first version of the icon extension API 
[@vscode/10804](https://github.com/Microsoft/vscode/issues/10804). This API is still in its early stages but the VSCode team is willing that this extension abandons the "hacky" ways and embrace the official API. In fact, they're even thinking of not allowing code injection by using checksums so... 

Even if this request was easy to accomplish -which is not at the moment- I think it would be wise to wait until the next release of VSCode before implementing new functionality.

That being said. I'll keep this suggestion opened just in case we can implement it in the coming months.

**Comment by robertohuertasm** [comment]
Closing this. See #328. I would suggest to create an issue with a feature request in vscode's repo.
