### ISSUE TITLE
Icon request: PHP Unit

### ISSUE THREAD

**Issue by TiTnOuK** [robertohuertasm/vscode-icons#236]
**PHPUnit – The PHP Testing Framework** has no icon.
Website URL : [Link](https://phpunit.de/)
Icon that can be used : [Link](http://blog.fclement.info/sites/default/files/2016-06/phpunit.png)
File : **phpunit.xml**

Thank you 😃

**Comment by jens1o** [comment]
I'll do it.

**Comment by jens1o** [comment]
Any other icon? I think it is not looking that good:

![image](https://cloud.githubusercontent.com/assets/11234139/18108172/6066df88-6f0b-11e6-941a-f8689dacc5e6.png)

**Comment by TiTnOuK** [comment]
I think you can use only this part of icon:
[Link](http://img4.hostingpics.net/pics/149944phpunitlogoalt.png)
