### ISSUE TITLE
Icon Update does not work properly

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#238]
**Checklist:**
- [X] I'm using Visual Studio Code Version 1.4.0 Stable
- [X] I'm using the extension version 1.8.5
- [X] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [X] My system is: Windows 10 Anniversary 64bit
- [X] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):

**Description:**

I want again to try out the vscode icons image lib based on microsoft's icon pack by julianpaulozzi, but it does not work. What did I wrong?
please see https://youtu.be/3OsQA-i1uns

Icons Disable and Enable works, but when using Enable, the default icon pack is being used...

no errors in dev console and I am not behind any proxy

**Steps to reproduce:**
1. Change ```vscode.icons``` to ```https://github.com/julianpaulozzi/vscode-icons-image-lib/blob/master/icons.zip```
2. Execute Icons Update
3. Nothing changed.

_Expected behaviour:_
Updated icons

_Actual behaviour:_
Nothing happens.

**Comment by robertohuertasm** [comment]
I think the url is wrong. Try this:
```
"vsicons.icons": "https://github.com/julianpaulozzi/vscode-icons-image-lib/raw/master/icons.zip"
```

**Comment by jens1o** [comment]
ah, thanks. It works!, will create a pr to the owner ;)
