### ISSUE TITLE
Run VS Code with admin privileges so the changes can be applied

### ISSUE THREAD

**Issue by internetz** [robertohuertasm/vscode-icons#242]
After Install this message pops up:
Run VS Code with admin privileges so the changes can be applied.

Developer Console shows following error:
```
Uncaught Exception:  Error: EACCES: permission denied, open '/usr/share/code/resources/app/out/vs/workbench/browser/parts/editor/media/icons.zip
```

- I'm using Visual Studio Code Version 1.4.0 stable
- I'm using the extension version 1.8.5
- My system is: KDE Neon (Ubuntu 16.04)

**Comment by robertohuertasm** [comment]
Have you read the readme regarding linux and administrator privileges?

**Comment by robertohuertasm** [comment]
@internetz can you give us some more information? What have you tried?

**Comment by internetz** [comment]
I just scanned the Readme and searched for the message that popped up after install. But I did not find anything. But you are right. The Linux user section in the Readme helped me out. Maybe you can add the message 'Run VS Code with admin privileges so the changes can be applied.' to the Linux user section in the Readme to make it easier to search/find (for retards like me).

**Comment by robertohuertasm** [comment]
@internetz I'm glad you make it. You're right, I take for granted that it's clear but it's clearly not clear at all :wink: I'll make a direct reference in the readme as per your suggestion. :wink:
