### ISSUE TITLE
Icon Request: RAML

### ISSUE THREAD

**Issue by Maples7** [robertohuertasm/vscode-icons#243]
Website URL: http://raml.org/
File Extension: .raml
Logo: http://raml.org/sites/default/files/ramllogo.png

A RESTful API Modeling Language.

**Comment by jens1o** [comment]
The raml logo has a width, that I could not resize. Can we just use the first letter? Is that okey with you?

**Comment by robertohuertasm** [comment]
@jens1o ok for me! :wink:

**Comment by Maples7** [comment]
@jens1o I'm ok, too. By the way, thank you both for this VSC extension :wink:
