### ISSUE TITLE
[icon request] docs folder

### ISSUE THREAD

**Issue by leaxoy** [robertohuertasm/vscode-icons#244]

**Comment by jens1o** [comment]
@leaxoy Please provide some more informations. Example icon, file extensions... You know. The template has any information that we need, so please fill it out.

**Comment by iRoachie** [comment]
@leaxoy what types of files are in a docs folder? Or what is it used for?

**Comment by jens1o** [comment]
@iRoachie typically markdown files, for example this: https://github.com/electron/electron/tree/master/docs

It describes the api.

**Comment by jens1o** [comment]
@iRoachie Can you create the icon? I'll would create a PR

**Comment by iRoachie** [comment]
@jens1o any inspiration?

**Comment by jens1o** [comment]
@iRoachie Something like this? https://www.apicasystem.com/wp-content/uploads/2015/08/API-icon.png

It's a little bit over the edge, because it describes the api, and the api coordinates the connection between the program and the plugin.

**Comment by robertohuertasm** [comment]
@jens1o I don't think this icon is very representative of a document folder. I would expect to see an icon related to a document (I'm thinking of what Windows does for the Documents folder).

**Comment by iRoachie** [comment]
How about a markdown themed folder?

**Comment by jens1o** [comment]
@robertohuertasm Good idea.

@iRoachie Also good, then we just have to use the folder template.
