### ISSUE TITLE
Icon Request: css.map

### ISSUE THREAD

**Issue by iRoachie** [robertohuertasm/vscode-icons#249]
- [x] I'm using Visual Studio Code Version [1.4.0] [Stable/Insider]
- [x] I'm using the extension version [1.8.5]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] My system is: [Mac OS Sierra]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Icon Name: [css.map]
      - Sample original Icon(32x32/png/transparent whenever possible): [url]
      - Extensions: only one, *.map.css

We can use the same map icon for the js.map. Just make it blue to match the css icon, and replace JS with CSS.

**Comment by jens1o** [comment]
Do you make the icon or should I?

**Comment by iRoachie** [comment]
@robertohuertasm  implemented the js.map one in #154 , so it would be easier for him to make since he should have the template.

**Comment by robertohuertasm** [comment]
@iRoachie @jens1o no problem, I'll do it!
