### ISSUE TITLE
Handlebars icon

### ISSUE THREAD

**Issue by listepo** [robertohuertasm/vscode-icons#25]
Hi @robertohuertasm, there are plans to add an icon for handlebars?

**Comment by robertohuertasm** [comment]
What would be the handlebars file extensions?

**Comment by robertohuertasm** [comment]
.hbs & .handlebars?

**Comment by listepo** [comment]
@robertohuertasm yes

**Comment by robertohuertasm** [comment]
Done! 👍

**Comment by listepo** [comment]
@robertohuertasm thanks 👍
