### ISSUE TITLE
Icon Request: Ansible and Terraform

### ISSUE THREAD

**Issue by TStraub-rms** [robertohuertasm/vscode-icons#258]
- [x] I'm using the extension version [1.8.7]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] My system is: Mac OS
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Icon Name: ansible
      - Sample original Icon(32x32/png/transparent whenever possible): ![ansible](https://cloud.githubusercontent.com/assets/19933791/18175595/e54974ce-703f-11e6-8f21-e38ce055aabc.png)
      - Extensions: .yml, yaml
- [x] I'm using Visual Studio Code Version [1.4.0] [Stable]
- [x] I want to create an icon request(if not, remove these lines below):
      - Icon Name: terraform
      - Sample original Icon(32x32/png/transparent whenever possible): ![terraform](https://cloud.githubusercontent.com/assets/19933791/18175596/e54a1db6-703f-11e6-8fa1-6156ec2a0530.png)
      - Extensions: .tf, .terra

**Comment by kevinraybooth** [comment]
Prob would want .yaml also.

**Comment by jens1o** [comment]
I don't have something to edit... Thanks @TStraub-rms

**Comment by jens1o** [comment]
Could you say all files possible with ansible, because the file extension is not that unique? @TStraub-rms

**Comment by TStraub-rms** [comment]
@jens1o Ansible only uses YAML files, so I am not sure how you would want to handle that. 
If the icon at least made its way into the repo we could then just add an extension association as a user preference.

**Comment by robertohuertasm** [comment]
Let's create the icon and associate it with the ansible extension and then use associations in order to load it. 

Note that this kind of usage won't be supported by the new API, and as per conversations with @ aeschli, I think there are no plans to support this specific scenario.

**Comment by TStraub-rms** [comment]
Fair enough. It would be nice to have an ability to load your own icons and
