### ISSUE TITLE
incorrect type .expected "array"

### ISSUE THREAD

**Issue by czmecho** [robertohuertasm/vscode-icons#266]
**Checklist:**
- [ ] I'm using Visual Studio Code Version [1.4] [Stable/]
- [ ] I'm using the extension version [1.8.9]
- [ ] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [ ] My system is: [win10] 
- [ ] I'm sure this issue is not a *duplicate*?
**Description:**
[short description of the bug, enhancement or feature request]
after I install the vscode-icons,the warning appear 
![](http://ww3.sinaimg.cn/large/7df5111fgw1f7gl5cuvvnj20ua0d8gnp.jpg)

**Comment by jens1o** [comment]
(added as enhancement, because this warning aren't that critical.

**Comment by robertohuertasm** [comment]
@czmecho can you provide a screenshot? I cannot reproduce it.

**Comment by robertohuertasm** [comment]
@czmecho have you changed your settings?

**Comment by czmecho** [comment]
@robertohuertasm  after  I reinstall it, the warnning appear.
and it appear in the system setting.json.

**Comment by robertohuertasm** [comment]
Do you have any custom setting?

**Comment by czmecho** [comment]
@robertohuertasm 
only this :
{
    "git.enabled": false,
    "http.proxy": "http://127.0.0.1:1080",
    "editor.fontSize": 18,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
}

**Comment by robertohuertasm** [comment]
Try changing the null value for []. If it works I will change the default value. The weird thing is that I don't get any warning at all...

**Comment by czmecho** [comment]
it works!
![](http://ww2.sinaimg.cn/large/7df5111fgw1f7ipbkyqwej20n80ntwgv.jpg)

**Comment by robertohuertasm** [comment]
Do you have some kind of Json validation extension installed?

**Comment by czmecho** [comment]
@robertohuertasm  no,and I have try to uninstall all the other plugins and it appear.

**Comment by robertohuertasm** [comment]
I will change the defaults anyway... but as I told you I cannot even reproduce it. I don't get any of these alerts even in Insiders build.

**Comment by czmecho** [comment]
@robertohuertasm It appear in the Insiders build portable too.
maybe it's beacuse I use the portable portable?or I use the Windows 10 for China.

**Comment by robertohuertasm** [comment]
@czmecho thanks for the feedback. I will look at it but I think that with just changing these defaults by our side it will be good. Next release will be soon. :grinning:
