### ISSUE TITLE
Icon Request : Nuget and NuSpec

### ISSUE THREAD

**Issue by eugeneniemand** [robertohuertasm/vscode-icons#270]
Icon Request : Nuget and NuSpec 
Example: http://www.nuget.org/favicon.ico

**Comment by jens1o** [comment]
Please more information. use the template.

**Comment by dungdm93** [comment]
nuGet logo with better resolution: [https://commons.wikimedia.org/wiki/File:NuGet_project_logo.svg]

**Comment by jens1o** [comment]
I'm going to ask myself, but in general, it is your job to give us the information we need.

What extensions are being used for this 2 file types?

**Comment by iRoachie** [comment]
@jens1o  Any updates on this?

**Comment by jens1o** [comment]
@iRoachie No. Should I close this? But first, let me look. (Even when it is not my job...)

**Comment by jens1o** [comment]
Okey, looked forward...

It's ```nuget, nupkg, nospec, psmdcp```
