### ISSUE TITLE
Elixir Icon too dark

### ISSUE THREAD

**Issue by miguelc1221** [robertohuertasm/vscode-icons#271]
I feel like the current Elixir Icon is too dark, perhaps a lighter shade of purple would work better? Most themes have a dark background on the file tree and makes the current Elixir Icon harder to see. Maybe it's just me?

**Comment by jens1o** [comment]
No, it is not only you. I'd look, and yes, it is too dark.
![look here](https://cloud.githubusercontent.com/assets/11234139/18267739/d959fdca-7420-11e6-866f-99da31e37e42.png)
In the tab view, it's even more bad.
