### ISSUE TITLE
Use docker icon for docker-compose.yml

### ISSUE THREAD

**Issue by klmcwhirter** [robertohuertasm/vscode-icons#273]
**Checklist:**
- I'm using Visual Studio Code Version [1.4.0] [Stable]
- I'm using the extension version [1.9.0]
- [X] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [MacOS X] [x86_64]
- [X] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):

**Description:**
Please use the Docker icon for files named docker-compose.yml.

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
And, please fill out the full template. Sample icon?

**Comment by jens1o** [comment]
he? GitHub Bug?

**Comment by robertohuertasm** [comment]
We already have the icon

**Comment by klmcwhirter** [comment]
Right you already are using the icon for Dockerfile. I would like to see it
appear for docker-compose.yml as well.

**Comment by klmcwhirter** [comment]
I found a workaround using your useFileAssociations config feature. You can probably close this unless others would like to see this association by default:
```javascript
["docker-compose.yml", "docker file"]
```

**Comment by robertohuertasm** [comment]
Really glad you make it work! Anyway, we'll add it as a default association :wink:

**Comment by sylv3r** [comment]
Hello guys,

I'm digging up this issue since the docker icon is still not the default one for docker-compose.yml
This is a quick fix an a much appreciated move in order to keep track properly of the docker related files by default

Thanks

**Comment by jens1o** [comment]
```
    { icon: 'docker', extensions: ['.dockerignore', 'docker-compose.yml', 'docker-cloud.yml'], filename: true, languages: [languages.dockerfile], format: FileFormat.svg },
    { icon: 'docker2', extensions: ['.dockerignore', 'docker-compose.yml', 'docker-cloud.yml'], filename: true, languages: [languages.dockerfile], format: FileFormat.svg, disabled: true }
```
Yes, you can disable the first one and enable the second(which is the official icon) with the customization feature.

**Comment by sylv3r** [comment]
Thanks @jens1o for this tip
