### ISSUE TITLE
Request example usage for file associations configuration

### ISSUE THREAD

**Issue by klmcwhirter** [robertohuertasm/vscode-icons#274]
**Checklist:**
- I'm using Visual Studio Code Version [1.4.0] [Stable]
- I'm using the extension version [1.9.0]
- [X] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Mac OS X] [x86_64]
- [X] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):

**Description:**

I used the useFileAssociation config option to work around [#273](https://github.com/robertohuertasm/vscode-icons/issues/273) and had quite a time trying to figure out how to setup the associations array.

What I ended up doing was reading the code in replacements.js and then using developer tools to see what actual CSS class you were setting for the Dockerfile icon. Once I duplicated that prefix (dockerfile) for docker-compose.yml in the associations array it worked.

If might be helpful to mention in the README.md that the CSS class prefix is the extensions attribute in the array at [https://github.com/robertohuertasm/vscode-icons/blob/master/src/build/supportedExtensions.js](https://github.com/robertohuertasm/vscode-icons/blob/master/src/build/supportedExtensions.js).

For whatever reason that was not obvious to me.

**Comment by jens1o** [comment]
https://github.com/robertohuertasm/vscode-icons#use-custom-file-associations-to-change-icons

It's already there. Is this what you're looking for?

**Comment by robertohuertasm** [comment]
Maybe @klmcwhirter is right and we should have to be more obvious. I think a simple note or remark stressing that you need to use extensions you want to mimic as a second element of the array will be more than enough.
