### ISSUE TITLE
No icons in main folder explorer in VSCode 1.5.0

### ISSUE THREAD

**Issue by xconverge** [robertohuertasm/vscode-icons#277]
- I'm using Visual Studio Code Version [1.5.0] [Stable] (just came out as NOT insiders)
- I'm using the extension version [1.9.0]
- [X ] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Win10] [x64]

**Description:**

I have tried Update and Enable, and multiple restarts.

I see the icon on the tabs, and in the Active Editors window, but not the general workspace folder explorer

**Comment by lbenie** [comment]
@xconverge 
it needs to implement the new api probably. I have the same issue

**Comment by xconverge** [comment]
@lbenie perhaps, but the "new api" is not new, it is what was previously the insider build

**Comment by unsafecode** [comment]
Please, support 1.5.0 API soon - right now my VS Code is ugly...

**Comment by FermJacob** [comment]
+1 Issue is happening for me

**Comment by lbenie** [comment]
@xconverge 
new [icon](https://code.visualstudio.com/updates#_workbench) feature uses a `theme` now

**Comment by devNaresh** [comment]
same here no icons with latest update

**Comment by xconverge** [comment]
@lbenie ah I see...so did they killed this extension by adding it native...

**Comment by sunflash** [comment]
VSCode 1.5 build-in theme is very ugly, and missing a lot icons, please add support soon :)

**Comment by lbenie** [comment]
turn this project into a theme extension por favor 😍 !

**Comment by robertohuertasm** [comment]
Hi everyone, it seems that vscode team has advanced the release date. They told me that it was to be happening on Sept 12th... 

I was preparing the new version with official icon support but this release was completely unexpected...

Anyway, I'll try to update the extension again and make it work with the latest version. I'll keep you posted!

Thank you very much for your support!

**Comment by robertohuertasm** [comment]
1.9.1 is out with full support for 1.5.0 stable version. I've also update the readme with a note on what is the expected future for this extension.

Thanks again for your support! :heart: :grinning:

**Comment by stbert34** [comment]
Works fine thanks :-)

**Comment by jens1o** [comment]
Thank you roberto! :smiley:

**Comment by fghpdf** [comment]
My linux can`t support icon,i just update my vscode and icon.
But vscode still ugly,help me,please.

**Comment by edvail** [comment]
yes, on ubuntu icons do not appear (code v1.5.1)

**Comment by Franky47** [comment]
Works fine on OS X, thanks a lot !

**Comment by fghpdf** [comment]
just wait the next version

**Comment by robertohuertasm** [comment]
Can you open a separate issue for Linux issue? I'll look into it asap.

**Comment by unsafecode** [comment]
Confirm tonight update (1.5.1.) broke icons again

**Comment by robertohuertasm** [comment]
@unsafecode see #278. Windows should be working ok. Just follow the usual process. Install latest 1.9.1 version and do `icons update`
