### ISSUE TITLE
Cannot remove extension completely

### ISSUE THREAD

**Issue by Pszek** [robertohuertasm/vscode-icons#279]
I'm using Visual Studio Code Version [1.5.1] [Stable]
I'm using the extension version [1.9.x]
My system is: [OS] [Win10]

After upgrade to VScode 1.5 I wanted to remove your extension. Unfortunately after removal icons are still visible despite builtin icons are visible too (see the screenshot below).

![image](https://cloud.githubusercontent.com/assets/10253750/18379841/d3e8db12-7674-11e6-9bcc-085ecb05a7a1.png)

Also tried to install it and remove again with admin priveleges, but to no avail.

BTW. Thank you for that great extension. It allowed me to use VScode comfortably. Now when icons are included I want to decrease my dependance on plugins.

**Comment by jens1o** [comment]
You need to execute the command ```Icons Disable``` first.

So, reinstall the extension and then execute the command, and then uninstall it. There you go. (or just leave it disabled)

**Comment by Pszek** [comment]
Thank you. That solved it.

**Comment by sbromberger** [comment]
> You need to execute the command Icons Disable before uninstalling. (which is in the faq)

Sorry, but where in the FAQ is it? As of now:

FAQs

**Tabs have disappeared.**

**I've updated to the latest version of the extension but I can't see any icon.**

**I've installed the extension but I can't see no icons.**

**I've updated my VSCode and now I can't see any icon.**

**I've tried everything but nothing seems to be working.**

**Why are you always updating so frequently?**

**Comment by robertohuertasm** [comment]
@sbromberger you're right. We'll include it soon, with the next release, including official support. Thanks for noting it.;)
