### ISSUE TITLE
Feature request: more icons

### ISSUE THREAD

**Issue by tylucaskelley** [robertohuertasm/vscode-icons#28]
Some suggestions (willing to help out via pull requests if needed):

1. .editorconfig: Use the EditorConfig logo or a yellow gear icon
2. .babelrc: Use the Babel logo or a yellow gear icon
3. .env: Pretty common for people to use an env file for API keys and such, perhaps good to add an icon for it
4. .eslintignore: use the same icon as the .eslintrc file
5. *.log: Log files should have an icon as well

**Comment by robertohuertasm** [comment]
Done. 1.1.4

**Comment by tylucaskelley** [comment]
sweet, thanks!!
