### ISSUE TITLE
Config setting to hide file-icons

### ISSUE THREAD

**Issue by opus131** [robertohuertasm/vscode-icons#280]
- I'm using Visual Studio Code Version [1.5.1] [Stable]
- I'm using the extension version [1.9.1]
- My system is: [Windows 10] [64bit]

**Description:**

I'd like to use the folder- and tab-icons from the extension, but the file-icons from the VS Code theme. Would it be possible to add a config setting to allow that scenario, smth like `"vsicons.hideFileIcons": true`

**Comment by robertohuertasm** [comment]
See #297 to see why this issue is being closed.
