### ISSUE TITLE
Icon request: Masterpage

### ISSUE THREAD

**Issue by mikiest** [robertohuertasm/vscode-icons#283]
- [x] I want to create an icon request:
      - Type: **extension**
      - Icon Name: **Master page**
      - Sample icon from Visual Studio:
![masterpage_32xlg](https://cloud.githubusercontent.com/assets/15056200/18388869/3c3c2806-769b-11e6-883c-3394feda1417.png)
      - Extensions: **.master**

**Comment by mikiest** [comment]
Has this been correctly merged?
.master files don't display any icons on my instance.

Using vscode-icons **v3.0.0** (did not show the icon on previous versions either) with the **VSCode Icons** icon theme and VS Code **1.5.3**.

**Comment by jens1o** [comment]
Hm? My pr looks correct. What did I do wrong?

**Comment by mikiest** [comment]
@jens1o Well first of all can you or anyone confirm they are experiencing the same issue? :)

**Comment by jens1o** [comment]
@mikiest Great idea, and my result is: yes, it's missing. The file is hidden.

Log:
```file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/workbench/browser/parts/editor/media/icons/file_type_masterpage@2x.png Failed to load resource: net::ERR_FILE_NOT_FOUND```

**Comment by jens1o** [comment]
GitHub bug. My commited file was not merged into the repo... I'll push it again.

**Comment by jens1o** [comment]
Should be working as soon as the new update is published.

**Comment by mikiest** [comment]
Thanks for this, working now :)
