### ISSUE TITLE
Icon request: cobol

### ISSUE THREAD

**Issue by chupi33** [robertohuertasm/vscode-icons#287]
Hello

is it possible to add the following icon ?

- I'm using Visual Studio Code Version [1.5.1] [Stable]
- I'm using the extension version [2.0.0]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: OSX Sierra
- [x] I'm sure this issue is not a *duplicate*?
- [X] I want to create an icon request(if not, remove these lines below):
      - Type: [extension]
      - Icon Name: [Cobol]
      - Sample original Icon(32x32/png/transparent whenever possible): [http://findicons.com/files/icons/2773/pictonic_free/32/prog_cobol.png]
      - Extensions: .cbl, .cob, .cpy

Thank you

![file_type_cobol 2x](https://cloud.githubusercontent.com/assets/4981101/18409743/d71f6086-774f-11e6-8190-7df404d6e223.png)

**Comment by chupi33** [comment]
Hello

Sorry but it seems to be ok for extensions .cbl & .cob not for .cpy

**Comment by robertohuertasm** [comment]
Solved with 2.0.3 release. I'll release it in 2 minutes.
