### ISSUE TITLE
Updating to latest version results in doubled icons, can't uninstall previous icons

### ISSUE THREAD

**Issue by keathmilligan** [robertohuertasm/vscode-icons#289]
VSCode 1.5.1. Just updated to the latest VSCode icons and got the message about the new API being supported. Enabling the VSCode Icons icon them results in two icons being shown for each file/folder.
![image](https://cloud.githubusercontent.com/assets/2936304/18411123/cf62b794-7736-11e6-9bbb-21dff549e4fd.png)

When VSCode icons is uninstalled and icon theme is set to None, VSCode icons still remain.
![image](https://cloud.githubusercontent.com/assets/2936304/18411152/76706374-7737-11e6-8a6e-37cea85cc0f6.png)

**Comment by keathmilligan** [comment]
OK, I think I've resolved this. After updating to 2.0.1, it is necessary to restart with admin privileges and run "Icons Disable" from the command palette. Then restart normally and enable the VSCode Icons icon them from preferences.

**Comment by robertohuertasm** [comment]
Hi @keathmilligan, glad you figure it out. It's explained in the readme but maybe it's not clear enough. 

With 2.0.1 you can choose which version do you want to use: the official one or the custom one, with tab icons and so on. If you choose the custom one then you'll need to disable any official icon theme that you may have enabled and star vscode with administration rights.
