### ISSUE TITLE
Duplicated icons

### ISSUE THREAD

**Issue by ashlouati** [robertohuertasm/vscode-icons#292]
**issue regarding the icons being duplicated**

when I choose from  File > Preferences > File icon Theme the option "None",
I get the icons once that seems to be permanent (I cannot remove them)
and by choosing an icon theme, well they become like this 
![issue](https://cloud.githubusercontent.com/assets/20360199/18416575/a8384660-7818-11e6-9667-8540a5f7f05a.png)

**Comment by jens1o** [comment]
Please execute the command ```Icons Disable```

**Comment by ashlouati** [comment]
thnx ! that solved the problem
