### ISSUE TITLE
Every time I open, it welcomes me to a new version

### ISSUE THREAD

**Issue by Meowbeast** [robertohuertasm/vscode-icons#293]
**Checklist:**
- I'm using Visual Studio Code Version [1.5.1] [Stable/Insider]
- I'm using the extension version [2.0.2]
- [X] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Win10] [x64]
- [X] I'm sure this issue is not a *duplicate*?

**Description:**

Every time I open code, your extention welcomes me to a new (the same) version.

**Comment by aluanhaddad** [comment]
I am experiencing the same issue.

On a side note, thanks for this terrific plugin.

**Comment by fegg** [comment]
哎，一个图标插件搞得好复杂。

**Comment by robertohuertasm** [comment]
Did you make a clean install or it was an update? The extension compares the version number with the one you had installed. If this is happening I guess something is wrong with the process of writing to your user settings folder. But this is weird, as vscode itself writes it's own settings into that same folder. If you did update the extension, try a clean install and let me know if that fixes it. I'll try to reproduce it anyway. :wink:

**Comment by Meowbeast** [comment]
I removed the extension and re-added.  
Same issue.

**Comment by czmecho** [comment]
![image](https://cloud.githubusercontent.com/assets/5077551/18426810/e4017a84-78f6-11e6-9a63-69cd4780471c.png)
everything I open the vscode, it show up to me.

**Comment by robertohuertasm** [comment]
Can you check the content of the file `vsicons.settings.json`? You will be able to find it by following this path: `C:\Users\<YourUserName>\AppData\Roaming\Code\User\vsicons.settings.json`

**Comment by robertohuertasm** [comment]
Ok guys, I think I found the bug. I'll be publishing a patch soon. :wink:

**Comment by robertohuertasm** [comment]
I've just released 2.0.3. Can you check if it's solved? You'll see again the message with the 2.0.3 for sure but hopefully never again until next version release.

**Comment by aluanhaddad** [comment]
2.0.3 fixed it for me. I'm using VS Code Insiders 1.6. Thanks for the quick turn around on this!

**Comment by Meowbeast** [comment]
Confirmed fixed.

Thanks!  It's been a rough OCD weekend... ;)
