### ISSUE TITLE
I can't use it on Mac after update it to 2.0.2. I've tried to use the command "Icons Enable"

### ISSUE THREAD

**Issue by EricWang1992** [robertohuertasm/vscode-icons#294]
I can't use it on Mac after update it to 2.0.2. I've tried to use the command "Icons Enable"

**Comment by robertohuertasm** [comment]
Can you be more specific? What did you do? Is it a clean install?  Did you updated the extension? Do you receive any message? Have you any error in dev console?

**Comment by schurig** [comment]
Same for me, running the latest version of `vscode-icons`. No errors in the dev console.

**Comment by robertohuertasm** [comment]
@EricWang1992 @schurig I would appreciate more details...

**Comment by enorfelt** [comment]
I too can't see any icons.
Running:
VS Code 1.5.2
vscode-icons 2.0.4

![image](https://cloud.githubusercontent.com/assets/8871328/18476219/77fdfd0c-79c9-11e6-9136-1f3aa4e1c55f.png)
![image](https://cloud.githubusercontent.com/assets/8871328/18476232/84bc0d04-79c9-11e6-946a-e71320c2d36b.png)

**Comment by robertohuertasm** [comment]
@enorfelt try `icons update`

**Comment by enorfelt** [comment]
@robertohuertasm thx! Worked!

**Comment by robertohuertasm** [comment]
@EricWang1992 @schurig can you try the same and tell me if it works for you?

**Comment by olingern** [comment]
@robertohuertasm I had the same problem and `icons update` worked for me. 

Thanks for the awesome extension!

**Comment by EricWang1992** [comment]
@robertohuertasm It's ok for me now. vscode-icons: 2.0.4 vscode: 1.5.2

**Comment by schurig** [comment]
Worked for me as well
