### ISSUE TITLE
[Question] [Suggestion] Enable icons only in tabs and "Open Explorer" Version 1.5.x

### ISSUE THREAD

**Issue by Tekbr** [robertohuertasm/vscode-icons#297]
- VSCode Version: 1.6.0-insider
- OS Version: Windows 10
- Version vscode-icons: 2.0.3

--Sorry for the English, I used Google Translator --

I have not seen any similar matter, if any, sorry.

Please change the title if necessary..

As the vscode-icons is supported the new api, is it not possible to use icons 'Enable - Update - Disabled' to when we are in version 1.5.x or higher to activate the icons only in tabs and "Open Explorer."

**Comment by jens1o** [comment]
I think it is not possible, due to our limited API functions with the Code API. But you can still use the old way. Remember to disable the icon functionality of Code. Then, you can execute ```Icons Enable```. There you go.

**Comment by robertohuertasm** [comment]
It should be possible when `hideFolders` and `Custom icon associations` work again. I'll let you know when it's fixed.

**Comment by robertohuertasm** [comment]
I've fixed the issues but now I've realized that if you use `custom icon associations` icons will be disabled everywhere, not only in the tree view. 

VSCode team is going to offer native support for tabs and "open editors" icons so I don't think is worth to implement this feature. Sorry :disappointed:  I hope you'll understand. :grinning:

**Comment by robertohuertasm** [comment]
Related to #280

**Comment by Tekbr** [comment]
> VSCode team is going to offer native support for tabs and "open editors" icons. 

That I did not.

Anyway thanks for the answer.

Oh, congratulations to all the great job.

**Comment by robertohuertasm** [comment]
@Tekbr thanks for your understanding. Maybe if the VSCode team takes too long implementing icon tabs and so on I will consider such an implementation. I've been told that probably in next release they will be delivering though, so it should be a month or so.
