### ISSUE TITLE
Hide Folder icons is not working

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#298]
hideFolders setting is not working anymore. It conflicts with the new API.

**Comment by jens1o** [comment]
It would be great, if microsoft says to you when they change the api. It is not funny...

**Comment by robertohuertasm** [comment]
@jens1o it's not Microsoft's fault. I didn't check it properly. :blush:

**Comment by wagerfield** [comment]
This still isn't working for me?

I am running the latest version of VS Code 1.6.0 and have the latest version of vscode-icons (3.0.3)

I have set the following flags set in my user settings:
```
{
  "vsicons.hideFolders": true,
  "vsicons.hideCustomFolderIcons": true
}
```

...but I am still seeing the folder icons in the file explorer:

![screen shot 2016-10-11 at 15 45 41](https://cloud.githubusercontent.com/assets/412747/19274935/d94686e0-8fc9-11e6-9772-63d0ab7d088d.png)

**Comment by robertohuertasm** [comment]
@wagerfield starting from v.3.0.0 and VSCode 1.6.0, we have abandoned all the custom functionalities and we only rely on official VS support so all the configurations of the extension are gone and this can only be managed via vscode api. I'm not sure if they provide now with something similar. In any case I encourage you to open an issue in their repository asking for the feature. 😉
