### ISSUE TITLE
Feature request: smaller icons

### ISSUE THREAD

**Issue by jschwarty** [robertohuertasm/vscode-icons#30]
Some of the icons look a bit too big (typescript, c#, html). Would be cool if these were a little smaller in scale.

**Comment by robertohuertasm** [comment]
These icons that you're referring to were the default package from sublime. This is not a priority for me. I expect to provide custom icons functionality so anyone can use the ones they prefer but I'll keep this opened in case some designer takes the lead and prepares some cool icons for us :wink:

**Comment by robertohuertasm** [comment]
@jschwarty I'll close this issue in favour of #65 as they're similar
