### ISSUE TITLE
it's f..king crazy ,update everyday??

### ISSUE THREAD

**Issue by rockwxy** [robertohuertasm/vscode-icons#304]
_**Instruction Template**_

**THIS IS AN EXAMPLE TEMPLATE**

**Make sure the following boxes are checked out(and the vars replaced) *BEFORE* you're submitting this issue**

**Screenshots are more than welcome!**

**Please remove any unused content (including these instructions) before submitting your issue.**

**Thanks :smile:**

**Checklist:**
- I'm using Visual Studio Code Version [1.x.x] [Stable/Insider]
- I'm using the extension version [1.x.x]
- [ ] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [OS] [Arch]
- [ ] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):
      - Type: [extension/folder]
      - Icon Name: [name]
      - Sample original Icon(32x32/png/transparent whenever possible): [url]
      - Extensions: .just, .a, .bunch, .of, .extensions
      - [ ] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**

[short description of the bug, enhancement or feature request]

[**PLEASE INSERT THE ERROR(S) YOU CAN SEE IN DEV CONSOLE HERE**]

[_Where is the dev console? Launch code, click on "Help" in the menubar at the top, click on "Toggle Developer Tools", and click on that window on "Console"._]

**Steps to reproduce:**
1. First step
2. Second step
3. And you can count yourself, can't you?

_Expected behaviour:_

[these lines are only important if you're submitting an issue]

_Actual behaviour:_

[these lines are only important if you're submitting an issue]

**Comment by robertohuertasm** [comment]
read the readme. Don't press the update button if you don't want to update. There are bug fixes that can't wait.
