### ISSUE TITLE
Please add .csx (c# script) icon

### ISSUE THREAD

**Issue by garrardkitchen** [robertohuertasm/vscode-icons#307]
Can you please add icon for .csx extension.  This maps to .cs extension and is csharp script.  I use this mainly with Azure Functions.

Warmest regards,

Garrard.

**Comment by jens1o** [comment]
Can we use the classic C# icon?

**Comment by garrardkitchen** [comment]
Yes. Thanks.

**Comment by garrardkitchen** [comment]
Thank you!
