### ISSUE TITLE
Don't surrender!

### ISSUE THREAD

**Issue by danielo515** [robertohuertasm/vscode-icons#312]
This is not an actual issue.

I just read the new features coming in the new version of VStudio and I immediately thought in your extension.
Since the icons as a default feature is a nice thing to have, I find your extension to be much better. Maybe those users that want the vanilla version can live without features like custom icons or tab icons, but for people like me that live a bit more out of the box (have you ever heard about tiddlywki or `.tid` files?) your extension is a must have.

I just want to thank you for it and encourage you to not abandon it in favor of native implementation of VSCode.

Regards

**Comment by jens1o** [comment]
My words. Just a great extension.

**Comment by pumano** [comment]
**Small guide** how to turn on vscode using mac version in recent version of VS Code:

**Code > Preferences > File Icon Theme >** Choose **VSCode Icons** for applying plugin

**Comment by robertohuertasm** [comment]
Hi @danielo515, many thanks for your more than kind words :heart: :grin: 
Provided that next version of VSCode is going to provide some new goodness regarding icons I see no point on keeping all the hacks so v.3.0 will get rid of all them and go fully official. Please see #328 for more information.
