### ISSUE TITLE
Webpack Icon for webpack.config.babel.js

### ISSUE THREAD

**Issue by chadly** [robertohuertasm/vscode-icons#313]
I see that webpack support was just added in regard to #305, #310. However, it appears it is only adding the webpack icon for `webpack.config.js` explicitly. It would be nice if it would also add it for anything that begins with `webpack.config.*.js`.

For me, I use `webpack.config.babel.js` which tells webpack to load the config file with the babel-loader. It would be nice to get the webpack icon for that file, too.

**Comment by robertohuertasm** [comment]
Hi chadly, this can't be done with the official API at the moment but you can use our custom icon association functionality in order to make it work. [Take a look here](https://github.com/robertohuertasm/vscode-icons#use-custom-icon-associations-to-change-icons). It works with regular expressions so it should cover any scenario you may have. :grinning:

**Comment by chadly** [comment]
Thanks @robertohuertasm. I didn't realize this extension was that extensible! I'll try that.

Maybe since, using the babel loader is probably most common, it would make sense to also include the webpack icon for both `webpack.config.js` & `webpack.config.babel.js` only?

**Comment by robertohuertasm** [comment]
@aeschlii, is there any way in the new API to support this kind of scenario? Should we add a new language (webpack) in order for the users to associate these files with this language? What would be the way to go in order to cover this in an official way?

**Comment by robertohuertasm** [comment]
@chadly I'm thinking of supporting a few common webpack filenames for the moment, until we have a proper official way to cover the scenario. I will accept your suggestion of supporting `webpack.config.babel.js` and I will add to it `webpack.config.dev.js`, `webpack.config.staging.js` and `webpack.config.production.js`
