### ISSUE TITLE
Icon Request: Gemfile n' gemspec

### ISSUE THREAD

**Issue by dungdm93** [robertohuertasm/vscode-icons#314]
Current icons for `Gemfile` and `*.gemspec` look like this:
![rubygems](https://cloud.githubusercontent.com/assets/6848311/18561256/567a036a-7ba9-11e6-9e08-e99615790bbc.png)

As you see, `Gemfile` n' `*.gemspec` has no icon at all. However, `Gemfile.lock` has ruby file icon, even if it's not ruby file.

**Checklist:**
- Visual Studio Code version [1.5.1] [Stable]
- vscode-icons extension version [2.0.5]
- System: [Windows] [x64]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request
      - Type: [file]
      - Icon Name: [ruby-gem]
      - Sample original Icon: [https://rubygems.org/favicon.ico]
      - Extensions: `Gemfile`, `Gemfile.lock`, `*.gemspec`

**Comment by dungdm93** [comment]
`Gemfile` and `Gemfile.lock` are in Bundler spec [[reference](http://bundler.io/gemfile.html)]
So, please use this icon [http://ruby-korea.github.io/bundler-site/images/gembundler.png] for those file.
Sorry about that mistake.

**Comment by robertohuertasm** [comment]
I missed the bundler icon in the last PR.
