### ISSUE TITLE
Icon Request: RSpec

### ISSUE THREAD

**Issue by dungdm93** [robertohuertasm/vscode-icons#315]
- Visual Studio Code version [1.5.1] [Stable]
- vscode-icons extension version [2.0.5]
- System: [Windows] [x64]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request
      - Type: [file/folder]
      - Icon Name: [rspec]
      - Sample original Icon: [http://rspec.info/images/logo.png]
      - File `.rspec`, folder `spec`

**Comment by jens1o** [comment]
I'll create a PR with the file icon, but due I didn't have access to Photoshop anymore, I cannot do the folder icon, I'm looking for an program which can handle that file...

**Comment by robertohuertasm** [comment]
@jens1o no problem, I'll do it. I think [the Gimp](https://www.gimp.org/) can handle it.

**Comment by robertohuertasm** [comment]
@dungdm93, @jens1o, I'm thinking that the spec folder is not particular of this ruby framework and maybe we should consider using the rspec logo for it. I'd suggest to associate it with the normal tests folder icon. Is it ok for you?

**Comment by dungdm93** [comment]
@robertohuertasm Yeah, I see. It's OK if using normal tests folder, but it would be better if we can display icon by detected frameworks/libraries. :)

**Comment by jens1o** [comment]
@dungdm93 But we do not have rights to read files in a directory :sob:
