### ISSUE TITLE
Icon Request: Flow

### ISSUE THREAD

**Issue by pibone** [robertohuertasm/vscode-icons#318]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- I'm using Visual Studio Code Version [1.5.2] [Stable]
- I'm using the extension version [2.0.5]
- My system is: [Mac OS 10.11.5] [x64]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [file/folder]
      - Icon Name: [flow]
      - https://github.com/rtorr/vscode-flow/raw/master/flow-logo.png
      - File: .flowconfig ; Folder: flow ; Extension: .js.flow

**Comment by robertohuertasm** [comment]
Folder icon still pending

**Comment by jens1o** [comment]
Exactly, I'm still looking for a programm, which allows me open .psd files
