### ISSUE TITLE
Add css / styles folder icon

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#321]
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [folder]
      - Icon Name: [css-style]
      - Sample original Icon(32x32/png/transparent whenever possible): [url]
      - Extensions: css, styles

I'm not really sure of the icon. We'll have to think about it.

**Comment by jens1o** [comment]
Icon: a pen which writes are text?

**Comment by iRoachie** [comment]
This could go a long way lol, are you extending it for scss, sass, less, stylus?

**Comment by robertohuertasm** [comment]
@jens1o it seems ok to me. 
@iRoachie, I'm not sure how to proceed... maybe we should create a specific one for every kind of style with the original logo. Does it sounds reasonable to you?

**Comment by iRoachie** [comment]
@robertohuertasm Could probably go with the pattern similar to the .vscode folder. Like a coloured folder with the logo for the extension sitting in a corner

**Comment by robertohuertasm** [comment]
Yes, that's for granted. We're going to stick to our own style convention regarding folder icons. :wink: So you think is sensible to follow this approach with all the different style flavours, don't you?

**Comment by iRoachie** [comment]
Sounds good to me, I'd like to get some more feedback from community

**Comment by jens1o** [comment]
Sounds good to me, too.
