### ISSUE TITLE
Please add .toml

### ISSUE THREAD

**Issue by RSamal** [robertohuertasm/vscode-icons#324]
Please add .toml extension

**Comment by jens1o** [comment]
Please use the template.

**Comment by jens1o** [comment]
Hmm, it doesn't have an official icon. Any idea for this?

https://github.com/toml-lang/toml

**Comment by robertohuertasm** [comment]
I'm going to create a literal icon and close this issue.

**Comment by robertohuertasm** [comment]
A flamingo finally...
