### ISSUE TITLE
small readme fix for OSX users

### ISSUE THREAD

**Issue by joeblew99** [robertohuertasm/vscode-icons#326]
you have 👍 
File > Preferences > File Icon Theme > VSCode Icons

On OSX its:
Code > Preferences > File Icon Theme

--

Also i would add this at the very top of the readme. Let me explain:
I have been using your extension for about 1.5 months, but then a few days ago after an update i could not see the icons anymore. SO i looked at your readme, and only found it pretty deep ino the readme.

**Comment by jens1o** [comment]
Do you want to create a PR, or should I?

**Comment by robertohuertasm** [comment]
@jens1o go for it. 😉

**Comment by jens1o** [comment]
Is this ok? 5b4fa55319f171acf9027f4ea539753642f62fba

**Comment by robertohuertasm** [comment]
@jens1o :+1:

**Comment by jens1o** [comment]
then I closing
