### ISSUE TITLE
I can't get through our proxy server

### ISSUE THREAD

**Issue by bearslumber** [robertohuertasm/vscode-icons#329]
Hi 

I can't get through our proxy server. Any chance f making a .vsix available to download for local install?

All help is greatly appreciated.

Bearslumber

**Comment by robertohuertasm** [comment]
@bearslumber take a look [here](https://github.com/robertohuertasm/vscode-icons#custom-icons-support-and-offline-icons-support).

The .vsix is not an option as the zip containing the icons will always be downloaded. Download it manually from this repo and follow the link instructions.

**Comment by bearslumber** [comment]
Thank you
Much appreciated.
