### ISSUE TITLE
Icon for vscode tsconfig.json, tasks.json and settings.json

### ISSUE THREAD

**Issue by skolmer** [robertohuertasm/vscode-icons#33]
All vscode configs should have the vscode icon instead of default json icon.
`jsconfig.json` and `.vscode/launch.json` have the vscode icon but `tsconfig.json`, `.vscode\tasks.json` and `.vscode\settings.json` have the default json icon.

**Comment by mrmlnc** [comment]
IMHO, if the file has an extension `.json`, this is JSON file.

**Comment by skolmer** [comment]
In my opinion vscode icons for vscode specific configuration files are fine, but that wasn't my point. This issue is about consistency. At the moment launch.json and jsconfig.json have both vscode icons but other vscode specific configs have json icons. Those files have all the same file extension!

**Comment by mrmlnc** [comment]
@skolmer, It sounds logical. Perhaps, I agree.

**Comment by robertohuertasm** [comment]
I'm including tsconfig.json for the moment. settings.json and tasks.json are too generic to apply a vscode icon to them. As I cannot set the icon depending on the file's container folder I have no way to discern the correct use of the icon and, therefore, I've decided to keep the json icon for them.
