### ISSUE TITLE
Support VSC 1.5.3

### ISSUE THREAD

**Issue by vkammerer** [robertohuertasm/vscode-icons#330]
Hello,

thanks for the great package! I couldn't live without it :)

I just upgraded to version 1.5.3 and the icons have disappeared. It isn't the first time this happens, so I think that in the future I will wait a few days before accepting the prompt in VSC to upgrade...

Is there a way that this behaviour doesn't happen in the future, and that we can safely upgrade VSC without fearing the loss of our beloved icons?

**Comment by jens1o** [comment]
Exceute ```Icons Enable```

**Comment by vkammerer** [comment]
ok thanks for the reply!

**Comment by jens1o** [comment]
Does it work? Then, you can close this issue :wink:
