### ISSUE TITLE
Tab icons not showing

### ISSUE THREAD

**Issue by Spiralis** [robertohuertasm/vscode-icons#338]
- I'm using Visual Studio Code Version [1.5.3]
![image](https://cloud.githubusercontent.com/assets/64342/18805310/f3c7f0c6-8209-11e6-8649-28dcb3703c54.png)

- I'm using the extension version [2.0.5]
![image](https://cloud.githubusercontent.com/assets/64342/18805348/8a3c1cd4-820b-11e6-8945-640b9ce5228d.png)

- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Windows 10] [x64]
- [x] I'm sure this issue is not a *duplicate*?

**Description:**
The tab icons are not showing, despite my settings being correct, AFAICT.
![image](https://cloud.githubusercontent.com/assets/64342/18805336/f5727b70-820a-11e6-9453-8d7f1f777331.png)

**Errors in dev console:**

> shell.ts:428Cannot read property '_documents' of null: TypeError: Cannot read property '_documents' of null
>     at DefinitionMetadataDocumentProvider.onTextDocumentClosed (C:\Users\ronny.INTS\.vscode\extensions\ms-vscode.csharp-1.4.1\out\features\definitionMetadataDocumentProvider.js:10:13)
>     at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:13653)
>     at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:15829)
>     at t.$acceptModelRemoved (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:13349)
>     at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905)
>     at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449)
>     at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:31126)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)e.onUnexpectedError @ shell.ts:428
> 

**Steps to reproduce:**
1. Open VS Code
2. None of the files opened, or already open shows the tab icons.

_Expected behaviour:_
I would have expected the tab icons to show.

_Actual behaviour:_
Not showing tab icons.

**Comment by jens1o** [comment]
What are the extensions you'd installed? Looks like there is an error from a C#-providing extension. That could return in not loading our extension properly.

**Comment by robertohuertasm** [comment]
@Spiralis have you tried executing the `icons update` command? Are you using the official API or the custom functionality? Have you ever executed the `icons enable` command?

**Comment by Spiralis** [comment]
Ah. That's it. I thought this was part of the latest VS Code included icon support. I just installed it and selected it in the File|Preferences|File Icon Theme menu. 
When I ràn `icon update` they appeared double up actually. When I choose "None" in that list, the VS Code Icons appear as expected (including ison in tabs). 
Not sure which way this is supposed to work though. Should I not use that system for this extension?

**Comment by jens1o** [comment]
> Not sure which way this is supposed to work though.
Both are working, but when your ok with the normal theme in that list, then ran Icons Disable and click it on the list.

**Comment by robertohuertasm** [comment]
@Spiralis vscode official api still does not support icons in tabs. So if you want this functionality you will have to use the hacky way by executing `icons enable`. The good news is that in VSCode v.1.6.0 icons for tabs are coming to the general public so you won't need to run the hacks and just do as you first did.

**Comment by Spiralis** [comment]
Cool. Thanks. I very much like the icons in the tabs, so I am using the old style `icons enable` "hack".
