### ISSUE TITLE
TypeScript icon

### ISSUE THREAD

**Issue by dungdm93** [robertohuertasm/vscode-icons#339]
I (personal) fell current TypeScript icon is a little bit ugly.
![typescript](https://cloud.githubusercontent.com/assets/6848311/18805598/431ce406-823c-11e6-818b-306301173dfb.png)
I'd suggest to change it by an official one [http://www.typescriptlang.org/assets/images/icons/apple-touch-icon-180x180.png]
![TS](http://www.typescriptlang.org/assets/images/icons/apple-touch-icon-180x180.png)
And **svg version** if you need. [https://github.com/remojansen/logo.ts/blob/master/ts.svg]

**Comment by jens1o** [comment]
thanks, I'll do that today

// cc: #65

**Comment by robertohuertasm** [comment]
I've reduced the size of the former icons. I've also tested with the original logo but it's too much solid color for me so I'll stick to the former ones with reduced format.
