### ISSUE TITLE
Feature request: Typescript Definition Icon

### ISSUE THREAD

**Issue by skolmer** [robertohuertasm/vscode-icons#34]
It would be nice to have a separate icon for .d.ts files to visually differentiate typescript code from typescript type definitions. I propose this icon (other suggestions are welcome):
![file_type_typescript_def 2x](https://cloud.githubusercontent.com/assets/2427106/16178062/1777047e-363f-11e6-8381-4c0146c75e30.png)

**Comment by robertohuertasm** [comment]
There's no current support for double extensions. I'll have to implement this.

**Comment by robertohuertasm** [comment]
Done!

**Comment by skolmer** [comment]
Great, thanks! :+1:
