### ISSUE TITLE
JavaScript icons

### ISSUE THREAD

**Issue by dungdm93** [robertohuertasm/vscode-icons#354]
I found a community logo for JavaScript in [**here**](https://github.com/voodootikigod/logo.js)
![JavaScript logo](https://raw.githubusercontent.com/voodootikigod/logo.js/master/js.png)
Although not an official icon but it's very popular in JavaScript world. 
And i think it look nicer than current JS icon. So I'd suggest you to replace the old one in order to keep in line with HTML, CSS and TypeScript #339 icons.
![javascript](https://cloud.githubusercontent.com/assets/6848311/18898113/c0f44188-8559-11e6-8a46-67a35fd247f8.png)

**Comment by robertohuertasm** [comment]
Hi @dungdm93, the current icon is indeed an inverted version of that logo. I'm not willing to use huge blocks of solid colors as icons if possible. The same happened with the TypeScript logo. See #339
