### ISSUE TITLE
Icon request: SaltStack (.sls) state file(s) and Jinja templates

### ISSUE THREAD

**Issue by mmisztal1980** [robertohuertasm/vscode-icons#356]
Hi,

It would be pretty awesome if the icon set supported saltstack's .sls files (which are basically YAML files)
![saltstack_logo](https://worldvectorlogo.com/logos/saltstack.svg)
Additionally, Jinja templates would be a welcome addition as well 

Cheers!

**Comment by jens1o** [comment]
Sure, but do you have a icon for "jinja"?

**Comment by mmisztal1980** [comment]
I believe, that's the one:
![jinjaicon](http://jinja.pocoo.org/docs/dev/_static/jinja-small.png)

**Comment by profsmallpine** [comment]
The jinja extension should also support `.jinja2` files
