### ISSUE TITLE
Icon for .proto files (Google Protocol Buffer)

### ISSUE THREAD

**Issue by ivanz** [robertohuertasm/vscode-icons#365]
Would be nice to have an icon for [Google Protocol buffer](https://developers.google.com/protocol-buffers/) files which have the `.proto` extension

**Comment by jens1o** [comment]
is there any icon?

**Comment by ivanz** [comment]
That's a good question and after having a quick search around I can't find one.

**Comment by jens1o** [comment]
Do you have a idea how the icon can look like?

**Comment by MinnieTheMoocher** [comment]
+1, I also would love to have a *.proto icon


idea for icon:

Could be derived from JSON icon, but using a different color for the braces.

In my brain, this wakes the "struct" association in my brain, which protobuf is all about.
It is about declaring structs.

**Comment by robertohuertasm** [comment]
[Found this logo](https://www.google.es/imgres?imgurl=http%3A%2F%2Fimg.keenwon.com%2F2014%2F07%2F20140731191357_86129.png&imgrefurl=http%3A%2F%2Fkeenwon.com%2F1304.html&docid=41c_3GT0F9euqM&tbnid=ueclCkNIpll4_M%3A&w=500&h=79&client=firefox-b-ab&bih=981&biw=1781&ved=0ahUKEwjRvNzeqtXPAhWIOhoKHTQNA9EQMwgiKAQwBA&iact=mrc&uact=8)

**Comment by delaneyj** [comment]
Using vscode 1.10.2 on Windows with vsicons 7.5.1 and viewing either .proto || .proto3 i'm not seeing the icon. Can someone verify it works on there system?

**Comment by JimiC** [comment]
Install any of https://marketplace.visualstudio.com/search?term=protobuf&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by delaneyj** [comment]
Sorry, didn't realize that was a requirement, fixed!
