### ISSUE TITLE
Can you please add icons for Fortran files?

### ISSUE THREAD

**Issue by ceshuer** [robertohuertasm/vscode-icons#366]
This might not be a popular request, but if possible, can we have icons Fortran files, such as:
.f90
.f
.mod

Thanks for the extension!

**Comment by jens1o** [comment]
Icon URL?

**Comment by robertohuertasm** [comment]
http://xyne.archlinux.ca/img/arch_linux_programming_language_logos/arch-fortran_logo.png
It will be delivered in next release.

**Comment by galjos** [comment]
It gone again! Not working on the newest release!

**Comment by robertohuertasm** [comment]
It works indeed. You need to install any fortran extension. Try [this one](https://marketplace.visualstudio.com/items?itemName=fortran-lang.linter-gfortran).

![image](https://user-images.githubusercontent.com/696981/228051803-4a6f64bd-14ee-43b4-ad69-1277b653e8ca.png)
