### ISSUE TITLE
Info message showed at every start.

### ISSUE THREAD

**Issue by nandowalter** [robertohuertasm/vscode-icons#367]
**Description:**

After installing v3.0.1 on vscode v1.6.0, **everytime** I open a new instance of vscode, vscode-icons welcome message shows up (info message located up in the vscode window).

**Comment by mbausdorf** [comment]
Experiencing the same issue as @nandowalter. Non-critical, but a little annoying nonetheless.

**Comment by robertohuertasm** [comment]
Is this your first installation or it was an update?

**Comment by nandowalter** [comment]
Was an update. After, I tried an uninstall and a re-install, with the same
result.

**Comment by mbausdorf** [comment]
for me it occurs post-update to VS Code 1.6

**Comment by robertohuertasm** [comment]
@mbausdorf so you already had the extension installed, didn't you?

**Comment by mbausdorf** [comment]
Yes, sorry - the extension was already installed

**Comment by nandowalter** [comment]
The same for me, I had the extension already installed. The bug occurred
after upgrading the extension.

**Comment by robertohuertasm** [comment]
Can you both take a look at this file and let me know what you have there?
C:\Users\<your_username>\AppData\Roaming\Code - Insiders\User\vsicons.settings.json

**Comment by richardpap** [comment]
Same here, tried a full reinstall too.
Even the icons are gone, and when i try to enable them, i get the following message:
"Icons Enable command is no longer supported for VSCode >= v1.6.0."

**Comment by robertohuertasm** [comment]
Sorry, I gave you the path to the `Insiders version`, change `Code-Insiders` for `Code`

**Comment by mbausdorf** [comment]
{"version":"3.0.0","status":"enabled","welcomeShown":true}

**Comment by robertohuertasm** [comment]
@richardpap icon support is now provided via the official VSCode API so you will have to go to `File > Preferences > File Icon Theme > Select vscode-icons`

**Comment by richardpap** [comment]
Oh, awesome, thanks!

**Comment by robertohuertasm** [comment]
@mbausdorf execute `Icons Disable`

**Comment by mbausdorf** [comment]
"Icons already disabled"

**Comment by robertohuertasm** [comment]
@mbausdorf  Could you let me know the text (more or less) of the welcome message that you're seeing? Thanks, btw! 👍

**Comment by robertohuertasm** [comment]
Got it! I see the bug! Thanks for your help! I will try to release a fix asap!

**Comment by mbausdorf** [comment]
Sure thing, heres a "timeline" after opening VS code.

- Welcome to the new version of vscode-icons v.3.0.1 -> Close
- Icons Enable command is no longer supported for VSCode >= v1.6.0. -> Close

**Comment by robertohuertasm** [comment]
3.2.0 is out and should fix this! Let me know if it's working for you! 😉

**Comment by mbausdorf** [comment]
My vsicons.settings file still says 3.0.1 and after the update the message also said 3.0.1 but I dont see the message anymore when restarting Code. Thanks so much, great job!

**Comment by robertohuertasm** [comment]
Argh, I will amend this right now. I think people is already missing our usual release frequency so... 😆

**Comment by robertohuertasm** [comment]
3.0.3 knocking at your doors! thank you all!

**Comment by mbausdorf** [comment]
![image](https://cloud.githubusercontent.com/assets/5411964/19269229/c22ba676-8fb9-11e6-88f4-2befe46d8523.png)

Settings file value is also correct. Nice work! Thanks for the quick help, much appreciated!

**Comment by nandowalter** [comment]
Thank you @robertohuertasm , fast fix!!!!!
