### ISSUE TITLE
Icons are gone

### ISSUE THREAD

**Issue by viniciusld** [robertohuertasm/vscode-icons#368]
I'm using vs code v 1.6.0 and extension v 3.0.3

I updated my vs code today to this version and all the icons are gone.

I've been through this before and followed the instructions from this comment (https://github.com/robertohuertasm/vscode-icons/issues/281#issuecomment-245881786) and every thing worked fine, but now i cant use the Icons Update command.

- Already tried to reinstall the extension.

**Comment by Thavarajan** [comment]
just use the icons theme to enable it again

**Comment by robertohuertasm** [comment]
Hi @viniciusld, icons are now supported via the official API. Please read the readme for more info on this matter.

**Comment by viniciusld** [comment]
@robertohuertasm didn't know about that. Thank you!
