### ISSUE TITLE
user setting vsicons.hideCustomFolderIcons is without effect

### ISSUE THREAD

**Issue by MinnieTheMoocher** [robertohuertasm/vscode-icons#370]
- I'm using Visual Studio Code Version 1.6.0 Stable
- I'm using the extension version 3.0.3 of
    https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Windows 64bit]
- [x] I'm sure this issue is not a *duplicate*?

**Description:**

user setting vsicons.hideCustomFolderIcons is without effect, see screenshot

**Steps to reproduce:**
1. edit user settings and set user setting vsicons.hideCustomFolderIcons to false
2. restart VSCode
3. custom folder icons are still visible

_Expected behaviour:_

special folders like "src" or "test" have default folder icon instead of special one

_Actual behaviour:_

special folders like "src" or "test" still have a special icon

![folder_icons](https://cloud.githubusercontent.com/assets/3216359/19282215/a8bcfeb8-8fed-11e6-9f06-f685e2de20db.png)

**Comment by jens1o** [comment]
That's right. Since the new version, we full use the official API, which doesn't support options right now. Feel free to ask in Code's Repo for a setting.

**Comment by MinnieTheMoocher** [comment]
then why does this extension put that setting into VSCode's default options?

**Comment by robertohuertasm** [comment]
@MinnieTheMoocher these are legacy options that will be removed in the next release. Please see the [motivations to apply this change here](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#state-of-the-extension)

**Comment by robertohuertasm** [comment]
See #336
