### ISSUE TITLE
Enabling the VSCode Icons theme causes double icons to be displayed

### ISSUE THREAD

**Issue by mmisztal1980** [robertohuertasm/vscode-icons#373]
![image](https://cloud.githubusercontent.com/assets/1357057/19309718/ee7ddb9a-9086-11e6-8521-48a7127ed1a8.png)

Enabling the VSCode Icons theme causes double icons to be displayed.

**Comment by jens1o** [comment]
Execute ```Icons Disable```.

**Comment by robertohuertasm** [comment]
You have to disable the old icons prior before enabling the official API. Just execute `Icons Disable` as @jens1o  suggests.

**Comment by mmisztal1980** [comment]
Just diagnosed this. This happened when VSCode wasn't able to start as administrator due to company policy.

**Comment by robertohuertasm** [comment]
@mmisztal1980 have you been able to solve it?

**Comment by robertohuertasm** [comment]
Of course you'll need administrator privileges to run any of the old commands. The hard way to make it work again is to reinstall VSCode. You won't lose any of your settings/extensions so it's safe to do it.
