### ISSUE TITLE
Icon Request: Prolog

### ISSUE THREAD

**Issue by raztd** [robertohuertasm/vscode-icons#383]
SwiProlog has a nice logo https://en.wikipedia.org/wiki/File:Swipl.png

**Comment by robertohuertasm** [comment]
Extensions?

**Comment by raztd** [comment]
I use *.pl extension for files I will compile with swi-prolog

**Comment by jens1o** [comment]
Are they other possible extension?

**Comment by raztd** [comment]
Yes
> .pl, .pro, .P

https://en.wikipedia.org/wiki/Prolog

**Comment by jens1o** [comment]
Thank you! I'll integrate it.
