### ISSUE TITLE
In VS Code 1.6.0 I cannot enable the Icons

### ISSUE THREAD

**Issue by miparnisari** [robertohuertasm/vscode-icons#385]
I installed the extension in admin mode, restarted the app, tried to enable the icons by pressing F1 and "Icons Enable" and got this: **Icons Enable command is no longer supported for VS Code >= 1.6.0**. And obviously I don't see any icons.

![image](https://cloud.githubusercontent.com/assets/5374887/19350657/06e7d336-912f-11e6-8d2b-f7d92c73cb08.png)

**Comment by jens1o** [comment]
That's right. The extension does not support this hacky implementation. You need to activate it via the File Icon Theme.

**Comment by miparnisari** [comment]
Oh! Okay, thanks. I'm closing this now.

**Comment by mhenke** [comment]
I am new to VSCode. How do I active it via the File Icon Theme?

**Comment by jens1o** [comment]
At the top, there's a menu: 
![image](https://cloud.githubusercontent.com/assets/11234139/20441534/3137759e-adc5-11e6-97ab-d2187c9a6f27.png)

Then follow my path and click on it. Then select "VSCode Icons". There you go!
