### ISSUE TITLE
Icon Change: StyleLint

### ISSUE THREAD

**Issue by JonathanWolfe** [robertohuertasm/vscode-icons#386]
**Change Icon of StyleLint**

[StyleLint](http://stylelint.io) currently has a pure black icon which isn't visible on the default UI color scheme.

![2016-10-13 14_31_25-omneo-ui - visual studio code](https://cloud.githubusercontent.com/assets/1449779/19361741/cfecadde-9151-11e6-8434-7b53aa04f680.png)

I recommend swapping it to a white version.

Attached here is a white png at 32x32, but white on white is invisible:
--> ![stylelint](https://cloud.githubusercontent.com/assets/1449779/19362093/420b519e-9153-11e6-9b46-a32b87707a8a.png) <--

```xml
<svg width="40" height="39" viewBox="0 0 40 39">
  <g fill="#fff">
    <path d="M20.272 38.16c4.375-15.642 4.248-15.713 7.41-26.866l.76.44c.414.237.752.042.752-.434V5.98c.84-2.938 1.496-5.21 1.69-5.89h3.425L40 5.36l-3.738 3.23 2.827 3.057L20.46 38.16c-.09.15-.217.116-.188 0z"/>
    <path d="M22.307 4.444c.17 0 .306.093.306.21V7.38c0 .113-.137.206-.306.206h-4.6c-.17 0-.307-.093-.307-.208V4.652c0-.115.137-.21.306-.21h4.6zm5.68-3.018l-5.062 2.922c.058.09.094.193.094.305V7.38c0 .14-.058.268-.148.37l5.113 2.952c.348.202.634.037.634-.365V1.792c0-.403-.285-.567-.634-.366zM16.993 7.38V4.652c0-.112.036-.215.094-.304l-5.062-2.924c-.348-.2-.634-.036-.634.366v8.545c0 .402.288.567.637.365l5.112-2.952c-.09-.103-.145-.23-.145-.37z"/>
    <path d="M19.54 38.16h.188c-4.374-15.642-4.248-15.713-7.41-26.866l-.76.44c-.413.237-.752.042-.752-.434V5.98C9.966 3.043 9.31.77 9.116.09H5.692L0 5.36l3.737 3.23L.91 11.648 19.54 38.16z"/>
    <ellipse cx="19.861" cy="11.897" rx="1.382" ry="1.382"/>
    <ellipse cx="19.861" cy="20.112" rx="1.382" ry="1.382"/>
    <ellipse cx="19.861" cy="28.329" rx="1.382" ry="1.382"/>
  </g>
</svg>
```

**Comment by jens1o** [comment]
svg is great!

**Comment by jens1o** [comment]
@robertohuertasm Is there something good to know when dealing with svgs? Can I put them in the icons folder as usual?

**Comment by robertohuertasm** [comment]
Yes, you can put them there. The problem is that the build process is still not ready. I'll have to modify it in order to mark svg somehow.

There's still a huge refactoring pending in the project because there are some things that are not really used anymore but are still there for people who use VSCode < 1.6.0.

I was willing to introduce these modifications with the next VSCode release but maybe we can move forward.

**Comment by robertohuertasm** [comment]
Let's use the png for this release. We have 3 icons to support along this one. I will start the svg feature next.
