### ISSUE TITLE
webpack files icons error

### ISSUE THREAD

**Issue by saltykovdg** [robertohuertasm/vscode-icons#388]
![webpack icons](https://cloud.githubusercontent.com/assets/18646645/19407593/674529bc-92d9-11e6-9a90-21cf21f2ce88.jpg)

**Comment by jens1o** [comment]
Could you explain what you feel is wrong? Do yoou want another icon for the production config?

**Comment by robertohuertasm** [comment]
@jens1o what is wrong is that webpack.config.prod.js should have the same icon as dev.js

**Comment by jens1o** [comment]
Ah.. I'll do it. @robertohuertasm

**Comment by saltykovdg** [comment]
thanks
