### ISSUE TITLE
Modify the build functionality to accept light icons

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#392]
Now the project doesn't take care of light themes. I think it would be easy enough to modify the build process in order to add specific icons for light themes.

**Comment by jens1o** [comment]
Hmm. nice comfort, but is it worth it?

**Comment by robertohuertasm** [comment]
I think so. There are some people complaining about that. And if we have the option I will accept PR gladly. Some icons will only require a color change or some border applied. Plus, the official api allows to publish specific icons just for light themes. It wouldn't affect the usual flow that we have now.

**Comment by jens1o** [comment]
Great! I'm agree with you!

**Comment by JimiC** [comment]
I believe we are a step closer into support this. Looking into this as well.
