### ISSUE TITLE
Icon Request: Idris

### ISSUE THREAD

**Issue by benedictleejh** [robertohuertasm/vscode-icons#398]
- I'm using Visual Studio Code Version [1.6.1] [Stable]
- I'm using the extension version [3.0.5]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Linux] [x64]
- [x] I'm sure this issue is not a _duplicate_?
- [x] I want to create an icon request(if not, remove these lines below):
  - Type: extension
  - Icon Name: Idris
  - Sample original Icon(32x32/png/transparent whenever possible):
    - https://github.com/idris-lang/Idris-dev/blob/master/logos/logo.svg
  - Extensions:
    - .idr
    - .lidr (literate Idris)
    - .ibc (compiled Idris files, similar to binaries, may not want to have an icon, included for completeness)
  - [x] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Comment by jens1o** [comment]
@robertohuertasm Should we wait for v4 or should we doing these now and convert it to png?

**Comment by robertohuertasm** [comment]
@jens1o convert it to png and we will recreate it later when v4 is done. Maybe this weekend I'll have the time to prepare v4.
