### ISSUE TITLE
Icon Request: test/spec JS

### ISSUE THREAD

**Issue by yevkbb** [robertohuertasm/vscode-icons#406]
- I'm using Visual Studio Code Version [1.6.1] [Stable]
- I'm using the extension version [3.0.6]
- [x] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [Windows] [x64]
- [x] I'm sure this issue is not a _duplicate_?
- [x] I want to create an icon request:
  - Type: extension
  - Icon Name: Test/Spec
  - Extensions: .test.js, .spec.js
  - [x] I crossed out "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**

I keep test files ending with .spec.js in the same folder as the source files; having an icon for test files, in addition to folders, would be very helpful.
I can't think of an icon to use for this, I trust you can come up with a good one.

**Comment by kristianmandrup** [comment]
YES, this is the latest fashion! We have the tools now to avoid having to partition our code by type. Much better to partition by domain and have all the files related to a particular domain in one place.
I follow the same convention `.test.js` or `.spec.js` and I know that 100s if not 1000s of js developers are shifting to use this convention. Please add support for this :) 
Thanks!

**Comment by kristianmandrup** [comment]
Or perhaps this is already possible? If so, please add documentation for how to achieve this - how to add custom mappings to icons using this plugin. Thanks :)

**Comment by kristianmandrup** [comment]
I made this PR: https://github.com/robertohuertasm/vscode-icons/pull/409

**Comment by kristianmandrup** [comment]
I hope to see these icons available by the end of this weekend :)
The PR is fine, just having problem placing the icons correctly, ie. centered vertically, one pixel down.
