### ISSUE TITLE
Please add tips on creating custom icons

### ISSUE THREAD

**Issue by kristianmandrup** [robertohuertasm/vscode-icons#408]
Include links to some icon editors/design tools

http://iconion.com/
http://www.xiconeditor.com/

Cheers!

**Comment by jens1o** [comment]
I disagree with you, because we're not creating any icons, but official language icons. So you do not have to use this, because you didn't actually must create the icon from scratch.

**Comment by JimiC** [comment]
In the light of converting all PNG icons to SVG, I think a doc with rules, hints and tips for creating or modifying an SVG image is appropriate.

**Comment by robertohuertasm** [comment]
Reopening this issue to remind us to write some sort of contribution guides regarding icon creation.

**Comment by JimiC** [comment]
I was about to create a new issue with a task for this. I suggest we keep this closed.

**Comment by robertohuertasm** [comment]
Ok then!

**Comment by jens1o** [comment]
#489
