### ISSUE TITLE
Icon request: Add Ionic icon for ionic.project

### ISSUE THREAD

**Issue by MatthiasDebaere** [robertohuertasm/vscode-icons#42]
Could you add an Ionic icon for the 'ionic.project'-file?

Ionic: http://ionicframework.com/

Thanks!

**Comment by robertohuertasm** [comment]
Done!

**Comment by fasfsfgs** [comment]
Is it possible to reopen this?
After ionic cli 2.0, the config file has changed from 'ionic.project' to 'ionic.config.json'.

**Comment by jens1o** [comment]
I'll create a PR fpr this

**Comment by jens1o** [comment]
see #211
