### ISSUE TITLE
[Task] Convert all PNG to SVG

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#421]
This is a proposal task.

If you approve of this, I can provide a PR with all icons converted to SVG.

**Sample**
PNG: ![file_type_coffeescript 2x](https://cloud.githubusercontent.com/assets/1716442/20037129/08befcf0-a423-11e6-85a1-bbb42b60ed75.png)
SVG: [file_type_coffeescript@2x.svg.zip](https://github.com/robertohuertasm/vscode-icons/files/573771/file_type_coffeescript.2x.svg.zip) (remove `.zip` extension, github doesn't support SVG upload)

This is related to #380

**Comment by robertohuertasm** [comment]
@JimiC I'll close this as a duplicate of #380. We can continue the discussion there. For me it's ok if you provide a first SVG version of all the icons. 😁

**Comment by JimiC** [comment]
Fine with me.
