### ISSUE TITLE
Just a small suggestion for the JavaScript icon.

### ISSUE THREAD

**Issue by Dignity-Code** [robertohuertasm/vscode-icons#43]
Hello,

first i want to say thank you , for all of your work to build this great extension.

So my suggestion is too add this JavaScript icon.  https://www.planet-source-code.com/vb/2010Redesign/images/LangugeHomePages/HTML5_CSS_JavaScript.png

I mean the HTML and CSS icon is the same, only the JavaScript icon is different to this in the picture.
That would be awesome !
As I said, it would be only a small suggestion :)

Thank you, have a nice day !

**Comment by robertohuertasm** [comment]
Thanks for your suggestion but I'm not changing the icon at the moment. These are the reasons behind my decision:
- The ["semi" official logo of JavaScript is black and yellow](http://www.2ality.com/2011/10/logo-js.html).
- I hope to deliver soon the option to use your own icons and use custom icon packages so you will be free to use the icon you most like. In fact, you can do it right now just replacing the icons in its folder. 😄 

Best regards and thanks again for your idea! 😉
