### ISSUE TITLE
Proposal: Overlay icons to visualise file changes etc

### ISSUE THREAD

**Issue by mandricore** [robertohuertasm/vscode-icons#433]
- [ x ] I'm sure this issue is not a *duplicate*?

Would it be possible to allow for file icon overlay, so we can visualise more than just the file type (extension). I was talking with a developer friend about preferred Editors and icons. 
He mentioned he really loves that Atom tree view indicates which files have changed (since last commit). In VSC, we have to switch to a whole different view to see this.

We could potentially also indicate other types of file metadata, such as perhaps what type of "thing" it is beyond the extension. Would be cool if there was a way to better distinguish common file types such as `models`, `views`, `services`, `tests`, ... Perhaps, given location in a specific folder, naming convention or even some file metadata? 

We might even be able to indicate which files have been (partly) covered by last test coverage run.
Just some ideas and food for thought. 

The main proposal is for icon overlay in general (I recall in Eclipse IDE they allowed sub icons for all 4 corners of main file icon) and in particular indicating files that have changed.

**Comment by robertohuertasm** [comment]
Hi @mandricore, 

it certainly would be a great idea but unfortunately this extension doesn't do code patching anymore and follows what's been established by the VSCode team. I suggest you to put this request into their repository because it's them who should have to provide this kind of functionality.

**Comment by jens1o** [comment]
I would agree, but the problem is, that I don't think this is possible through the API...

I'm too slow... Thanks @robertohuertasm
