### ISSUE TITLE
Disable notification on version update

### ISSUE THREAD

**Issue by peterjuras** [robertohuertasm/vscode-icons#435]
Hi!

I really like this extension, however I feel that the notification after a version update is not really necessary. Apart from the fact that notifications will stay there forever until they are dismissed, if every extension would do this, VSCode would become really cluttered. The only necessary notification was when the big update with the built in API occurred, since then however they haven't been helpful to me.

Do you think you could provide a user setting to disable these notifications on an upgrade?

**Comment by robertohuertasm** [comment]
Hi @peterjuras, fair enough. I think you're right. I will remove it in the next version.

**Comment by DanJ210** [comment]
@robertohuertasm I don't mind it. I like the link to a change-log.

**Comment by peterjuras** [comment]
As mentioned, maybe an option to disable it in the settings? This way users are informed until thry choose not to be :)

**Comment by DanJ210** [comment]
@peterjuras Yes like a don't show again unless it gets reset by being uninstalled then reinstalled.

**Comment by jens1o** [comment]
I'm interested in having a option too. For testing purposes, I want to know when the extension has been updated, when I should check something etc.
