### ISSUE TITLE
Never managed to get icons working :(

### ISSUE THREAD

**Issue by Sn3b** [robertohuertasm/vscode-icons#438]
Hi,

On both of my computers the icons never show, I feel I'm doing something wrong... :/

First computer is Windows 10, second is Windows 8. I have tried everything, uninstall/reinstall, install as admin, run as admin, Ctrl+P¨, Ctrl+Shift+P, F1 etc... But nothing...

Funny thing too, I've tried other icon packages, none of them work, also, when I hit F1 or Ctrl+Shift+P and start typing "Icons Enable" or "Enable Icons", nothing comes up, it just shows "No commands mathing" :(

The way I install the icons is by going to the extensions with the icon on the left, then type in "vscode-icons" which I do find and install without any problem, I then enable it still via the UI and hit "Reload".

Is there anything I can check?

Thanks!

Seb :)

**Comment by robertohuertasm** [comment]
Please, read the [readme here](https://github.com/robertohuertasm/vscode-icons#enable-the-extension)

**Comment by DanJ210** [comment]
@Sn3b I had the same silly thing. You select your icons to use just as you would select a color theme.

**Comment by Sn3b** [comment]
Ah right, I feel stupid now... Thanks guys! :)

**Comment by DanJ210** [comment]
@Sn3b Ha! You made me feel better because I did the same thing and made a post before figuring it out! So don't feel bad!! Maybe vscode icon devs can put a reminder for first installers and newbies that makes it easier to know what to do!

**Comment by Sn3b** [comment]
Yeah! Especially since you need to manually enable it and then restart, one would think it's enough ;)
