### ISSUE TITLE
Display icon based on files.associations

### ISSUE THREAD

**Issue by TheColorRed** [robertohuertasm/vscode-icons#44]
I have a file without an extension and one that has a php extension but is defined as an html file, and as you can see they display like so:

![screenshot from 2016-06-26 10-37-08](https://cloud.githubusercontent.com/assets/1571806/16363237/fb088196-3b89-11e6-900a-e14d7fed564b.png)

However, in my `files.associations` I have them defined like so:

![screenshot from 2016-06-26 10-34-41](https://cloud.githubusercontent.com/assets/1571806/16363224/a71c7560-3b89-11e6-96d2-5ed87763c848.png)

Is it possible to also display icons based on the `files.associations`, then fallback to the extension name?

**Comment by robertohuertasm** [comment]
It's really a good idea. I don't know if I'll have access to that file but I'll take a look at the documentation and see what can be accomplished. :grin:

**Comment by TheColorRed** [comment]
In our extension, we get file associations like this:

```js
var fileSettings = workspace.getConfiguration("files");
var obj: Object = fileSettings.get<Object>("associations", new Object());
```

**Comment by robertohuertasm** [comment]
@TheColorRed Thanks for the info. The issue here is that this must be used in the scope of a specific function which the plugin is replacing... I'll see what are the options that we have there. 😀

**Comment by robertohuertasm** [comment]
@TheColorRed Unfortunately this cannot be done dynamically as I would like it. Every time the files.associations are changed the user should update the plugin again and again. 

Nevertheless, even if not doing it dynamic this is not a trivial implementation and given my lack of time I can't promise you a quick delivery! :smiley:

**Comment by jens1o** [comment]
Would be great!

**Comment by robertohuertasm** [comment]
Done in 96de6ea0541fd88322c67ddcce092acab108b711

**Comment by robertohuertasm** [comment]
Already release in 1.5.0
