### ISSUE TITLE
Enable instruction not correct  (1.4.0 version)

### ISSUE THREAD

**Issue by mhenke** [robertohuertasm/vscode-icons#444]
I am trying to active the icons in VSCode but the menu option doesn't exist. How do I active the icons? I am new to vscode.

Thanks,

#140

== Enable the extension ==
Go to File > Preferences > File Icon Theme > VSCode Icons.
(Note on OSX it is Code > Preferences > File Icon Theme > VSCode Icons.)

**Comment by jens1o** [comment]
There's no support for version 1.4 anymore. Maybe @robertohuertasm has a old release supporting this version?

**Comment by mhenke** [comment]
Ok. I'll close this ticket

**Comment by jens1o** [comment]
Nono... Wait for a reply of the owner. 😃

**Comment by robertohuertasm** [comment]
@mhenke is there any specific reason for you to use 1.4.0 version? I would definitely upgrade to the latest version. If you want you can build the [3.0.8 version of the plugin with 1.4.0 support](https://github.com/robertohuertasm/vscode-icons/releases).

**Comment by mhenke** [comment]
My company hasn't upgraded yet. I put in a request to upgrade the vscode software package. Computers locked down too :-)

**Comment by robertohuertasm** [comment]
@mhenke I see... then you-ll have to build tag 3.0.8 using [vsce package](https://code.visualstudio.com/docs/tools/vscecli#_packaging-extensions), create a `.vsix` and open it with your visual studio code.
