### ISSUE TITLE
Remove `typings` folder (support of Typescript 2+)

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#445]
Switching to `vscode v1.0.0`, and supporting `Typescript v2`, the use of the `typings` folder is redundant.

https://www.npmjs.com/package/vscode

I have tested my suggestion under:
`Windows 10`
`Bash on Ubuntu on Windows`

Discuss?

**Comment by robertohuertasm** [comment]
No discussion about this. I've been playing with the idea of using TypeScript at some point and thought that the folder will be good to house some custom definitions that we may need but we could get rid of this for the moment.

**Comment by JimiC** [comment]
I'm fairly good at Typescript. I could help switch the entire project to it.
