### ISSUE TITLE
Icon request: Makefile

### ISSUE THREAD

**Issue by tylucaskelley** [robertohuertasm/vscode-icons#45]
Makefile should have an icon, perhaps just what Sublime has or alternatively just another gear icon since it's a config file of sorts

**Comment by robertohuertasm** [comment]
A gear for you! :smile:

**Comment by rok-star** [comment]
Please consider changing Makefile icon. The icon is out of entire icon-set style. + Icon is very detailed and looks messy in 16x16 size.

Peace 🌈

**Comment by KingDarBoja** [comment]
Please open a new issue in order to avoid commenting on old issues. Thanks!
