### ISSUE TITLE
Bug? Perl icon not displayed.

### ISSUE THREAD

**Issue by bayesrule** [robertohuertasm/vscode-icons#458]
Hi,

I'm using the latest vscode and vscode-icons. This issue has persisted for several versions. The current perl icon is displayed like this.

![perl](https://cloud.githubusercontent.com/assets/3372671/20612391/61e86138-b2f4-11e6-8c8e-e33fe6fbc8ac.png)

**Comment by JimiC** [comment]
What you are posting is the icon for [`Prolog`](https://github.com/robertohuertasm/vscode-icons/blob/master/icons/file_type_prolog%402x.png) [(with extension of `P`)](https://github.com/robertohuertasm/vscode-icons/blob/master/src/build/supportedExtensions.js#L130) and not `perl`.

**Comment by bayesrule** [comment]
@JimiC Thanks for replying. But .perl is really not commonly used for Perl script, and Perl is a more popular language nowadays than Prolog. Do we still have to categorize .pl as Prolog file instead of Perl file?

Besides that, it seems vscode identify .pl as a Perl file by default.

**Comment by JimiC** [comment]
Looks like we have a conflict here. The `.pl` file extension is used from both, `Prolog` and `Perl`.
I looked extensively at wiki's but couldn't get a clean view. 
In order to resolve this, I propose to make the following changes:
`Perl` => `.pl, .pm`
`Prolog` => `.pro, .P`

@robertohuertasm @jens1o Thoughts?

**Comment by jens1o** [comment]
Any neutral icon for the conflict extension(s)? When it's not possible, I think perl should be preferred to prolog.

**Comment by robertohuertasm** [comment]
I think we can use the language service for that. I'll take a look maybe this weekend. I tested it before we switched to "non-hacks" mode and it was not working ok. I'll give it a try again.

**Comment by robertohuertasm** [comment]
Finally `pl` extension has been removed from the `extension list` and now is supported by language id. If you associate your file to `perl` or `perl 6` then you will see the proper icon.

**Comment by jens1o** [comment]
Thank you Roberto!
