### ISSUE TITLE
Feature request: alternate html icon

### ISSUE THREAD

**Issue by smlombardi** [robertohuertasm/vscode-icons#468]
IMO, the HTML5 icon many packages use for html files is too "loud" compared to the other icons in the set.  For someone like me with mostly html files, it's a bit much IMO.

![screen shot 2016-11-29 at 4 20 37 pm](https://cloud.githubusercontent.com/assets/835148/20729424/e7f8e6b8-b64f-11e6-9d4d-80bd2a69b9b5.png)

so i frequent replace it with a simpler set of angle brackets:

![screen shot 2016-11-29 at 4 21 22 pm](https://cloud.githubusercontent.com/assets/835148/20729440/f61ac48c-b64f-11e6-8187-020a7f3ebab0.png)

Any thoughts of changing this, or providing a setting somewhere for an alternate?

**Comment by smlombardi** [comment]
FWIW, even changing the color as in "vscode-great-icons" helps

![screen shot 2016-11-29 at 4 33 40 pm](https://cloud.githubusercontent.com/assets/835148/20729836/b7bb61f4-b651-11e6-825e-9d3891876ce6.png)

**Comment by robertohuertasm** [comment]
As far as I know we cannot provide any sort of setting that could provide a change in the icons without doing some sort of code patching. We're now sticking to the official way of creating icon themes so this should be asked in the VSCode repo. I undestand that maybe you don't like this color but I'm not willing to change it at the moment. We try to stick to "official" icons where possible and most of the people seem to like it. 

I would be glad to provide some sort of mechanism so you could change it but, again, this feature should be provided by the creators of the theme API. 😞

**Comment by JimiC** [comment]
Unfortunately, there is so much we can do.

**Comment by robertohuertasm** [comment]
Just as a note. I'm studying a possible way to accomplish this and many other advanced features. I'll tell you something soon.
