### ISSUE TITLE
Icon Request: Ruby Gemfiles

### ISSUE THREAD

**Issue by BenJetson** [robertohuertasm/vscode-icons#47]
Ruby files already get a gem icon with your extension, but the Gemfiles associated with Ruby projects don't. Could you add support for Gemfiles? They should have the gem icon just like .rb files do:
![image](https://cloud.githubusercontent.com/assets/10427974/16466684/06654698-3e12-11e6-94d0-f472f5c65794.png)

Gemfiles are usually in the root directory of the project and are named exactly "Gemfile" (with no extension) and also "Gemfile.lock". Currently, they have this icon:
![image](https://cloud.githubusercontent.com/assets/10427974/16466782/6e1e9bf4-3e12-11e6-9941-5dde75acb9eb.png)

**Comment by robertohuertasm** [comment]
Done!

**Comment by BenJetson** [comment]
That was fast! Thanks! 😀

I'll be looking forward to seeing it in the next update.

On Wed, Jun 29, 2016, 5:36 PM Roberto Huertas <notifications@github.com>
wrote:

> Done!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/robertohuertasm/vscode-icons/issues/47#issuecomment-229496573>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ8eRuYXA60kw4OiTO2hNL9145PymgHSks5qQuVfgaJpZM4JBgt9>
> .
>
-- 

Ben Godfrey
benjetson5236@gmail.com
Sent from Inbox
