### ISSUE TITLE
.java and .class file showing same icon

### ISSUE THREAD

**Issue by sujinsr** [robertohuertasm/vscode-icons#470]
Hi,

Since .java and .class showing same icon, it is little confusing while opening the file. Please add the different icon for .class file.

would be great if the icon for .class file similar to link below
http://fileinfo.com/img/icons/files/128/class-737.png

**Comment by JimiC** [comment]
I think we should consider having diff icons for `.java`, `.class` and `.jar`.

**Comment by jens1o** [comment]
Do you have a idea for the color combos? I don't have any idea...

**Comment by JimiC** [comment]
In matter of fact, I do. Will provide samples, as I'll work on them on the weekend.

**Comment by JimiC** [comment]
So here is my proposal for the `Java` related files.

[jar](https://github.com/JimiC/vscode-icons/blob/PNG2SVG/icons/SVG/Samples/file_type_jar.svg)
[java](https://github.com/JimiC/vscode-icons/blob/PNG2SVG/icons/SVG/Samples/file_type_java.svg)
[class](https://github.com/JimiC/vscode-icons/blob/PNG2SVG/icons/SVG/Samples/file_type_class.svg)

**Comment by jens1o** [comment]
I'm fine with it.

**Comment by robertohuertasm** [comment]
I really like it 💯 👍 😁

**Comment by sujinsr** [comment]
Perfect.

**Comment by Daylien** [comment]
I agree just perfect.
