### ISSUE TITLE
Add .exp extension for tcl icon

### ISSUE THREAD

**Issue by garettmd** [robertohuertasm/vscode-icons#475]
- [x] I'm sure this issue is not a *duplicate*?

Can we add the `exp` extension to the to the tcl icon set? This is to account for [`expect`](https://en.wikipedia.org/wiki/Expect), an extension to the tcl language. This would require changing the `supportedExtensions.js` file's line as follows:

```
{ icon: 'tcl', extensions: ['tcl'] },
```

becomes

```
{ icon: 'tcl', extensions: ['tcl','exp'] },
```

And this would probably better suited to me just issuing a pull request, but I don't have any experiencing with building via npm, so I'm pretty sure I'd get it wrong.

**Comment by jens1o** [comment]
You don't *need* to build, it's optional 😃

**Comment by garettmd** [comment]
Oh, well if it's that easy I'll just fork and do a PR!
