### ISSUE TITLE
Use languageIds to provide generic icons for non-specifically-listed extensions

### ISSUE THREAD

**Issue by JonathanWolfe** [robertohuertasm/vscode-icons#476]
Instead of just listing all the extensions explicitly, we could list out `languageIds` so that, for example, all files associated with `json` get the generic `_f_node` icon unless a more specific icon is listed.

**Comment by robertohuertasm** [comment]
Hi @JonathanWolfe, this is on our list of todos. I first tried it when we did our conversion to the new API but there was some inconsistent functionality in the part of the API using the languageIds. I'll give it a try again and see what we can do.

**Comment by JimiC** [comment]
I'm also looking into this.

**Comment by JimiC** [comment]
Can we close this issue?

**Comment by JonathanWolfe** [comment]
I'll test it tomorrow when I get to work and close if it works!

**Comment by robertohuertasm** [comment]
@JonathanWolfe we haven't linked the `json` extension yet. That's why I left it opened, for us to review possible extensions that should benefit from language support.

**Comment by robertohuertasm** [comment]
Continues in #521
