### ISSUE TITLE
.spec.js files is displaying as normal .js files

### ISSUE THREAD

**Issue by VitorLuizC** [robertohuertasm/vscode-icons#477]
**.spec.js** files is displaying as normal **.js** files.

![Screenshot with the files test](https://cloud.githubusercontent.com/assets/9027363/20796992/19fc5886-b7c0-11e6-930b-9005a0042573.png)

Steps to reproduce:
- Just create a file ended with **.spec.js**.

**Comment by robertohuertasm** [comment]
I see you're using Insiders, isn't it? Could you try in stable version? Maybe the vsc team has changed something in the new version.

**Comment by robertohuertasm** [comment]
Can you tell us which specific version of vsc are you using?

**Comment by robertohuertasm** [comment]
It's working for me in Windows:
![image](https://cloud.githubusercontent.com/assets/696981/20798069/db222064-b7dd-11e6-89a5-85c56d49dedd.png)

**Comment by VitorLuizC** [comment]
![vscode - version](https://cloud.githubusercontent.com/assets/9027363/20799604/ce8b2b5c-b7c9-11e6-9fd0-bfd68f9d1e4f.png)

I think its something with this old Insiders version.

I've updated and it started to work again.

Thank you to pointing me that. :+1:
