### ISSUE TITLE
[Proposal] Add DevOps CI service

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#479]
It would be very helpful, if we could automate the ESLint and build check via a CI (Continuous Integration) service like [`Travis`](https://travis-ci.org/). It can help check the PR before merge.

**Comment by jens1o** [comment]
I don't think Travis is necessary, but I like the direction you're pointing to.

**Comment by robertohuertasm** [comment]
I agree with @jens1o in that this wouldn't add a lot of value to the project at the moment but I don't see any reason why not to do it. In fact, I think it will be useful in the future if we change the project to TS and TSLint. 
👍 to the idea.

**Comment by jens1o** [comment]
Will you set it up @robertohuertasm ?

**Comment by JimiC** [comment]
If it's no problem, I would like to test it first with my fork.

**Comment by jens1o** [comment]
Great idea.
