### ISSUE TITLE
Optimize specialExt algorithm

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#48]
Now, when dealing with special extensions the code is iterating over all the array of extensions even when we already know the specific special extension and its sub-extensions. Use an associative array to speed up the search.

**Comment by jens1o** [comment]
done in 6c5d038871a595eb68319acd0b970c4141eff249?

**Comment by robertohuertasm** [comment]
Not really, this was a bad commit... I'm working on this as the tabs feature #101  will imply a refactor of all this code. This is really going to be solved in #101

**Comment by robertohuertasm** [comment]
This is getting more generic. I will solve it after 1.6.0 is released.
