### ISSUE TITLE
Change Python icon to have the official colors

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#491]
At the moment, all the icon is blue. It would be nice to incorporate the yellow as the official version.

**Comment by JimiC** [comment]
@robertohuertasm Do I get to get a priority list? 😛

**Comment by robertohuertasm** [comment]
@JimiC, excuse my English... 😅 what do you mean?

**Comment by jens1o** [comment]
He wants a list what he needs to do first(the most important). Then a step down to the 2nd-importest. Did you understand me?

**Comment by JimiC** [comment]
@robertohuertasm It means that if you have a priority list for the icon conversion process, let me know.
Currently, my priority is to first support requested icons, then convert the folder icons, then the rest of the icons.

**Comment by robertohuertasm** [comment]
Ok! Thanks for the explanation! 😁 I currently don't have such a priority list but yours fits perfectly with the approach we've been keeping so far so I don't see a reason to change it.

That being said, would it be a problem for you (@JimiC) if someone did some icon modifications right now? I mean, I was thinking of doing this when I had a free moment but I'm starting to think that maybe it's a problem for you because you maybe loose tracking of the state of the icons. 

Please, let me know if this is an issue for you because then we we'll stop all the icon modifications until `svg conversion` is totally completed.

**Comment by JimiC** [comment]
@robertohuertasm Help is much appreciated, but the pitfall here is that we don't have "yet" a common art guideline, so that the converted icons are inline with that.
It would be a shame if we end up spending more time on agreeing than converting.

So my priority list has in `#2` the #489 issue, which I intent to work on in parallel.

**Comment by JimiC** [comment]
To add to the above, we could create a separate branch on this repo to keep the converted icons (as I do on my fork). It will be must easier to keep track on them than having them on my fork.
