### ISSUE TITLE
[Icon Request] Support Jest

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#496]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: extension
      - Icon Name: jest
      - Sample original Icon: ![Jest](http://seeklogo.com/images/J/jest-logo-F9901EBBF7-seeklogo.com.png)
      - Extensions: 'jest.config.json'

**Comment by jens1o** [comment]
as soon as you had published the steps to edit svgs in Inkscape, let me know ^^

**Comment by JimiC** [comment]
@jens1o I already have the logo in SVG. Will make a PR tomorrow.
