### ISSUE TITLE
Keep icons enabled

### ISSUE THREAD

**Issue by kuechlerm** [robertohuertasm/vscode-icons#50]
Love this extention!

Is it possible to keep the icons enabled? I have to enable them after every reboot.

**Comment by robertohuertasm** [comment]
Do you mean after every update? Or every normal reboot?  If you have to enable it on every fresh start there is something wrong.
Which os are you using? Extension version?

**Comment by robertohuertasm** [comment]
Try reinstalling vscode, too. You won't lose your extensions and it will refresh the original files. Take note of vscode version too :)

**Comment by kuechlerm** [comment]
Ok, sorry, my bad. I tried it in Insiders Version.
But it seems like I have to reenable after every update of VS Code - Insiders.
Is this normal? I run Win10.

**Comment by robertohuertasm** [comment]
Yes, it's completely normal. Insiders has almost a daily upgrade so... Every time it upgrades the modified files are deleted and I decided not to be invasive and modify them again automatically.

**Comment by kuechlerm** [comment]
Ok. Thanks.
