### ISSUE TITLE
[Question] What is the purpose of..

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#504]
I have noticed in the distributed folder two files that aren't present in the repo.

- `messages_de.js`
- `replacements.js`

What's their purpose?

**Comment by jens1o** [comment]
messages_de was planned for a translation of the extension to german.

replacements.js is the file shipped within the old integration, this file was the injected code in Visual Studio Code

**Comment by robertohuertasm** [comment]
Old code that somehow survived in my dist folder. It won't be present in next release.
