### ISSUE TITLE
[Question] Following Semantic Versioning

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#505]
From what I know about Semantic Versioning, I think that we aren't following it strictly.

Shouldn't the version number be bumped according to:

- Major number: When the API changes in a way that introduces breaking changes.
- Minor number: When new features are introduced.
- Patch number: When bugs get fixed or enhancements are made to the code base.

Don't get me wrong here @robertohuertasm, you are in charge and how you bump the version number is up to you. I'm just struggling with my O.C.D. 😄

**Comment by jens1o** [comment]
You're right.

**Comment by JimiC** [comment]
To specify what I mean with "new features", I believe that every time a new folder or file gets supported/added the minor number should get bumped.

**Comment by robertohuertasm** [comment]
@JimiC, you're right, I'm not following it strictly. Only for major versions until now. But I have no problem in adopting it so the community can be happier and your O.C.D stops haunting you 😉
