### ISSUE TITLE
[Proposal] Switch to official logo where applicable

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#508]
Would like to propose to adopt official logos when there is one.

**Comment by JimiC** [comment]
I'll start the debate with the following:
![screenshot - 11_12_2016 22_20_54](https://cloud.githubusercontent.com/assets/1716442/21083031/5e0842b4-bff0-11e6-89b4-e69387ec7fcb.png)

**Comment by robertohuertasm** [comment]
@JimiC, although this was already discussed in #339 and #354, I think that's maybe time to revisit it 😉

**Comment by JimiC** [comment]
Maybe switching to official logos will make this extension more popular than it already is (#3 in the chart). 😉

**Comment by jens1o** [comment]
#roadTo1MioDownloads 😉

**Comment by robertohuertasm** [comment]
I've tested the new icons and I will sheep them tomorrow. I've downloaded the official ones.

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/21083635/efecbfc6-bff4-11e6-9e05-4f2f17398d82.png)
