### ISSUE TITLE
Elixir icons

### ISSUE THREAD

**Issue by bigardone** [robertohuertasm/vscode-icons#51]
Hi! I've just installed your awesome package and I love it :metal: 
Would it be possible to have icons for Elixir files such as `*.ex`, `*.exs` and `*.eex`?
Thanks in advance 😄

**Comment by robertohuertasm** [comment]
Done! Enjoy :smile:

**Comment by miguelc1221** [comment]
I feel like the current Elixir Icon is too dark, perhaps a lighter shade of purple would work better? Most themes have a dark background on the file tree and makes the current Elixir Icon harder to see. Maybe it's just me?
