### ISSUE TITLE
Icon for new Swift Package Manager file - Package.pins

### ISSUE THREAD

**Issue by rbukovansky** [robertohuertasm/vscode-icons#513]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: SwiftPM Package.pins
      - Icon Name: SPMPins
      - Sample original Icon(32x32/svg/transparent whenever possible): Standard Swift icon
      - Extensions: .pins (but for just Package.pins file)

There is new file created by Swift Package Manager called Package.pins. Please add standard Swift icon for this file. Thanks.

**Comment by JimiC** [comment]
@rbukovansky Can you please provide docs about this new file extension? Thanks in advance.

**Comment by rbukovansky** [comment]
@JimiC Here you go...

https://github.com/apple/swift-evolution/blob/master/proposals/0145-package-manager-version-pinning.md

**Comment by JimiC** [comment]
OK. Looks like the proposal refers in using a filename called `Package.pins`. Unfortunately `.pins` can not be used as a file extension in this case.

**Comment by rbukovansky** [comment]
@JimiC Why? Can we get mapping just to "Package.pins" filename?

**Comment by JimiC** [comment]
`.pins` is used for other files. Don't worry we can map to the filename `Package.pins` to show the `Swift` icon. Something that needs to be noted is that on `MacOS` `package.pins` is different than `Package.pins`, so we'll need to know if the file name is going to be strictly used in `PascalCase`.

**Comment by rbukovansky** [comment]
OK.

**Comment by rbukovansky** [comment]
@JimiC @robertohuertasm Thanks for resolution of this! :+1:
