### ISSUE TITLE
Icon request: Add robot framework icon for .robot files

### ISSUE THREAD

**Issue by ScenK** [robertohuertasm/vscode-icons#52]
Could you help to add an robotframework icon for the '.robot' - file? 

Thanks!

**Comment by robertohuertasm** [comment]
Done!

**Comment by ScenK** [comment]
It seems that the implementation not works ?
![screen shot 2016-07-03 at 4 38 12 pm](https://cloud.githubusercontent.com/assets/2987542/16544522/b7797f80-413c-11e6-9d71-3a60ce3f22f5.png)
![screen shot 2016-07-03 at 4 38 29 pm](https://cloud.githubusercontent.com/assets/2987542/16544523/b8ef499e-413c-11e6-856e-3a143c7659a3.png)

**Comment by robertohuertasm** [comment]
My bad! Now it should be working!

**Comment by simons-orw** [comment]
I have vscode-icons v11.4.0 but there's no icon for .robot files.
![image](https://user-images.githubusercontent.com/24887331/113830746-d333e880-977e-11eb-81ac-ba8437319ccb.png)

**Comment by 4nif** [comment]
Same issue with me on v11.5.0 @robertohuertasm do you have any suggestion for this issue?

**Comment by robertohuertasm** [comment]
@simons-orw, @4nif you have to install a extesion supporting the `robot` language. Try [this one](https://marketplace.visualstudio.com/items?itemName=TomiTurtiainen.rf-intellisense), for instance. That will do the trick!
