### ISSUE TITLE
Karma icon

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#523]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: file
      - Icon Name: karma
      - [Sample original Icon ](https://gist.github.com/robertohuertasm/3c63d4851d8607199f54c3ede42ae9fe#file-karma-seeklogo-com-svg) 
      - Extensions: `karma.conf.js`

**Comment by JimiC** [comment]
Wanted to do this this weekend.
