### ISSUE TITLE
Protractor logo

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#524]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: extension
      - Icon Name: protractor
      - [Sample original Icon](https://raw.githubusercontent.com/ramonvictor/gulp-protractor-qa/master/assets/protractor-qa-logo.png) 
      - Extensions: `protractor.conf.js`

**Comment by JimiC** [comment]
Wanted to do this this weekend.
