### ISSUE TITLE
Can't activate icons (original: no se me activan los iconos)

### ISSUE THREAD

**Issue by hmuschett** [robertohuertasm/vscode-icons#529]
**Translated:** (by JimiC)
Hi
I have installed the extension (until it is activated) but I am not able to activate the icons on Win7 and I do not have the rights of admin in the machine I do not know if that has anything to do. I have done the steps to enable the extension but it does not come out in File Icon Theme> VSCode Icons.

**Original:**
hola 
tengo instalada la estencion(hasta se me actualiza) pero no se me acavan de activarr los iconos sus Win7 y no tengo los derechos de admin en la maquina no se si eso tendra que ver. he ralizado los pasos para avlitar la estencion pero no me sale en  File Icon Theme > VSCode Icons.

**Comment by jens1o** [comment]
I think he can help best, I can't understand spanish.

**Comment by JimiC** [comment]
I would really really appreciated if we could stick restrictively to English.

**Comment by robertohuertasm** [comment]
@hmuschett ¿Entiendes inglés? ¿Qué versión estás usando?

Translation: Do you speak English? Which version are you using?

**Comment by JimiC** [comment]
@robertohuertasm Did I do well with the translation? My Spanish are very basic (mostly what I've learned from TV :smile:)

**Comment by hmuschett** [comment]
@robertohuertasm gracias por responder s al parecer era que estaba utilizando una verision vieja(1.3) me descarge la 1.7 y me aparecio el menu y se activaron los icons mucha gracias a la comunidad

**Comment by robertohuertasm** [comment]
@JimiC your Spanish is quite good. If you ever come to Barcelona we'll have a change to practice it! 😉
