### ISSUE TITLE
Icon request: .swig extension

### ISSUE THREAD

**Issue by tylucaskelley** [robertohuertasm/vscode-icons#53]
Swig is a pretty popular HTML template language, here's the website: http://paularmstrong.github.io/swig/

**Comment by robertohuertasm** [comment]
@tylucaskelley What is the swig file extension? According to the examples in its site is html... and html is already assigned. No way to know what's the purpose of the file. 😞

**Comment by tylucaskelley** [comment]
Oh, it's `.swig`. It's HTML but has template features that let you do things like have if and for statements, etc.

**Comment by jens1o** [comment]
Looks like it is an fork of blade/smarty.

**Comment by jens1o** [comment]
Do you have an icon for this template engine?

**Comment by tylucaskelley** [comment]
Couldn't find one; maybe smarty or html icon would work

**Comment by jens1o** [comment]
I'll create an PR with the smarty icon.

**Comment by jens1o** [comment]
@robertohuertasm @tylucaskelley could someone close this?
