### ISSUE TITLE
Angular Icon Matching Is Too Broad

### ISSUE THREAD

**Issue by Tsmith18256** [robertohuertasm/vscode-icons#538]
The new Angular icons are nice, but the matching pattern is too hit and miss that I think there should be an option to disable these. I have a React Native project in which I end all my React Component files with _.component.js_, so they are being marked as Angular files.

Additionally, in my project at work, where we use Angular 1, the controllers are marked as _.controller.js_ and don't get the Angular icon. The Angular icons are a good idea, but it's confusing right now seeing them where they shouldn't be and missing where they should be.

**Comment by Tsmith18256** [comment]
I apologize if this is ignorant (I know pretty much nothing about the VSCode extension API), but is there any chance it would be possible to have a config where users could map their own regexes to different icons?

**Comment by JimiC** [comment]
See #514
