### ISSUE TITLE
[Icon Request] Support for .rake

### ISSUE THREAD

**Issue by namtab00** [robertohuertasm/vscode-icons#554]
- [x] I'm sure this issue is not a *duplicate*
- [x] I want to create an icon request
      - Type: rake file
      - Icon Name: ruby
      - Extensions: .rake

**Comment by JimiC** [comment]
From what I read `.rake` files are `Ruby` files but they contain task instructions. We already support `rakefile` associated with the `Ruby` icon, but I believe that this may cause confusion to the `Ruby` users.

How about we switch `rakefile` and `.rake` to
![rake](http://www.rubyrake.org/wp-content/uploads/2016/09/logo-ruby.png)

**Comment by JimiC** [comment]
This is going to be supported by `vscode` `ruby` language id. Still though I believe we should override the icon with the `rake` icon.
