### ISSUE TITLE
`HTML` icon broken/missing

### ISSUE THREAD

**Issue by JonathanWolfe** [robertohuertasm/vscode-icons#556]
After the latest update, `4.2.0`, the new svg version of the html icon doesn't appear and instead defaults to the fallback "white-paper" icon.

### Screenshot
![2016-12-19 10_34_54-pick-list-input html - omneo-ui - visual studio code](https://cloud.githubusercontent.com/assets/1449779/21318467/4306b846-c5d7-11e6-83bb-699155f43bbd.png)

### VS Code info
**Version:** 1.8.0
**Commit:** 38746938a4ab94f2f57d9e1309c51fd6fb37553d
**Date:** 2016-12-13T17:45:32.595Z
**Shell:** 1.4.6
**Renderer:** 53.0.2785.143
**Node:** 6.5.0
**Windows Version:** 7 Enterprise SP1

### DOM
```html
<div class="monaco-icon-label file-icon index-name-file-icon html-ext-file-icon polymer-lang-file-icon explorer-item" title="C:\Repos\omneo-ui\app\index.html">
    <a class="label-name">index.html</a>
    <span class="label-description empty"></span>
</div>
```

**Comment by jens1o** [comment]
But any icon but html will be displayed normally?

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/21318762/dc66520c-c60a-11e6-8be0-40263d2db12a.png)
I'm seeing it... can you try to reinstall the extension?

**Comment by jens1o** [comment]
It works too, in my enviroment.

**Comment by JonathanWolfe** [comment]
Uninstalling, then reinstalling the extension didn't produce any different results.

**Comment by robertohuertasm** [comment]
Which vscode version are you using?

**Comment by JonathanWolfe** [comment]
Just updated the issue with all that info, actually.

**Comment by robertohuertasm** [comment]
Go to `C:\Users\<youruser>\.vscode\extensions\robertohuertasm.vscode-icons-4.2.0` and remove it manually.

Then reinstall again the extension and let me know.

**Comment by JonathanWolfe** [comment]
No change.

**Comment by JonathanWolfe** [comment]
Ran all the icons through `svgo` and didn't get any changes either.

Also added an actual DOM node to the issue.

**Comment by JonathanWolfe** [comment]
Figured it out @robertohuertasm. The language ID is overriding the extension icon. Since I'm using JonathanWolfe/language-polymer and associate all HTML files to that type, it's trying to give it that icon (but there isn't one), and instead of falling back to the extension, it falls back to the default icon.

**Comment by jens1o** [comment]
Great!

**Comment by JonathanWolfe** [comment]
I'm guessing there's nothing this repo could do to fix it? Should I go open an issue on the vs-code repo?

**Comment by robertohuertasm** [comment]
This is a candidate on

**Comment by JonathanWolfe** [comment]
Sure, I'll add the icon after lunch.

**Comment by robertohuertasm** [comment]
If you can use svg that would be awesome!
