### ISSUE TITLE
[Icon Request] Support for reStructuredText

### ISSUE THREAD

**Issue by valerius257** [robertohuertasm/vscode-icons#561]
- [x] I'm sure this issue is not a *duplicate*
- [x] I want to create an icon request:
      - Type: reStructuredText file
      - Icon Name: reStructuredText
      - Extensions: .rst

**Comment by JimiC** [comment]
I have a PR ready for this but I need #563 to accepted first.

**Comment by jadchaar** [comment]
@JimiC any idea why the icon is not showing up for me? VSCode icons is for sure enabled:
<img width="140" alt="Screen Shot 2019-05-26 at 1 19 14 PM" src="https://user-images.githubusercontent.com/7388203/58385097-f608e980-7fb8-11e9-88f6-2b0010c3463e.png">

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/pull/2054#issuecomment-496012967

**Comment by jadchaar** [comment]
@JimiC even after deactivating and reactivating, nothing changed. I tried uninstalling the extension and reinstalling it (and adding back the file icon theme setting to settings.json), but that also did not work.

**Comment by JimiC** [comment]
You still need to activate it.

**Comment by jadchaar** [comment]
Yeah, I did that each time. I see all the other vscode-icons in my file explorer but for some reason the `rst` files just don't have an icon despite activation and all the other steps I have taken.

**Comment by JimiC** [comment]
Are you using an extension that supports `rst` syntax highlighting? Without it you won't see any icon.

**Comment by jadchaar** [comment]
Ah yes installing a tool for `rst` syntax highlighting added an icon. Anyway this can be circumvented/improved in the future @JimiC?

**Comment by JimiC** [comment]
This behavior is by design.
