### ISSUE TITLE
Support of Properties language id

### ISSUE THREAD

**Issue by JimiC** [robertohuertasm/vscode-icons#565]
- [x] I'm sure this issue is not a *duplicate*?

Looking at the [extension spec](https://github.com/Microsoft/vscode/blob/master/extensions/ini/package.json), if we are going to support this language id, I suspect it will create visual issues to what the user is currently familiar with.

Thoughts?

**Comment by JimiC** [comment]
Should we raise an issue with `vscode` to ask them to move the `git` related `filename` and `extensions` to [git](https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json) extension?

**Comment by jens1o** [comment]
@JimiC Yeah, we absolutly should ask them. It's their mission to resolve this failure.

**Comment by robertohuertasm** [comment]
I would also approve raising an issue with this.  I don't know why they took the decision to add these extensions to the `ini` language and not to the `git`.

**Comment by JimiC** [comment]
Finally found the time to raise the issue in `vscode` (https://github.com/Microsoft/vscode/issues/18358).

**Comment by JimiC** [comment]
Closing this as resolved by @robertohuertasm PR (https://github.com/Microsoft/vscode/pull/17865).
