### ISSUE TITLE
Assing icon to dot folders with specific names

### ISSUE THREAD

**Issue by whitecolor** [robertohuertasm/vscode-icons#581]
Often people name specific purpose folders using leading dot.

```
.scripts
.webpack
.tests
```
Just to make them be on top of the list, now only `scripts`, `webpack` etc without dot got icon.

**Comment by jens1o** [comment]
@robertohuertasm Is that currently possible with the api without defining hundreds of synonyms?

**Comment by JimiC** [comment]
@whitecolor `tests` folder also have icon.

**Comment by whitecolor** [comment]
@JimiC `.tests` doesn't

**Comment by JimiC** [comment]
@whitecolor I wrote `tests` not `.tests`.

**Comment by robertohuertasm** [comment]
@jens1o this could only be accomplished by using synonyms as you say. Let's wait for the new customization functionality and hopefully this will be feasible. I'm working on it but I don't find the proper amount of time to finish it yet. :grin:

**Comment by jens1o** [comment]
Seriously?
