### ISSUE TITLE
Missing associations for testts icon

### ISSUE THREAD

**Issue by cmccorvey** [robertohuertasm/vscode-icons#610]
While there is a supported file association for the testjs icon, there is no association for the corresponding Typescript flavored testts icon. I suggest the following be added to supportedExtensions.js:

     { icon: 'testts', extensions: ['test.ts', 'spec.ts'], format: FileFormat.svg },

**Comment by robertohuertasm** [comment]
This must be a bug. It was present until the latest release. Let me check it.

**Comment by cmccorvey** [comment]
Thanks!

**Comment by robertohuertasm** [comment]
It seems that somehow has been removed from the `supportedExtensions`. There will be a patch published in a few hours.

**Comment by JimiC** [comment]
Mw and conflict resolving to blame.

**Comment by robertohuertasm** [comment]
@JimiC no worries. You did a great work with the new icons! 😀
