### ISSUE TITLE
PHP Icon is a bit small

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#618]
**Checklist:**

- [X] I'm sure this issue is not a *duplicate*?

![image](https://cloud.githubusercontent.com/assets/11234139/21769620/e076b5aa-d67f-11e6-90ad-ec5ff4b53c40.png)

It's hard readable, I think the older icon would fit better, since it represents the php mascot and you don't have any letter on it you couldn't recognize.

**Comment by JimiC** [comment]
This is the official icon and the mascot is present as `php2`. You can change it at will now.

**Comment by jens1o** [comment]
@JimiC Thanks for the clarification. First, I also think this was added, but I wasn't able to found that settings. Thank you! Closing this...

**Comment by robertohuertasm** [comment]
We could leave the mascot as v2 so people can change easily, that would be great!

**Comment by JimiC** [comment]
@robertohuertasm I holding the PR until we decide what to do with the `json` icon.

**Comment by Oxicode** [comment]
change icon php please

**Comment by JimiC** [comment]
@Oxicode You can assign your own or use the provided alternatives (see how in [wiki section](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning)). We are using official icons where available and that's our official choice.
