### ISSUE TITLE
Installing custom icons not working?

### ISSUE THREAD

**Issue by jedmao** [robertohuertasm/vscode-icons#62]
I added the following to my user settings:

```json
{
"vsicons.icons": "https://github.com/jedmao/vscode-icons/blob/grayscale-icons/icons.zip?raw=true"
}
```
But it's not working, even when I start vscode as administrator, Ctrl+Shift+P run the "Icons Update" command and restart.

**Comment by jedmao** [comment]
It also doesn't work when I try:
```json
"vsicons.icons": "https://github.com/Yukaii/vscode-icons/blob/3e504348f54230ca302f5275ee248165a997e7e5/icons.zip?raw=true"
}
```

**Comment by jedmao** [comment]
FWIW, I'm on Windows 10.

**Comment by robertohuertasm** [comment]
@jedmao My bad, I didn't put the correct instructions in the readme. Now I've update it. The icons.zip must contain a folder named icons!! Then it will work perfectly. I've tested your package and it works if you modify this. Best regards! 👍

**Comment by jedmao** [comment]
Thanks @robertohuertasm. It works! I had to fix the icons to have transparent backgrounds, but it works!
