### ISSUE TITLE
Icon request: .elm

### ISSUE THREAD

**Issue by vaags** [robertohuertasm/vscode-icons#66]
Elm is a quite popular language for front end development (it compiles to javascript):

https://github.com/elm-lang
http://elm-lang.org/

Here is the official logo / icon:
https://sbrink.gallery.vsassets.io/_apis/public/gallery/publisher/sbrink/extension/elm/0.6.2/assetbyname/Microsoft.VisualStudio.Services.Icons.Default

**Comment by robertohuertasm** [comment]
Done!
