### ISSUE TITLE
.blade.php not displaying icon

### ISSUE THREAD

**Issue by rivendare** [robertohuertasm/vscode-icons#67]
Only displays the icon for a standard .php file.

**Comment by robertohuertasm** [comment]
You should see a Laravel Logo in 1.3.7.

**Comment by rivendare** [comment]
Perfect, working great now. Thanks!

**Comment by Klodovsky** [comment]
For anyone who might still face this issue, I found out that the icons/extensions wasnt working correctly because of invalid settings.json format , make sure your json format is correct.

You can check that by visiting https://jsonlint.com/
