### ISSUE TITLE
Icon Request: .todo

### ISSUE THREAD

**Issue by jens1o** [robertohuertasm/vscode-icons#69]
Just for todo Files. Would be useful to differentiate the different files between spaces and todo....

**Comment by robertohuertasm** [comment]
Sorry but I'm not sure to understand... spaces? is it another extension? Do you know where to find the logo?

**Comment by jens1o** [comment]
Spaces... Ahmm...

Sorry, I chosed the wrong words.

I mean a blank file without any extension.

A .todo is, in the current version, looking like a normal file.

**Comment by robertohuertasm** [comment]
Understood! 👍 Do you know of any todo logo?

**Comment by jens1o** [comment]
We could use the following Font Awesome icon:
http://fontawesome.io/icon/check/

**Comment by robertohuertasm** [comment]
I've found this. It's already transparent: http://images.clipartpanda.com/check-clipart-Check-box-icon.png 
Is it ok for you?

**Comment by jens1o** [comment]
Yep, that's also nice! When the update goes live?

**Comment by robertohuertasm** [comment]
now! 😄

**Comment by jens1o** [comment]
big thanks!

**Comment by robertohuertasm** [comment]
1.3.9 is already published!
