### ISSUE TITLE
Feature request: icons are very light for Light theme users

### ISSUE THREAD

**Issue by bansalvks** [robertohuertasm/vscode-icons#7]
The icons are extremely good for Dark theme users however for people like me who are on light side are facing trouble viewing them.

Please create 2 sets of icons 1 for light and 1 for dark themes that can be selected by executing commands.

Many thanks.

**Comment by robertohuertasm** [comment]
Designers of the world!! Some help would be really appreciated!

**Comment by jschwarty** [comment]
Would be nice to also have a set of non-color ones for each light and dark too and have an option to roll with the color or non-color icons.

**Comment by robertohuertasm** [comment]
You can now use your own custom icons by modifying your settings. Please, read the readme to learn how to do it. There's some people already preparing custom icon packages. #61 #65
