### ISSUE TITLE
Show icons on the new tab panel (VsCode 1.3+)

### ISSUE THREAD

**Issue by eladcandroid** [robertohuertasm/vscode-icons#70]

**Comment by sgtoj** [comment]
If this is added, especially if it is enabled by default, can you exposed an `setting.json` option to enable/disable it too?

**Comment by robertohuertasm** [comment]
I will have a look at it and see if it's feasible. Remember that vscode has not an open api regarding icons extensions so maybe is not possible to accomplish that.

**Comment by jens1o** [comment]
Would be nice, if there is any option. What we actually need? I would like to help. Currently, we use the background-image property, aren't we?
