### ISSUE TITLE
Not working at all on 1.3.0 or 1.4.0 (insiders) mac

### ISSUE THREAD

**Issue by smlombardi** [robertohuertasm/vscode-icons#71]
no icons appear.  i downloaded and enabled the extension.  is there more to it than that?

**Comment by smlombardi** [comment]
I see they also need to be enabled with the command.  Seems odd to not enable them by default, but it works now.

**Comment by robertohuertasm** [comment]
As the extension modifies some core vscode files I wanted the process to be a conscious choice of the user. If this weren't the case I've would have done it an automatic process.
