### ISSUE TITLE
CSS injection conflict detection?

### ISSUE THREAD

**Issue by be5invis** [robertohuertasm/vscode-icons#74]
Given that vscode-icons modifies `workbench.main.css`, which may conflict with other extensions that changes this file to implement custom CSS, is it possible to provide an option to add user’s custom CSS to the patch?

**Comment by robertohuertasm** [comment]
Could you elaborate this a little bit more? What would be the purpose of it?

**Comment by be5invis** [comment]
@robertohuertasm 

There are extensions modifies `workbench.main.css` either, like [vscode-background](https://github.com/shalldie/vscode-background). They may conflict with each other.

**Comment by robertohuertasm** [comment]
In the case of vscode-icons I only use a comment they have in the code and put some new stuff before it. I don't modify the existing code at all so I guess I won't be causing conflicts with other apps. Anyway, this would be impossible to control as this doesn't depend on something I can control. Everybody is free to do whatever they please so no matter what I do or say. What I've tried is to leave what it already existed exactly the same.
