### ISSUE TITLE
Admin privileges Mac

### ISSUE THREAD

**Issue by maxval94** [robertohuertasm/vscode-icons#78]
MacOS
Visual Studio Code 
Version 1.4.0-insider (1.4.0-insider)
http://joxi.ru/L21zZR6s6lY8MA

**Comment by robertohuertasm** [comment]
I've also noticed that too... 😞 I'll take a look at it asap.

**Comment by robertohuertasm** [comment]
Hi @maxval94, I'm going to close this and follow up in #79 as this seems to be a generic issue with the new Insiders release and it happens in OS and Linux, too.

**Comment by robertohuertasm** [comment]
@maxval94 I've recently pushed v.1.4.0 and it should be working now 👍

**Comment by maxval94** [comment]
Yes, it is work , Thanks
