### ISSUE TITLE
Insiders  & VSCode 1.3.1 version not working!

### ISSUE THREAD

**Issue by robertohuertasm** [robertohuertasm/vscode-icons#79]

**Comment by robertohuertasm** [comment]
Related #78 Duplicated

**Comment by robertohuertasm** [comment]
It seems to be related with the downloading of the icons.zip file. Somehow, it's failing because of the lack of privileges. I'll dig into it and let you know.

**Comment by robertohuertasm** [comment]
It seems that the problem has extended to 1.3.1 release

**Comment by robertohuertasm** [comment]
I can confirm that OSX 1.3.1 version is still up and running and working ok! 👍  Any of you having issues on your Mac?

**Comment by robertohuertasm** [comment]
I've changed the path where icons where downloading as it has been removed in insider's version. Now it should be working for both versions.

**Comment by ianrobrien** [comment]
Yes confirmed fixed in Windows 7/VS Code 1.3.1/vs code icons 1.4.0. I'll double check my Linux install tonight but I'll assume it's fixed. Thank you!

**Comment by ianrobrien** [comment]
Hi again - unfortunately this does not seem to be resolved on my Linux box. Here's some info:

> VS Code version: 1.3.1
> vscode-icons version: v1.4.3

I ran `sudo chown -R $(whoami) /usr/share/code` and also confirmed I am the folder owner with `ls -la /usr/share/code`. I am running Ubuntu 16.04. I'm happy to provide logs or debugging info but it's probably quicker for you to spin up a virt box :grinning:

**Comment by robertohuertasm** [comment]
Have you executed Icons Update command?

**Comment by ianrobrien** [comment]
Icons Update worked! I'm surprised I missed that.

**Comment by jens1o** [comment]
;)
