### ISSUE TITLE
Icons don't show up (VsCode 1.3.1) Fedora

### ISSUE THREAD

**Issue by eladcandroid** [robertohuertasm/vscode-icons#81]
After setting the right privileges and enabling icons
OS: Fedora 24
VsCode 1.3.1

![screenshot from 2016-07-13 08-15-03](https://cloud.githubusercontent.com/assets/13297000/16792546/06f2f3ec-48d2-11e6-9c6b-bad4395e8439.png)

**Comment by NeilAllen** [comment]
This is my finding, with 1.3.1, too - Windows 10

**Comment by xfilipe** [comment]
Here too, Fedora 23

**Comment by robertohuertasm** [comment]
See #79

**Comment by robertohuertasm** [comment]
Hey guys, can you reinstall your VSCode and download 1.4.0 version of this extension? Don't worry as your extensions and configurations won't be lost. 😉

**Comment by jsnjack** [comment]
Still see no icons...

**Comment by mrmlnc** [comment]
Works fine on Windows 10 (build 10586.494) with VS Code 1.3.1 & 1.4.0-insiders (2016-07-13T05:07:03.170Z).

**Comment by robertohuertasm** [comment]
@jsnjack have you make a clean install of vscode? Are you getting some error? Could you open the   Developer Tools and see if you have some message in your console?

**Comment by jsnjack** [comment]
I reinstalled it with dnf, then executed chown command, then F1 -> Enable icons. Vscode restarts and I'm getting no errors. My developer tools shows only:
```
[Extension Host] vscode-icons is active!
```

**Comment by robertohuertasm** [comment]
I guess you've used 1.4.0 version of the extension, haven't you? Just to discard things...

**Comment by NeilAllen** [comment]
I'm on a Win10 preview build (14372). Removed & Reinstalled VSCode & added the extension; still have the same issue.

The dev console, too, reads: [Extension Host] vscode-icons is active!

**Comment by jsnjack** [comment]
Yes, I updated it from the vscode before reinstalling it. I don't see the way to say what exactly version it is, but it is the latest at the moment (which is 1.4.0, I guess)

**Comment by robertohuertasm** [comment]
@NeilAllen have you used the Enable Icons command?

**Comment by NeilAllen** [comment]
That's Cracked it!

`Icons Enable` 

Apologies if I've lead you on a wild goose-chase.

N

**Comment by eladcandroid** [comment]
It works for me with the 1.4 version :+1:

**Comment by robertohuertasm** [comment]
@jsnjack it seems that @eladcandroid has managed to make it work in Fedora 24 with 1.4.0. In order to check this, you can go to the extension manager on the left tool bar and see which is the version you have installed.

**Comment by jsnjack** [comment]
I already checked it in the extension folder. I have 1.4.0 installed

**Comment by robertohuertasm** [comment]
@jsnjack try icons update command

**Comment by jsnjack** [comment]
@robertohuertasm Update command worked! Thank you!
