### ISSUE TITLE
vscode-icon is disabled after update VS code

### ISSUE THREAD

**Issue by nguyenquynhan** [robertohuertasm/vscode-icons#82]
VSCode Version: (version 1.3)
OS Version: WIN 10

Each updated VS Code times, vscode-icon is disabled, then I must reenable vscode-icon, why? Can you help me please?

**Comment by robertohuertasm** [comment]
See #79

**Comment by robertohuertasm** [comment]
@nguyenquynhan I've recently pushed v.1.4.0 and it should be working now 👍
