### ISSUE TITLE
Feature request: Only color icons when file is modified

### ISSUE THREAD

**Issue by jsynowiec** [robertohuertasm/vscode-icons#83]
If enabled, all icons could be displayed in grayscale until a file is modified (or is new). For such files icons should be colored. This might be introduced as an optional setting.

**Comment by robertohuertasm** [comment]
This is not certainly in my roadmap as it is not a trivial functionality to implement given the current state of the VSCode extension API. I can't promise you anything but I'll consider it in the future. 😉

**Comment by robertohuertasm** [comment]
@jsynowiec if you're into grayscale icons @jedmao provides a [custom package](https://github.com/jedmao/vscode-icons/blob/grayscale-icons/icons.zip?raw=true) Read the readme in order to know how to use it. 😄

**Comment by jsynowiec** [comment]
@robertohuertasm already did and I have them ;-) Thanks! But this doesn't help identifying what changed.

**Comment by robertohuertasm** [comment]
@jsynowiec that's right, but as I said this is completely out of the scope at the current moment. Let's wait for the VSCode team to move forward and see if they can provide a proper API for this kind of extensions.

**Comment by robertohuertasm** [comment]
Closing this. See #328. I would suggest to create an issue with this in the vscode's repo.
