### ISSUE TITLE
Icons Not Displaying After Latest Update

### ISSUE THREAD

**Issue by michaelmaw** [robertohuertasm/vscode-icons#84]
Updated the extension to the latest version this morning and icons no longer show up. I'm running VS Code 1.3.1 (latest) on Windows 10 Pro 64-bit. Tried uninstalling the extension and reinstalling but still no luck. Icons showed up fine before applying the latest update.

**Comment by futuremint** [comment]
Same here, VS Code 1.3.1 on OS X.  I also tried uninstalling and reinstalling but still no icons. My VS Code looks so boring now :(

**Comment by erenhatirnaz** [comment]
+1 I tried running as administrator, but nothing has changed.
VS Code version: 1.3.1
OS: Windows 10 Pro 64bit

**Comment by MLefebvreICO** [comment]
@futuremint This is not related.

As for your problem I had the same issue, the way to make them back is to make sure the plugin is enabled and then press F1 and do "Icons Enable", it will reboot vscode with the icons now on.

**Comment by michaelmaw** [comment]
That did the trick for me. But first open VS Code as Administrator, then F1 "Icons Enable", restart VSC, fixed.

**Comment by erenhatirnaz** [comment]
@MLefebvreICO Thanks, that worked.

**Comment by robertohuertasm** [comment]
Please, see #78, #79, #80, #81 and #82

**Comment by jens1o** [comment]
should we add a FAQ Markdown File for questions like this?

**Comment by robertohuertasm** [comment]
@jens1o, that's right. I thought that the current docs are more or less ok but this issue leads me to think your way.

**Comment by robertohuertasm** [comment]
@jens1o I've just published another version with some basic faqs in the readme.

**Comment by mammad2c** [comment]
@michaelmaw not work for me :( , 
win 10
vsc 1.3
vsicon 1.4.3

**Comment by jens1o** [comment]
Are there any errors in console?

Could you open a new issue?

**Comment by mammad2c** [comment]
@jens1o no error. 
Is important to create new issue?

**Comment by robertohuertasm** [comment]
@mammad2c have you tried the FAQs? The usual procedure is to reinstall your VSCode from scratch, then F1 and "Icons Enable". If that's not working, then try "Icons Update". If still not working and no console errors present we'll have to dig into it. Usually, people is behind a proxy (see #21) but this case leaves some errors in the Dev Console. Please, let me know! :wink:

**Comment by mammad2c** [comment]
@robertohuertasm  i did the FAQs and i got theese error: 
![vs-icon](https://cloud.githubusercontent.com/assets/16647736/16907036/b9679b26-4cd4-11e6-8a89-d41e130f3afc.png)

**Comment by mammad2c** [comment]
i fixed it with set : 
`"http.proxyStrictSSL":` false,` from [issue 21](https://github.com/robertohuertasm/vscode-icons/issues/21)
and downloaded the project and extracted icons folder in appropriate folder.

**Comment by Aisuko** [comment]
@michaelmaw It is work for me ,thanks

**Comment by Farouk19** [comment]
File -> Preferences -> File Icon Theme -> VSCode Icons
