### ISSUE TITLE
Creating a folder the icon is a file

### ISSUE THREAD

**Issue by MLefebvreICO** [robertohuertasm/vscode-icons#85]
When we create a new folder, while entering the name of it, the icon next to it is an empty file.

It would be better to see a new folder icon instead.

**Comment by jens1o** [comment]
I think this is a native VS Function, isn't it?

**Comment by MLefebvreICO** [comment]
No as VS doesn't show any icons beside it when the extension is disabled

**Comment by robertohuertasm** [comment]
@MLefebvreICO  What is you OS? Insiders or normal VSCode?

**Comment by MLefebvreICO** [comment]
@robertohuertasm Windows 10 64bits. Normal VSCode.

**Comment by robertohuertasm** [comment]
I've tested it in W10 64bits and once you name the folder and hit enter the folder icon appears. Is this not happening to you? Is the file icon remaining?

**Comment by MLefebvreICO** [comment]
It is appearing, but when in "creation" mode(when you type your new folder name), it will put a file icon next to it, instead of a folder.

**Comment by robertohuertasm** [comment]
Yes, I'll dig into it but it may be not possible to fix if the team have changed how they put class names to different items. Anyway, it's a minor issue given that the folder icon finally appears once it's created.

**Comment by MLefebvreICO** [comment]
Yes but still I would like that if we could fix it, if not that is ok

**Comment by robertohuertasm** [comment]
@MLefebvreICO of course. I'll see what we can do about it 😉

**Comment by robertohuertasm** [comment]
This seems to have been solved by the vscode team.
