### ISSUE TITLE
vscode 1.3.x Why icons are transparent...?

### ISSUE THREAD

**Issue by frogcjn** [robertohuertasm/vscode-icons#88]
<img width="213" alt="2016-07-15 16 55 00" src="https://cloud.githubusercontent.com/assets/1777562/16868991/34a7f530-4aad-11e6-80ac-fe2a23483ad8.png">

**Comment by robertohuertasm** [comment]
Please, read the readme faqs and try what it's said. It will also good to have more info about your system, extension version... it looks like you haven't executed "icons update" command.

**Comment by frogcjn** [comment]
@robertohuertasm , unfortunately, I've tried, but it is still not working.

**Comment by robertohuertasm** [comment]
I'll suggest you to reinstall VSCode.

**Comment by frogcjn** [comment]
@robertohuertasm, unfortunately, still not working.

**Comment by robertohuertasm** [comment]
Which OS?

**Comment by frogcjn** [comment]
OS X 11.12 beta 2 (16A239j),  VSCode 1.3.1

**Comment by fenbox** [comment]
![image](https://cloud.githubusercontent.com/assets/360618/16893304/a5761418-4b66-11e6-9978-170209762540.png)
![image](https://cloud.githubusercontent.com/assets/360618/16893318/06a607ca-4b67-11e6-9e16-2b3ddb532ebc.png)

**Comment by robertohuertasm** [comment]
@fenbox are you also using OS X 11?

**Comment by fenbox** [comment]
@robertohuertasm OS X 10.11.5

**Comment by robertohuertasm** [comment]
@fenbox it seems that you're having trouble downloading the icons.zip file... Are you behind a proxy?

**Comment by robertohuertasm** [comment]
@fenbox it seems that you're having trouble downloading the icons.zip file... Are you behind a proxy?

**Comment by robertohuertasm** [comment]
@frogcjn can you open the developer tools and see if you have something in your console?

**Comment by fenbox** [comment]
@robertohuertasm Yes, I can't download the zip file directly. Use proxy and run `Icons Update` works for me.

**Comment by robertohuertasm** [comment]
@frogcjn can you confirm that? In case you want to get information about how to proceed if you're behind a proxy see #21

**Comment by frogcjn** [comment]
[Extension Host] null
threadService.ts:214 [Extension Host] null
