### ISSUE TITLE
SQL is not just mysql

### ISSUE THREAD

**Issue by matheusssilva** [robertohuertasm/vscode-icons#89]
The extension shows mysql icon for sql files. But SQL is not just mysql.
My suggestion is the default [database icon](https://www.google.com/search?q=database+icon&client=ubuntu&hs=Wuu&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjc_s73gfnNAhXBkJAKHVHqDFwQ_AUICCgB&biw=1315&bih=641)

**Comment by AlekSi** [comment]
Oh yes! I use PostgreSQL and can't stand MySQL! 😡

-

Seriously, it's confusing.

**Comment by robertohuertasm** [comment]
Will be released in 1.7.0 today!
