### ISSUE TITLE
Support for offline icon packages

### ISSUE THREAD

**Issue by JabX** [robertohuertasm/vscode-icons#93]
Hello,
I tried using the extension at work but I got blocked by my corporate proxy while trying to download the icon package (I can't even download extensions there anyway).
I saw that there were an option to load a different icon package, but it looks like it must be located somewhere online to work (well, it didn't work when I tried to specify a local path for the icons.zip file). Instead of trying to solve the proxy issue, I think it would be a good idea to add support for local icon packages.

**Comment by jens1o** [comment]
In generally, JavaScript cannot read your disk out. VS Code is running in a Virtual Machine.

I think it is difficult, to inject even more JavaScript Code in VS to read your data.

Why you cannot just download the extensions at home, you just need to update them daily when it is time to update VS Studio. It will be cached locally.

**Comment by robertohuertasm** [comment]
Hi JabX, I've also been playing with this idea. You can make it work locally very easily as those icons are precisely downloaded to a local folder '/vs/workbench/browser/parts/editor/media/icons/'

I'll create a new option to allow specifying a custom local path in next releases. :+1:

**Comment by ywmail** [comment]
I'm also using vscode behind a corporate proxy, but i use cntlm to change the encryped proxy to an unencrypted one, after setting the proxy of vscode, I can download extensions, but the vscode-icons extension does not honor the proxy setting of vscode. so i put the icons.zip on a intranet web server and it works ok now.

**Comment by robertohuertasm** [comment]
in #21 @madrus says:

> Ok. SOLVED!!! Thanks to the tip of @pplawucki. While dubble checking, I have found out that I had no http_proxy nor https_proxy variables configured among the Windows environment variables. I have added them, restarted VSCode and bum! The icons work.

Have you tried that?

**Comment by ywmail** [comment]
Yeah, it works after add the `HTTP_PROXY` and `HTTPS_PROXY` to the  Windows environment variables.

**Comment by robertohuertasm** [comment]
I've provided the option to use local icon packages. Please read the readme for further instructions 😀
