### ISSUE TITLE
icons.zip cannot be downloaded.

### ISSUE THREAD

**Issue by ywmail** [robertohuertasm/vscode-icons#94]
I'm using vscode behind a proxy, but the vscode-icons do not honor the proxy setting of vscode.

**Comment by robertohuertasm** [comment]
in #21 @madrus says:

> Ok. SOLVED!!! Thanks to the tip of @pplawucki. While dubble checking, I have found out that I had no http_proxy nor https_proxy variables configured among the Windows environment variables. I have added them, restarted VSCode and bum! The icons work.

Have you tried that?

**Comment by ywmail** [comment]
Yeah, it works after add the `HTTP_PROXY` and `HTTPS_PROXY` to the  Windows environment variables.
