### ISSUE TITLE
Improve icons in Light Themes

### ISSUE THREAD

**Issue by alexlacasa86** [robertohuertasm/vscode-icons#95]
Some yellow icons like YML, JS or JSON are indistinguishable on light themes.

<img width="227" alt="captura de pantalla 2016-07-18 a las 12 19 20" src="https://cloud.githubusercontent.com/assets/6088482/16911981/e5e38e32-4ce1-11e6-9ccc-95510c61922d.png">

**Comment by robertohuertasm** [comment]
This is related to #7 . The extension already provides a way to add custom icons and you can find a gray scale icon palette in the readme.
