### ISSUE TITLE
Icon request: .erb extension new icons

### ISSUE THREAD

**Issue by gvn182** [robertohuertasm/vscode-icons#96]
ERB is the html template for ruby on rails, very similar to .cshtml 
http://apidock.com/ruby/ERB/

**Comment by robertohuertasm** [comment]
I've created a new one. A hybrid between ruby and html... hope you like it...

**Comment by robertohuertasm** [comment]
5bb7085377cd43dfa92cb1adc2b21c11d4c701e0 I will release it soon in 1.5

**Comment by robertohuertasm** [comment]
Already released.
