### ISSUE TITLE
Clojure and ClojureScript

### ISSUE THREAD

**Issue by keawade** [robertohuertasm/vscode-icons#99]
The current icon for Clojure seems to be an old one and it isn't associated with the file extensions `.clj`, `.cljs`, `.cljc`, or `.edn` [which are used for Clojure](https://en.wikipedia.org/wiki/Clojure).

**Comment by robertohuertasm** [comment]
Done in d2b89be0e72ce38a68076a041644baad7caa240b
I will release it in 1.5

**Comment by robertohuertasm** [comment]
Already released

**Comment by jens1o** [comment]
Wow, you're really fast @robertohuertasm :+1:
